### PR TITLE
apply: replace spread operator

### PR DESCRIPTION
**Pull request by Mottie**
Given the comment at the top of the apply.js file

> // Not using some slow features of ES6,... spread,...

This PR replaces the spread operator in the `replaceAll` function.

### CODE REVIEW

**Comment by tophf** [comment]
Eh, don't optimize blindly. Measure the current performance first. That comment was pertinent when we had a global mutation observer that checked every element in the entire document.

**Comment by tophf** [comment]
When all current PRs get merged, I'll remove that comment, switch to ES6, and wrap the entire code in IIFE so that on orphaning we'll only detach all listeners and the leftovers will be garbage-collected automatically.

**Comment by Mottie** [comment]
Let me know if there's anything I can do to help.

**Comment by tophf** [comment]
Test the usercss PR more.

**Pull request closed without merging**
