### PR TITLE
Light grey theme

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
Light grey / lower contrast default UI theme with actual detail styling.

The original dev explained the lazy default theme by saying it's meant to be plain because it's a CSS extension which can be themed by users. We have continued using that excuse because we're also lazy, and themes are subjective, so achieving a general consensus can be a PITA. We added some cool custom elements and mostly left them unstyled.

Most of us agree the white is too harsh, the contrast is too high, and the lack of styling is bland in the current default. I end up having to test stuff in the default all the time, and I find it cringe-worthy, so I finally decided to propose an alternative.

### CODE REVIEW

**Comment by Mottie** [comment]
Nice work! The light grey is much easier on the eyes. 🥇

**Comment by TayliaM** [comment]
This looks really nice and professionally done. Agree with Mottie that it is much easier on the eyes!

**Comment by tophf** [comment]
I disagree with the above. I like the dark theme by @narcolepticinsomniac and the default white, but not this one. It doesn't look better than the default, it doesn't look professionally done. I disliked it at the first glance. I definitely don't want to use it. The proper solution is to add a darkness slider like in Adobe products, it's not really difficult, and the first step is to switch to variables.

**Comment by narcolepticinsomniac** [comment]
>I disagree with the above.

Shocking.

>I like the dark theme by @narcolepticinsomniac

Funny, I recall the exact opposite when I proposed that one.

>I like... the default white

You're on an island there man.

>it doesn't look professionally done

Cheap shot. Despite your impeccable taste, I put a lot of time and effort into it.

>~~achieving a general consensus~~ *coming up with something tophf won't immediately hate on* can be a PITA

>The proper solution is to add a darkness slider like in Adobe products

I know, let's talk about it like it's the ultimate solution, never implement it, then have the same conversation this time next year. A slider isn't gonna do anything in the way of adding style where there is none, and the majority of our UI has little to none. 

>disabled styles, and the rest of the UI looks almost exactly the same... The zebra background will likely disappear

Legitimate criticism? Why start now? 

The main goal was to lower all around contrast. That was bound to be a process, and I didn't think it was perfect. I expected we'd discuss details and tweak contrast wherever necessary. Zebra striping is simple, we could go back to the semitransparent if it's preferable. The colors I switched to are actually slightly more obvious than the current default striping on my screen, but how zebra striping is achieved isn't some big deal.

Seems like you'd rather dismiss it entirely than work to improve it. If that's the case, I'm gonna quit pissing in the wind here.

**Comment by tophf** [comment]
>Funny, I recall the exact opposite when I proposed that one.

I like it visually, not how it's implemented.

>I know, let's talk about it like it's the ultimate solution, never implement it

Many cool features are suggested and no one implements them.

>Seems like you'd rather dismiss it entirely than work to improve it. If that's the case, I'm gonna quit pissing in the wind here.

I know you're good at dark themes but maybe light themes just aren't your thing. I don't know. It might make sense to find a good grayish site with similar structure of info and use it as an inspiration.

**Comment by narcolepticinsomniac** [comment]
>not how it's implemented

I'd ask WTH that means, but it's irrelevant to the topic.

>maybe light themes just aren't your thing.

Well you like the current default, so maybe they're not your thing? 

I've had a few people testing right along, and the general consensus was "unquestionably better".

**Comment by TayliaM** [comment]
I'm still seeing lots of potential with this style.  After using it for the last day or so, the stark look of the default has become really noticeable.The popup would need very little change in my opinion, as the lower contrast works well there and looks very nice. I do see tophfs point about the lack of contrast in the manager, and I would love to see if some tweaks could be made there that might help address that issue.

**Comment by tophf** [comment]
99% of people using the internet don't have any problems with white background, which is used in 99% of the sites. Just like me. It means there's nothing wrong with my opinion here and nothing inherently wrong with the white theme we currently have. Anyway, what happens right here right now is the exact reason we don't change the default theme.

**Comment by tophf** [comment]
>I'd ask WTH that means, but it's irrelevant to the topic.

It's actually relevant. A desirable default theme implementation is the one that simplifies theming and recoloring. For example, by using CSS variables.

**Comment by narcolepticinsomniac** [comment]
>It's actually relevant.

The relevant  topic is whether or not the default theme is too bright, high contrast, and unstyled, and whether a light grey, lower contrast, more stylized default would be an improvement. If you wanna nitpick the code, that's another story. I can tell you that while you're still experimenting with different shades everywhere, variables would be a huge PITA. I don't get the obsession with variables, but they'd be pretty simple to convert once you know all actual values for sure.

Anyway, you were referring to "the implementation" of my personal style at the time, which is most definitely irrelevant.

>99% of people using the internet don't have any problems with white background

Even more irrelevant. Don't try to lump us in with normal web users. I'd lowball the percentage of userstyle users who became userstyle users in order to get rid of bright white backgrounds at more than half.

>nothing inherently wrong with the white theme

Such a glowing endorsement. Pretty sure that's the biggest compliment we could hope to get on it. Most power users have themes, so they don't really care, but we consistently get the occasional negative comment on the UI. The actual layout is very decent, so I assume at least some of those are because of the default theme, for all the reasons already mentioned.

>there's nothing wrong with my opinion here

Who said there was? There's nothing wrong with anyone's opinion here. It's not about any of our individual opinions, it's about what we all decide is best collectively. I'm still never going to use the default theme, so I didn't spend time on this because it's something I love and want so badly to use personally. I did it because I think it's better UX for casual users.

There's currently four opinions, which ain't much to go on. Three are on the record that light grey/low contrast is "obviously better". I'm not saying this current draft is perfect. I expected we'd discuss a bunch of details. I think the popup is real nice, the editor/options are pretty good, and the manager could probably use a little more work, as mentioned.

We've always made these types of decisions fairly democratically, and there's certainly not enough feedback to go off, but you're the only one so far who prefers the white. If this PR dies a slow death because nobody else cares, or everybody prefers the current default, so be it. I figured it was a good base to work with, and we'd compromise a bit to come up with something we all felt was an improvement, but that was assuming you weren't adamantly opposed to the whole concept in the first place.

I fully expected you to shit all over some of the details, because we've worked on CSS together in the past. I didn't expect you'd be so dismissive right off the bat. I also wouldn't expect you to resort to petty insults, or out-of-context statistics to support your opinions, so I was wrong on multiple counts.

There's not much you couldn't put your foot down about if you feel that strongly about it. None of it was the reaction I expected from you, so that's my miscalculation.

**Comment by DanaMW** [comment]
Variables would all0w for the slider function where  the style can be slide from light to dark and anywhere in between

**Comment by DanaMW** [comment]
i like it more styled thanks for your work

**Comment by tophf** [comment]
The thing is, I really think this theme in its current state is worse than the default one. I really disliked it the moment I opened the style manager. This is rare, because usually I can browse almost any site without thinking there's something wrong with how it's themed.

As for guessing the percentage of users who can't stand the white background, it's moot unless we have the numbers, which we'll never have, probably. 

I also think that being a person who can use sites utilizing either white or dark backgrounds without any problems makes me more objective on this matter compared with someone who can't stand white backgrounds or high contrast.

The thing I dislike the most by now, though, is this kind of discussion we're having here. I find it pretty embarrassing, almost disgusting, so maybe the time to change the default theme hasn't come yet.

**Comment by narcolepticinsomniac** [comment]
>I find it pretty embarrassing

I'm not embarrassed by anything I've said here, but I can understand why you'd be. I'm you're biggest fan, which is the only reason I've made a real effort here to remain civil.

**Comment by tophf** [comment]
Well, I guess I could have been less civilized too, it's quite easy, but the embarrassing thing here is that we even discuss each other and the effort to remain civil. It means this is no longer a technical discussion, but almost a typical "internet fight" with trolling, implications, emotions, etc. Certainly not something I enjoy seeing (not anymore at least), much less to participate.

**Comment by narcolepticinsomniac** [comment]
Agreed. Let's at least give it a rest for a while.

**Comment by tophf** [comment]
I can definitely agree to a simplified implementation, which is good enough until we implement customizable UI darkening, here's an example for the manage page:

```css
body {
  background-color: #ddd;
}
#header {
  background-color: #eee;
}
.newUI .entry.odd {
  background-color: rgba(128, 128, 128, 0.1);
}
```

Something as simple as that.

**Comment by DanaMW** [comment]
You know ever since you mentioned that slider i have have been trying to figure out how to implement it here because I already have all my whole system colors as variables in one "colors" css I like that idea a lot.

**Comment by the-j0k3r** [comment]
Firefox recently implemented in dev edition a way to respect the Style of the OS, I think this means Windows 10 Dark/Light choices, because as far as I can remember Linux side this was never an issue and it always went dark whenever.

I dont know what the Windows side of things for Opera and Chrome in that respect and here is the real question.

Would addons/extensions be able to follow/respect what the OS as set or not assuming all browsers supported it (Im assuming browser support is needed in order for addons to support it too)?

**Comment by Mottie** [comment]
Deferred to #517.

**Pull request closed without merging**
