### PR TITLE
Hide focus outlines without crippling accessibility, plus buttons

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
I was kinda missing the active state change for buttons, so I wanted to add one. Transparent gradient is inverted for active state, and the result is pretty damn close to default browser button active state, so I'm pretty happy with it. The other problem, once again, was the focus outline which also sucks on focused buttons. @Mottie has already guilt-tripped me every time I screw with accessibility for the sake of aesthetics, and rightfully so. Default browser buttons hide outlines, but still allow for them when focused by the keyboard. We need some similar code. Before bugging @tophf, I decided to look around for existing solutions and came across [what-input](https://github.com/ten1seven/what-input). It's 4kb minified, which seems reasonable, and it appears to work well. The same could probably be accomplished with less code, but this one adds a couple other attributes to key on for state changes which may or may not be useful in the future.

Even better, we can fix the other hidden outlines which work with keyboard focus. Digging around, I found the collapsible headers in manage and edit, and a couple in the regex message-box. The other ones with hidden outlines are slider checkboxes, but their inputs were hidden. I tried the `tabindex` hack on `.onoffswitch` which didn't work. It focused, but had no action. Maybe I did it wrong. Anyway, I unhid the inputs and positioned them accordingly to allow for outline and keypress action. It works fine in the options, but the initial keypress action for message-box sliders registers twice. Works fine on subsequent keypresses. Some difference in the js, I guess. Like I said, maybe not the best way to go about it in the first place, IDK. Just wanted to see if I could get them working.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Hmm. Was testing something, and that glitch on message-box slider initial click is also present in the master. I guess I didn't break it after all. Maybe the hacky CSS solution here is good enough to make sliders accessible.

**Comment by Mottie** [comment]
It's looking good so far...

The option sliders are working for me! There are a few minor issues that can be fixed by adding a `tabindex` to enable or disable focus, and a few other places that need javascript to be fixed. I can work on a PR after this one is merged.

The what-input code is a bit too bloaty. I've found, but haven't tried, [fix-outline](https://github.com/kimmobrunfeldt/fix-outline) which might work just as well.

**Comment by narcolepticinsomniac** [comment]
>The option sliders are working for me!

Really? In the manager? I'm still using that StackOverflow test style, and when I open the message-box in the manager, the first slider click always registers twice. Can repro in Cent and Google Chrome, in this PR and with the master.

**Comment by Mottie** [comment]
Oh, I meant the options page. I'm not sure which message box you're referring to.

**Comment by narcolepticinsomniac** [comment]
You guys will know better whether what-input is best for the task. I think `data-whatintent` is a nice additional feature and may be useful to combine with `data-whatinput` for some edge-cases where outlines may sneak through.

**Comment by narcolepticinsomniac** [comment]
In the manager, click the cog:

message-box

**Comment by Mottie** [comment]
I'm still not sure what you mean... I can tab to the slider and press space to toggle it. The color selector isn't working, that's one of the places that will need a little work.

**Comment by Mottie** [comment]
Oh, I see... the *first* time you tab to it the slider is toggling twice. I'll look into it.

**Comment by narcolepticinsomniac** [comment]
I thought "initial click" was pretty clear. At least you can repro, so I don't feel like I've been taking crazy-pills. =)

**Comment by Mottie** [comment]
I made a bunch of tweaks to make stuff more accessible, but my work depends on your PR. You ok with me adding to this PR? I've already started with this PR and accidentally rebased from master a few times.... so I don't know the best solution other than forcing an update here.

**Comment by narcolepticinsomniac** [comment]
Go right ahead.

**Comment by Mottie** [comment]
Whew... Ok, it's still not 100% perfect. We need to figure out how to move focus out of CodeMirror... pressing <kbd>Tab</kbd> with or without modifiers doesn't get you out of the editor.

**Comment by narcolepticinsomniac** [comment]
>We need to figure out how to move focus out of CodeMirror

Yeah, I noticed that. I was shooting for "not terrible", but I dig the ambition. Haven't really navigated around via keyboard yet. Why TF are the popup buttons so high with empty space underneath them? Is that from the US.o PR?

**Comment by Mottie** [comment]
Oh, that's probably because I added a 1px border underneath... it shows up on focus. I too dislike the blue outline. Especially when it's outlining the `<a>` wrapping the `<svg>`.

**Comment by tophf** [comment]
>Why TF are the popup buttons so high with empty space underneath them? Is that from the US.o PR?

No longer. I've just finished fixing the most basic issues.

**Comment by narcolepticinsomniac** [comment]
Nice.

**Comment by narcolepticinsomniac** [comment]
Damn, you were thorough. Skipped over "Mozilla Format" icon. Not sure if that was intentional. I'd say the underlines may not be obvious enough. Given the fact that we have a special class for keypress focus, we could really style icons and links with fills and colors, without affecting their regular look.

The editor is an issue, and I'd also think it'd be nice for message-box popups to automatically receive focus.

**Comment by narcolepticinsomniac** [comment]
Underline showing up uninvited:

underline

**Comment by Mottie** [comment]
Fixed... silly link underline.

**Comment by tophf** [comment]
* Removed what-input because changing attributes that high in DOM affects the entire layout so the browser recalculates it fully. On my computer it took 20-50ms depending on the amount of elements.
* Wrote a renderer-friendly implementation that sets `data-focused-via-click` attribute on the input itself or its label.
* Removed the alternative focus decoration on icons. Initially I liked it, but after actually using keyboard navigation I realized it's super-weird to have a different style for icons.
* Fixed the shape of outline on svg icons, previously distorted due to margins and such on the elements within the focusable one.
* Short-circuited tabbing in messagebox so it doesn't escape to the page

**Comment by narcolepticinsomniac** [comment]
>Removed what-input... Wrote a renderer-friendly implementation

Figured you might. LGTM.

>Removed the alternative focus decoration on icons

I wasn't a fan either. Mottie did an excellent job making practically all clickable elements keyboard accessible though.

>Fixed the shape of outline on svg icons

Outlines look nice, but we've got some funky positioning now. Shouldn't be to difficult to recreate margins differently.

>Short-circuited tabbing in messagebox so it doesn't escape to the page

Works well, but for some reason skips "applies to" SVG info icon.

**Comment by tophf** [comment]
Go ahead.

**Comment by narcolepticinsomniac** [comment]
>Go ahead.

What? Adjust icon positioning?

**Comment by tophf** [comment]
Yep.

**Comment by narcolepticinsomniac** [comment]
Will do. Gotta eat first.

**Comment by tophf** [comment]
Got impatient, opened two manage pages from the master and this PR and adjusted some margins myself.

**Comment by narcolepticinsomniac** [comment]
>Got impatient

Guess so. Was just about to upload. Removed some redundant code you already did, but I think there's some other stuff. Mostly info SVG. Give me a sec to upload. If it's unnecessary we can just revert it.

**Comment by narcolepticinsomniac** [comment]
I should probably just redo it with your changes to double-check everything. Fuck.

**Comment by tophf** [comment]
I can revert mine, it was a quick hack.

**Comment by narcolepticinsomniac** [comment]
Nah, NBD. Barely beat me to the punch.

**Comment by narcolepticinsomniac** [comment]
`#sections-help` info icon in editor isn't keyboard accessible. Last one I noticed.

**Comment by tophf** [comment]
> Chrome 86 introduces [...] `:focus-visible` [...] the same heuristic the browser uses when it's deciding whether to show a default focus indicator. 

http://blog.chromium.org/2020/09/giving-users-and-developers-more.html

I don't think we want to use it in the foreseeable future though as we have our own polyfill. But if we ever decide to raise `minimum_chrome_version` to 86 or above then it's on the table.

**Comment by narcolepticinsomniac** [comment]
RemindMe! 4 years =)

**Pull request merged**
