### PR TITLE
rework and move newUI+theme to options.html

### PR DESCRIPTION
**Pull request by tophf**
Moves the 1) newUI options block and 2) theme button from the manager into the options page which we/I wanted to do since forever once we made a dedicated options page. The shortcuts button is already present in the options page.

Now that the theme option is in the options page, it should increase its discoverability which was kinda low due to the dense and cluttered nav panel in manage.html.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Moving to options makes sense. Clicked the link, and USO won't load. Perhaps we should consider linking [the archive](https://33kk.github.io/uso-archive/?category=chrome-extension) instead? Obviously, if we did, we'd need to drop USO from the link text, but I think we should regardless. Something more generic, like "Find styles for the Stylus UI", or something similar.

**Comment by tophf** [comment]
USO takes ~10 seconds to load here. The archive doesn't seem to provide style customization controls.

**Comment by tophf** [comment]
Hmm, the archive converts everything to usercss which exposes style customization controls so I guess it's alright. Switching.

**Comment by tophf** [comment]
I've used `Find a Stylus UI theme`, WDYT?

**Comment by narcolepticinsomniac** [comment]
> WDYT?

That's something similar. LGTM.

On the fence as to whether recent > popular. Shame there's no combination of the two.

**Comment by tophf** [comment]
Fine, let's use the default order.

**Comment by narcolepticinsomniac** [comment]
That works. Thanks tophf.

**Pull request merged**
