### PR TITLE
convert USO styles to USO-archive on update

### LINKED ISSUE #1122: [Feature Request] Check for presence of UserCSS header in styles installed from UserStyles.Org and parse it if present
* **Browser**: Google Chrome 86.0.4240.198 (doesn't matter)
* **Operating System**: Windows 10 (doesn't matter)
* **Stylus Version**: 1.5.13
* **Screenshot**: none

I have a style on USO used by over 260k users. Recently decided to move it on GitHub, but apparently Stylus ignores UserCSS header in styles installed from USO. As the result I can't use @updateURL to point users with existing installations to a new location and the only option I have is to make them remove existing one and install manually from a new location.
Style in question: https://userstyles.org/styles/101141/ru-adlist-css-fixes

Is it possible to implement UserCSS header parsing for styles installed from USO and use it when it's present and valid?

### PR DESCRIPTION
**Pull request by tophf**
There will be no additional prompts or tooltips shown for this process.
The advanced settings of the style are preserved.

Also fixes #1122 - the author of the style should update it on USO site first, then Stylus will use the embedded UserCSS metadata during the next update check.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Trying see this conversion in action, but nothing so far. I've got a couple traditional styles from USO, and I kinda expected them to convert on the next update check. Since they didn't, I'm assuming they only convert if an available update is detected? 

If one of the benefits of conversion is more reliable update checks, wouldn't it make sense to convert on the first check regardless?

**Comment by tophf** [comment]
Yes, it's updated only there's an actual update because I thought it might surprise the users otherwise. The md5 check is still super fast on USO.

**Comment by tophf** [comment]
On the other hand, some/many styles will never be updated on USO anymore because their authors has abandoned the dying site so it might make sense to convert the styles regardless of whether they've changed.

**Comment by narcolepticinsomniac** [comment]
> The md5 check is still super fast on USO.

Well, that's a small miracle.

> it might surprise the users otherwise

For anyone paying attention, who knows what they're looking at, it's gonna be somewhat of a surprise whenever it happens. Most users will likely never notice, and the ones who do are probably smart enough to figure out the change.

Are we doing the conversion ourselves, or pulling from the archive? If it's the latter, I imagine scraper lag might be a significant issue.

I'd say immediate conversion either makes more sense, or no difference. If it really doesn't matter, we can leave it as-is. Your call.

**Comment by tophf** [comment]
No conversion, I'm using USO-archive's style. The scraper runs once a day, I guess, so indeed waiting for an actual update would be unreliable. Okay, gonna switch unconditionally then.

**Comment by tophf** [comment]
Eek, it's somewhat scary observing 50 styles getting automatically updated to USO archive in the style manager... BTW the version text is too long in the list - it's a full date and time - so I wonder maybe we should show just the first 4 digits for USO-archive styles...

**Comment by narcolepticinsomniac** [comment]
Sounds reasonable enough.

**Comment by tophf** [comment]
Done. Don't forget to make a backup or better even test on a separate browser profile.

**Comment by tophf** [comment]
Merging so more people can test it in master.

**Comment by narcolepticinsomniac** [comment]
Think I ran into a little bug here. After updating styles individually, manually, the icon didn't change to double checkmarks on one. Didn't throw an error, but there obviously was one.

starstsWith

**Comment by tophf** [comment]
Should be fixed now in master.

**Comment by coalpha** [comment]
I'm not sure if this is the right place to do this but thank you so much for converting the "Find Styles" thing to the USO-archive. It makes it so much faster and just overall less painful. Otherwise the search just hangs because USO is so slow.

**Comment by narcolepticinsomniac** [comment]
> I'm not sure if this is the right place to do this

Close enough. =) 

It's a nice change from "your website sucks", considering we have no control over that broken POS.

**Pull request merged**
