### PR TITLE
fix styling of options frame in FF

### LINKED ISSUE #1021: RegExp include not working for embedded options in FF
FF 79.0 (64-bit)

Noticed when testing 8's sync PR, but seems to be the same in stable. When importing styles, certain style overrides for options weren't applied.

Tried a generic test style, and for some strange reason, RegExp rules which should apply to the options iframe, are simply ignored. 

Works fine in Chromium, and also in FF if you right-click source and open options in a new tab. Style shows up in the popup as active in an iframe, but no style is injected.

Test:

```
@-moz-document regexp("(chrome|moz)-extension://.*options\\.html.*") {
*{color:red!important;}
}
```

### PR DESCRIPTION
**Pull request by tophf**
Fixes #1021.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
LGTM. Something else weird though, now that I'm testing. That test style only shows up as an active iframe popup entry in FF.

**Comment by tophf** [comment]
Yeah, Chrome doesn't list it, investigating...

**Comment by narcolepticinsomniac** [comment]
Always nice to determine the root of the problem is another random WontFix with no justification.

**Comment by tophf** [comment]
The workaround turns out to be quite convoluted if I do it properly (without hardcoding the options url, that is) so maybe we'll let the bug affect us?

**Comment by narcolepticinsomniac** [comment]
That's fine. It's not the biggest deal.

**Pull request merged**
