### PR TITLE
fix split-btn with popup.stylesFirst

### PR DESCRIPTION
**Pull request by tophf**
* switched to pure CSS flex+order instead of JS
* moved the main buttons to the top

image

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Pref is toggling the opposite of expected behavior, meaning 'Styles before commands' puts commands first, and vice-versa. 

When commands are first, inline search causes styles to disappear, for all practical purposes.

**Comment by narcolepticinsomniac** [comment]
> moved the main buttons to the top

If the plan was to switch this to the default, and the toggle's text wasn't changed for whatever reason, I kinda hate that idea.

**Comment by tophf** [comment]
Fixed the bugs, good catch.

> If the plan was to switch this to the default, and the toggle's text wasn't changed for whatever reason, I kinda hate that idea.

The buttons are moved when the styles are shown at the bottom. Previously they were displayed in the middle of the popup which looked weird as the buttons kinda divided the popup. In the default layout they're at the edge, which is why I've moved them to the edge in the alternative layout.

**Comment by narcolepticinsomniac** [comment]
> Previously they were displayed in the middle of the popup

Been so long since I've even looked at 'commands first', didn't realize what you were referring to. Buttons on top when the action block is on top seems like the natural choice. Imagine it looked kinda goofy before.

LGTM now.

**Pull request merged**
