### PR TITLE
fix FF shortcuts button

### LINKED ISSUE #898: Button “Shortcuts” in manage.html doesn’t work on Firefox
* **Browser**: Firefox
* **Operating System**: Arch Linux
* **Stylus Version**: 1.5.10

When clicking on “Shortcuts” button, it does nothing. Console shows:
> Error: No `options_ui` declared

But “Options” button → “Shortcuts” works fine.

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
My bad, always forget to reference the relevant issue. Closes #898

I didn't exactly test it extensively, but it seems to do the trick.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
I wasn't even aware FF had its own shortcuts dialog built in, tbh. Why don't we use it in Chromium as well? Do we think Chromium's is more intuitive? 

Also, do you think it's worthwhile to check `localStorage.installType` and provide an option to configure reload if it's dev?

**Comment by tophf** [comment]
1. Chromium's built-in customization page is more intuituve because it handles key presses and converts them into key names so the users don't need to type the shortcut. It also automatically discards hotkeys it can't handle.

2. IDK, I would remove our dialog completely in FF and just show an instruction how to open FF's built-in UI.

**Comment by narcolepticinsomniac** [comment]
>more intuitive because it handles key presses

Yeah, I figured. I was kinda impressed with our humble dialog though.

I'm not interested in making any how-to. If we're gonna leave it as-is, adding reload conditionally might be nice. If we did, is there a less clumsy way than what I came up with while just testing:

```
  let hotkeys;
  const dev = localStorage.installType !== 'normal';
  if (dev) {
    hotkeys = new Map([
      ['_execute_browser_action', 'optionsCustomizePopup'],
      ['openManage', 'openManage'],
      ['styleDisableAll', 'disableAllStyles'],
      ['reload', 'reload'],
    ]);
  } else {
    hotkeys = new Map([
      ['_execute_browser_action', 'optionsCustomizePopup'],
      ['openManage', 'openManage'],
      ['styleDisableAll', 'disableAllStyles'],
    ]);
  }
```

**Comment by tophf** [comment]
A.
```js
  const hotkeys = new Map([
    ['_execute_browser_action', 'optionsCustomizePopup'],
    ['openManage', 'openManage'],
    ['styleDisableAll', 'disableAllStyles'],
    ...localStorage.installType !== 'normal'
      ? ['reload', 'reload']
      : [],
  ]);
```
B.
```js
  const hotkeys = new Map([
    ['_execute_browser_action', 'optionsCustomizePopup'],
    ['openManage', 'openManage'],
    ['styleDisableAll', 'disableAllStyles'],
  ]);
  if (localStorage.installType !== 'normal') {
    hotkeys.set('reload', 'reload');
  }
```

**Comment by tophf** [comment]
B seems simpler and more obvious I guess.

**Comment by Gusted** [comment]
A is overcomplicated b is simple

**Comment by narcolepticinsomniac** [comment]
Cool, thanks. I'l double-check it and probably add it here when I get a chance.

**Comment by narcolepticinsomniac** [comment]
Meh, adding reload conditionally might've been cool if it worked with "install from file", but when I just checked, those register as normal installations. Other than that use case, I suppose there is none really, since the only other method is temporary, AFAIK.

**Pull request merged**
