### PR TITLE
Editor: horizontal resize grip

### PR DESCRIPTION
**Pull request by tophf**
I want to make the resize grip more accessible. 
A better default style is welcome if you have ideas.

clip289-fs8

And maybe do something upon double-click on the grip? 
Like autosizing to code height or window height or ...?

@narcolepticinsomniac, @schomery, PTAL.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
I like it. Standard look is a few lines, but they're not commonly the entire width of an editor either. Dotted is a decent look regardless. I also like the idea of double-click actions. Perhaps it could alternate between viewport height and folded to a minimal size of one line. Even better if it could remember sizing after closing/reopening.

Viewport height should probably be a calc that allows for the header above (with less padding) and one "applies to" underneath. As I suggested in the "sections as tabs" issue, it might be nice to apply that same viewport sizing to the first section by default anyway.

Resizer has a minor z-index issue with autocomplete suggestions. There's also a couple other weird things with suggestions. The checkbox in the header has some extra space above it, the suggestions look like they should have normal blue hover backgrounds but they don't, and the suggestions themselves aren't very intuitive. Like in the screenshot, `display: n` suggests all properties beginning with "n". Obviously, smarter autocomplete suggestions only suggest possibilities relevant to the property and letters typed so far.

chrome_2017-06-27_17-44-32

**Comment by tophf** [comment]
Thanks for the comprehensive assessment as always. I've fixed z-index issue, but not the spacing issue as I couldn't reproduce it (the html for all options is identical) so it might be something in your custom theme. Double-click now simply maximizes/restores the size. I'm not yet ready to overhaul the editor so I'm reluctant to add complex features. As for autocomplete relevancy, that's just the way csslint works, I haven't investigated it.

**Comment by tophf** [comment]
Cherry-picked as 9ffc5253915afa9afe80e504a1ed983646c0ecc5 and 565f23fa6ef0e1632e129001ffbd6537099805a5 in master.

**Comment by narcolepticinsomniac** [comment]
> it might be something in your custom theme

Yup. My bad.

> Double-click now simply maximizes/restores the size. I'm not yet ready to overhaul the editor so I'm reluctant to add complex features. 

Checked it briefly, and it appears to work well. Pretty convenient, as is the extra wide resizer. Nice little details.

As for autocomplete relevancy, it could be better, but it's NBD. The thing that was bugging me more is the hover background of the options not working correctly. That's usually pretty standard stuff for webkit select/options appearance.

**Pull request closed without merging**
