### PR TITLE
Custom checkbox and select elements

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
Give me a minute to upload everything.

### CODE REVIEW

**Comment by tophf** [comment]
Grr, lots of indents in html files are wrong, probably due to tabs you insist on using... Someone will have to fix it.

**Comment by narcolepticinsomniac** [comment]
Replace all checkbox and select elements throughout the UI. At least I think I got all of em. All checkboxes are now customized, tightly wrapped and absolutely positioned in their labels, with the exception of `.style-name` checkboxes, which use practically every positioning trick and still have a 2px tweak specific to FF for the manager entries. I also made custom `select` elements, which use SVG carets for arrows. Arrow elements are siblings, so they can be styled accordingly for any state changes, and are positioned to look like part of the normal `select` element. Tested in Chromium, Opera, and FF, and everything looks virtually identical. Not tested in any ancient, buggy versions of any browser, like FF52 or IE6.

Quite a bit of copypasta involved before fine tuning, so along with any obvious bugs, be on the lookout for any redundant, unnecessary code, up to, and including syntax/indent errors, which I'm sure there are some of. 

@tophf I also fixed the overflow bug in the manager. It didn't make any sense. That ridiculously long variable calc seemed to add up, but not only was there overflow, it got progressively worse if you undocked the browser and adjusted the width. I fucked with this for far too long before figuring out that it was something simple, `#installed{table-layout: fixed;}` does the trick. I remember asking you why the hell we were using a `table` layout. Whenever a site I frequent uses them for anything other than charts, I tend to rewrite them. You were right to mention not rewriting the whole thing, because I probably would have, I was so annoyed. It's the CSS I'm least familiar with, and there's so many weird combinations of elements and properties to achieve layouts which can almost always be done so much more simply and sanely with `flex`. Anyway, I'm pretty sure it's resolved.

**Comment by tophf** [comment]
No margins around the text in the filter dropdowns. Too tight.

clip408

Dropdowns in the editor are fine.

As for the `display: table` in the manager, we've discussed at least several times: it makes the column widths adjust to the content and window size. Not something you can do with flex. OTOH you argued we can impose arbitrary limits, but I see no benefit in that. Everything is a tool, and a tabular list in the manager is perfect for tables.

**Comment by narcolepticinsomniac** [comment]
Say something positive. You don't even have to mean it.

**Comment by tophf** [comment]
The editor page looks great! I see no problems there.

**Comment by tophf** [comment]
I'll fix the tabs/indents and push a commit into your branch, brb.

**Comment by tophf** [comment]
* manager: "as usercss" checkbox mark is super tiny in FF
* manager: no margins around the text in the filter dropdowns
* editor: beautifier dialog in FF has a horizontal scrollbar
* popup: you've removed `html:not(.moz-appearance-bug)` prefix, please restore it
* all css files: add `html:not(.moz-appearance-bug)` prefix on all rules that don't work in [FF52 ESR](https://www.mozilla.org/en-US/firefox/organizations/all/) just like I did in popup.css, that is all rules that rely on `-moz-appearance: none` being actually applied, which wasn't the case before FF54.
* find a way to configure your editor to use 2 spaces instead of tabs
* `table-layout: fixed` has broken automatic width adjustment based on content. I've never seen the bug it's supposed to fix myself nor in reports so I suppose the problem is quite rare; anyway there might be better fix

**Comment by narcolepticinsomniac** [comment]
>Please find a less destructive solution.

Well, that sucks. I'm out of ideas at the moment, and I won't be able to look at that variable calc for a while without clawing my eyeballs out. Table layouts are are not my specialty. Black magic fuckery, if you ask me.

>No margins around the text in the filter dropdowns. Too tight.

This doesn't bother me. Since they're a hybrid checkbox/select, I thought they looked better mimicking the checkbox look. `option` doesn't have a lot of stylability when rendered by the browser. I think there's a pseudo-selector for them. Maybe their `appearance` can also be customized, but I've never even attempted to screw around with them, tbh.

AFAICT, as they are, we'd have to make those `select` 22px like the rest for `option` to look the same as the others, which'd screw up the checkbox/label look. Even just briefly tested 22px positioned up with overflow hidden on the parent, and they still seem to inherit the visible height of the select element. 

>find a way to configure your editor to use 2 spaces instead of tabs

Yeah, my bad. I already did in Sublime, although it occasionally fucks off, but I use ++ for html because of the vertical selection feature. Didn't even notice till it was too late. 

>`html:not(.moz-appearance-bug)`

I think it's insane to jump through hoops for an old, buggy browser which has its end-of-support date in the next few months. 

>editor: beautifier dialog in FF has a horizontal scrollbar

Simple fix. I'll do that, parent selectors (begrudgingly, if I have to), and `option` height if you really think it's more important than the general appearance of the parent elements.  Also open to any suggested workaround for those. 

Might be tomorrow though. I've got a massive headache from staring at the computer for too long.

**Comment by tophf** [comment]
>Might be tomorrow though.

Ok.

> I thought they looked better mimicking the checkbox look. 

It looks really weird compared to all other dropdowns we have. Like someone simply forgot to add the margins. Not sure I ever saw such a thing in a UI. Definitely needs fixing.

>I think it's insane to jump through hoops for an old, buggy browser which has its end-of-support date in the next few months.

It's used by hundreds of users currently compared to the thousands of FF users overall and those numbers will only increase because many users dislike the new FF. Also, the hoops aren't that hard to jump, should be just a one-time thing. I really hate all the FF-induced issues we've been having in general, and I dislike FF, but even so I can add it myself, NBD.

**Comment by narcolepticinsomniac** [comment]
>those numbers will only increase because many users dislike the new FF

Support ends "early 2018". That's as definitive as I found quickly googling. If users stick with an unsupported version, why would they migrate to an older, buggy ESR which will no longer be an "ESR"? Bad enough all the workarounds for FF in general polluting the code. Will we still cater to its bugs once it's no longer supported? Not even saying this is the point to draw the line since it's not that complicated, but there has to be a point eventually. Mostly, I find that bitching about it is somewhat therapeutic.

>manager: "as usercss" checkbox mark is super tiny in FF

They're all super tiny. That one's just misaligned. Looks like this is the culprit:

```
#newStyleAsUsercss-wrapper svg {
    margin-top: -2px;
}
```

No clue why it's only borked in FF, otherwise I would've noticed.

**Comment by tophf** [comment]
We'll remove the workaround when the amount of FF ESR users will decrease due to natural reasons in a year or so. No need for Stylus to look completely broken in a browser that can run it without any functional problems.

**Comment by narcolepticinsomniac** [comment]
I get it. I'm just annoyed.

**Comment by tophf** [comment]
Maybe it'd be less aggravating if we put FF-specific kludges in a section that runs only in FF?

```css
@supports (-moz-appearance:none) {
  html.moz-appearance-bug .svg-icon.checked {
    display: none;
 }
}
```

**Comment by tophf** [comment]
I've fixed these minor compatibility issues, gonna upload the commit soon.

**Comment by tophf** [comment]
Here's what I did:

* Extracted the styles for checkbox and select in global.css file loaded as the first stylesheet. The original .css files override only what's needed.
* Disabled the new styles in FF < 54 via `@supports` in global.css and 2 simple rules.

* Restored beautify dialog behavior: it always rearranged its contents based on selection.
  Lightened the arrow's background, otherwise the dropdown boxes were the most prominent thing.
* Restore autosizing of aligned options to fit different lengths in translated UI. This is not ideal as it may overflow the sidebar anyway, but solving it properly would be a separate task.

* Removed `table-layout: fixed` from manage.css.
* Added custom selects in usercss config dialog.
* Shifted the selectors in filters to match other checkboxes in the header. It's different from that in the list of styles, where a bigger gap is needed since a different action is performed when style name is clicked.

* Reduced animation duration on checkboxes as it made UI appear tardy/laggy.
* Darkened the checkbox background and made it transparent because otherwise many/all dark themes for Stylus would become hard to use. Now they only have problems with our bright colors in the hover effect.

* Tested in FF 52, 57, 59, Chrome 54, 62, 64

**Comment by narcolepticinsomniac** [comment]
>Extracted the styles for checkbox and select in global.css

Nice.

>Added custom selects in usercss config dialog.

Cool. Didn't realize there were any.

>Shifted the selects in filters to the left a bit to match other checkboxes in the header

I was going for that. Were they off? Anyway, as they are now, dropdowns are kinda crowding checkboxes. I'd suggest we remove the left padding from those `select` and add the 4px to the `left:` positioning on `select-resizer`.

>Reduced animation duration on checkboxes as it made UI appear tardy/laggy.

Fine. Killjoy.

>Darkened the checkbox background and made it transparent because otherwise many/all dark themes for Stylus would become hard to use.

I originally went with semitransparent, but decided against it because it results in slightly inconsistent coloring on zebra-striped backgrounds. More so in the popup, less so in the manager because their backgrounds are fainter, but still slightly off.

I suppose we could change striped background checkbox transparency to match, but that's kinda silly. As far as considering 3rd-party themes, we should consider them more than most projects because that's usually zero, but we shouldn't make compromises to improving the default for them.

As a theme author, I'm annoyed with the changes we're making, but they are improvements. I didn't realize you'd push the popup checkboxes so quickly, and had to update with at least a sloppy patch so they weren't completely screwed up. Bottom line, authors are responsible for making themes work with the UI, not the other way around.



Ironically, `.nobreak` is broken:

usercss

Defeats the purpose of circumventing allowing the browser/OS to screw with checkbox/label alignment, and obviously the checkmark positioning. What are we trying to "unbreak", and where else are we using `.nobreak`?

**Comment by narcolepticinsomniac** [comment]
Seems like you rebased this PR, right? CM "find" function appears to be slightly bugged again in this PR and not in the master. Only js I touched here was beautify, which I wouldn't think could affect "find". Also didn't think I broke anything there anyway. It's not completely broken, but it's not jumping to the first instance or marking the scrollbar.

**Comment by tophf** [comment]
Yuck, the nobreak rule in global.css is a mistake, idk why it got there but all rules needed for the element are within manage.css. I wasn't sure we need such a class, actually, but I thought it might come in handy.

I've added a js hack for the aligned options to make sure unbreakable long words break themselves prior to breaking the layout. We'll find a better solution later. Current hack seems both flexible and robust so it'll hold for a while.

How do I reproduce the find bug? Just tried searching and can't see the bugs you mentioned.

**Comment by narcolepticinsomniac** [comment]
Might depend on the search term.

Searched for `:not(.slider)` in https://pastebin.com/mZUfQ718

**Comment by tophf** [comment]
Jumps and highlights.
Apparently there's a secret trick to make it fail. It'd be helpful if you can identify it. Otherwise I'm not sure I can find the bug right away.

pic

**Comment by tophf** [comment]
However I see another bug with highlighting the scrollbar: sometimes it doesn't go away.

**Comment by tophf** [comment]
I want this PR to be merged ASAP. We have too many of them. Will you try that padding trick now? Otherwise let's merge this and you'll deal with the details later.

**Comment by narcolepticinsomniac** [comment]
Have an errand to run real quick. Go ahead and merge if you want. Only a couple minor details which can be worked out after. I'll also retest "find" in master afterwards.

**Comment by narcolepticinsomniac** [comment]
BTW, that highlight console error is what I saw when it failed.

**Comment by tophf** [comment]
Ok. As for the transparent background-color on checkboxes, I did it because toggling in the popup would be severely compromised for all users with custom dark themes for days/weeks until style authors update their themes.

**Comment by narcolepticinsomniac** [comment]
CM "find" in current master: 
[CM.zip](https://github.com/openstyles/stylus/files/1529509/CM.zip)

>I did it because toggling in the popup would be severely compromised

I get that, but semitransparent on top of darker zebra-stripe does result in slightly darker checkboxes. Surprised it doesn't bug you, but not the biggest deal in the world.

**Comment by tophf** [comment]
I can repro with "Highlighting" option set to "disabled", thanks.

**Comment by narcolepticinsomniac** [comment]
>Will you try that padding trick now? 

NM. You changed the way I was suggesting on purpose so the dropdowns were less crammed. The fact that dropdowns are real close to checkboxes is NBD.

The slight discrepancy of checkbox backgrounds on zebra-striping still bugs me. After theme authors have had a couple weeks to adjust, I'd prefer we switch them back.

**Comment by narcolepticinsomniac** [comment]
Alright, there are little discrepancies in all browsers on Windows, FF being the worst with its terrible select arrows and little alignment issues. The real test though is Linux, which I just checked for the first time in a while. Our custom elements work really well, but I needed to override the system color, and also eliminate their ill-conceived inner text dotted line for focused elements.

Two of the three most difficult UI elements which require both CSS and HTML are good now, but a quick glimpse at Linux FF will tell you that we need to do the easy ones. Buttons and inputs are simple CSS fixes. Inputs are a no-brainer, whereas everyone has button appearance preferences. 

To avoid any conflicting opinions if possible, I'll suggest we mimic Windows Chromium buttons, which are very light gray with a very subtle gradient. I would like to recreate the gradient with a transparent image though, so we can put a very subtle transition on them. That's one of my preferences already creeping in.

The other issue is fonts. Most Linux distros don't ship with a lot, and instead use their shit Moto-Sans font everywhere. Some cruel joke, I believe. Not only are they odd looking, but bold is crazy bold. I would assume we could include Arial to override the system font. 

I am also curious about any suggestions for button fonts for all OSes. Default buttons rendered by the browser seem to sprinkle a little magic on the fonts. They look slightly bolder than recreating them with the same font in custom CSS. Not a factor with light text on dark, but slightly noticeable with dark text on light. It might be wise to use a font that has a "medium" weight, kinda like Google does with Roboto.

I took some screenshots of our UI in Linux. My system theme is dark, which is just as common as light, if not more so. Either way, the oversizing of elements remains the same. Chromium is not a factor. Even if you override program appearance, Chromium only lets you affect the UI, nothing within pages. In newer Linux releases you can override the top chrome of the browser, including the URL bar which is pretty awesome. FF, however, allows the system to override everything by default. Everything is oversized, and the alignment sucks, although it's not quite as bad as it used to be.

Current release version of manage:

old-manage

Current master version of manage:

new-manager

Current release version of edit:

old-edit

Current master version of edit:

new-edit

Options, to be thorough:

old-options


Obviously, the last tricky element is `input[type="number"]`. I don't know of any good way of customizing these, but I haven't experimented much. In Chromium, the arrows are a pseudo-element which can be styled to some extent, but I've never attempted to customize them wholesale. In FF, I don't even know what's going on, but they seem like a single uncustomizable element. I don't use FF devtools much, and it occurs to me that maybe I should've enabled inspecting the shadow DOM or something. In Windows they're not bad, certainly not enough to screw around with anyway, but in Linux they're pretty fucking terrible.

screenshot from 2017-12-05 03-23-22

**Comment by narcolepticinsomniac** [comment]
Oh, and we have one radio input. Fairly simple SVG should do the trick.

**Comment by Mottie** [comment]
Maybe we should include [normalize](https://github.com/necolas/normalize.css)?

I think it might benefit us to start using a css framework like [bulma](https://github.com/jgthms/bulma) or [pure.css](https://github.com/yahoo/pure/) and build from there. I haven't seen many (any?) frameworks that add custom checkboxes & selects because it's such a nightmare to get right.

And although [this MDN article](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Advanced_styling_for_HTML_forms) is a bit dated, it's an interesting read &ndash; especially the examples section. What's really interesting is that the [form libraries](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Advanced_styling_for_HTML_forms#The_road_to_nicer_forms_useful_libraries_and_polyfills) it recommends have been deprecated or haven't been updated in a long time (up to 5 years).

**Comment by tophf** [comment]
Yeah, inputs and buttons. Let's start with those. 

As for normalize.css, its file contents doesn't seem to be helpful, the framework approach would probably imply changing the entire internal layout so it's out of the scope here.

**Pull request merged**
