### PR TITLE
fix infinite loop in colorizeInvisible

### PR DESCRIPTION
**Pull request by tophf**
Fixes a longstanding bug.

~Alleviates #888.~
~Theoretically this bug could be the sole culprit of that issue.~ Alas, no.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Unfortunately, I see the same issue in this PR, testing that style in FF 74. If typing consistently in the editor, memory still skyrockets.

**Comment by tophf** [comment]
Well, someone else will have to debug that as I try to use FF as little as possible.

**Comment by narcolepticinsomniac** [comment]
Guess if 8 was gonna weigh in here, he would've done it by now. Seems like an improvement we should merge regardless, huh?

**Comment by tophf** [comment]
Seems like a trivial change, nothing to review :-)

**Comment by narcolepticinsomniac** [comment]
Good enough. Under normal circumstances, I would think CM scrollbars not being functional would warrant an expedited update. Still blows my mind that I'm the only one to report it, and I open up FF maybe once a month. We should still probably fix it and merge whatever else is good to go, and start thinking about pushing an update.

**Pull request merged**
