### PR TITLE
Colorpicker

### LINKED ISSUE #210: Color picker in the editor
* Easy: a colorpicker button under a section.
  Arguably a color wheel icon, maybe not even a `<button>`, but just an image.
* Hard: a colored rectangle should be shown before any color (like in devtools) and clicking the rectangle would show a color picker.
  Needs investigating the devtools source code or a similar project's.

### PR DESCRIPTION
**Pull request by tophf**
Fixes #210
(assuming we don't want a separate colorpicker button under code editors)

Please test: [zip](https://github.com/openstyles/stylus/archive/colorpicker.zip).

a47fea3d8c

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
I's say you did a nice job making it more light weight. Even with one of my monstrosity code styles, I didn't see a resource suck that would make it prohibitive. It's functionality seems pretty flawed though. when altering existing hsl(a) strings, it's losing the beginning parenthesis, and cramming the entire new string into the hue value. Also seems like there should be a "revert" option.

**Comment by Mottie** [comment]
I'll be back this weekend. I'll take a look then.

**Comment by tophf** [comment]
I've fixed everything I think. Please retest.

**Comment by narcolepticinsomniac** [comment]
Big improvement. Perhaps I'm not all that adventurous, but values all seem to change correctly in my testing. A couple minor positioning issues. If the value hits a new line, the clickable square should go with it:

position

and far-right positioning doesn't account for scrollbars:

scrollbar

**Comment by tophf** [comment]
Fixed various issues found on discord channel and the scrollbar positioning bug.
Can't fix wrap-breaking because this is how CodeMirror inserts widgets.

**Comment by narcolepticinsomniac** [comment]
Another minor detail. `cursor: pointer;` should be on the inner actionable element:

```
.codemirror-colorpicker > .control > .hue,
.codemirror-colorpicker > .control > .opacity {
    cursor: default!important
}
.codemirror-colorpicker > .control > .hue > .hue-container,
.codemirror-colorpicker > .control > .opacity > .opacity-container {
    cursor: pointer!important;
}
```

Otherwise, LGTM.

**Comment by tophf** [comment]
What is the difference? I'm not familiar with the issue. I see currently it sets `pointer` on the outer `.hue` and `.opacity` only.

**Comment by tophf** [comment]
Ah!!! I see, the bounding rectangle is incorrect now.

**Comment by Mottie** [comment]
The only issue I'm seeing is when you click on a swatch to open the colorpicker, then scroll away from that line, the colorpicker remains. You can still edit and change the color but it doesn't scroll back to the line where it was opened from. I know you can use undo/redo to jump to the line, but it might be nice if the colorpicker did this for you.

**Comment by tophf** [comment]
> but it doesn't scroll back to the line where it was opened from

That's intended. Keeping the current viewport is more important as it's a predictable UX. IMO closing a colorpicker popup doesn't warrant changes to the scrolling position. If a user scrolled away while working on a color, we can assume there's something they want to see and I'm not yet convinced they would always want the view scroll back.

>use undo/redo to jump to the line

Simply press the arrow keys, which is IIRC the standard way to reveal the input caret since forever.

**Comment by tophf** [comment]
415c1f2361

I've decided it's weird to have the bottom 40% of UI white (even 30%, subtracting the sliders area).

**Comment by tophf** [comment]
Actually, I wanted to rewrite it since the first seconds I saw the code and today I did it. Now both js files are fully rewritten. And dark/light theme is switched automatically on every invocation of the colorpicker popup depending on the background color of the editor.

**Pull request merged**
