### PR TITLE
Enhance: faster msg.sendBg

### LINKED ISSUE #771: Extension page FOUC in the latest Canary
* **Browser**: 78.0.3902.0 (Official Build) canary (64-bit) (cohort: Clang-64)
* **Operating System**: Windows 7
* **Stylus Version**: 911108c3b48a2dc1e
* **Screenshot**:

I think the problem is that `runtime.getBackgroundPage` becomes slower on Canary.
*Cent Browser Version 4.0.9.112 (Official Build) (32-bit) (Chromium 74.0.3729.169)*
image
*Google Chrome | 78.0.3902.0 (Official Build) canary (64-bit) (cohort: Clang-64)*
image

Maybe we should switch back to `extension.getBackgroundPage`. However, I don't remember why we switched to `runtime.getBackgroundPage`. Maybe because of a FF bug or something?

### PR DESCRIPTION
**Pull request by eight04**
Fixes #771

### CODE REVIEW

**Comment by tophf** [comment]
* The FOUC is fixed.
* It's still noticeably slower than 1.4.22 because an empty dark background is shown for almost half a second on each refresh.

**Comment by eight04** [comment]
> an empty dark background is shown

You mean the style list is loaded slower?

**Comment by tophf** [comment]
Yep, didn't think I'm the only one seeing it so here's the profiler timelines:
* this PR https://puu.sh/EdFb0/d9eafb65b9.png
* 1.4.22 https://puu.sh/EdFbT/1e1eaa70b5.png

**Comment by tophf** [comment]
Looking at the timeline length, 1.4.22 completes all activity in 480ms vs 580ms for this PR/master, so theoretically it may be caused by some change in the built-in CSS of the manager page. The styles db is identical in both cases.

**Comment by narcolepticinsomniac** [comment]
>The FOUC is fixed.

That was the main goal.

>480ms vs 600ms

Suppose there's room for improvement, but preventing FOUC is still a win.

**Pull request merged**
