### PR TITLE
Add inline search filters

### LINKED ISSUE #757: Customize Sorting of a Theme Search
* **Browser**:
* **Operating System**:
* **Stylus Version**:
* **Screenshot**:

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
Closes #757

Mostly just the UI at this point. Centered the dropdown link and menu, and set up translations. Hooked up the menu click function, and I know we don't usually bother with auto-closing menus, but it felt kinda weird with this one, so I added scroll and click listeners to auto-close.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
@tophf Obviously, feel free to commit here directly whenever you get around to it. I'm about as psyched about doing the JS as you were the UI, so I'm not screwing with it unless I have to. =)

**Comment by tophf** [comment]
When I finished wiring it up, testing revealed that USO ignores the `sort` parameter. Either they deleted the corresponding code or they've renamed some of the so-called routes in the search URL. Anyway I couldn't figure it out so far. Will try later.

**Comment by narcolepticinsomniac** [comment]
Damn. We should know better than to trust that they haven't broken anything they have access to. Hope you find a solution, but it sounds like a long shot. That'd be a shame, it would've been a nice little feature.

**Comment by tophf** [comment]
Guess they've butchered it upon switching to the new site design.

**Comment by narcolepticinsomniac** [comment]
We gave this a shot, but AFAIK there's no sane way to do this if USO gutted the API.

**Pull request closed without merging**
