### PR TITLE
don't export redundant values

### LINKED ISSUE #1372: [Bug] Avoid redundancy in exported styles
# Bug Report

### Bug Description

When exporting Usercss styles, the resulting JSON file contains the same CSS in two "copies" (original and post-processed). JSON file could be significantly smaller, if the the redundant CSS is not included.

### CSS Code

For example, create a new Usercss style with:
```css
/* ==UserStyle==
@name           Test
@namespace      github.com/openstyles/stylus
@version        1.0.0
==/UserStyle== */

@-moz-document url("https://www.example.com/test.html") {
    body {
        background-color: green !important;
    }
}
```
Then export the style. The JSON file will contain essentially the same CSS twice:
```json
...
"sections": [
  {
    "code": "body {\n        background-color: green !important;\n    }",
    "start": 181,
    "urls": [
      "https://www.example.com/test.html"
    ]
  }
],
"sourceCode": "/* ==UserStyle==\n@name           Test\n@namespace      github.com/openstyles/stylus\n@version        1.0.0\n==/UserStyle== */\n\n@-moz-document url(\"https://www.example.com/test.html\") {\n    body {\n        background-color: green !important;\n    }\n}",
...
```

The `sections` component can be computed from `sourceCode`, there is no need to have it in exported JSON.

### System Information

- OS: Linux
- Browser: Firefox 90
- Stylus Version: 1.5.21

### PR DESCRIPTION
**Pull request by tophf**
fixes #1372

### CODE REVIEW

**Review by eight04 — APPROVED** [review]
LGTM. Tested with Firefox Dev 96.0b8

Note that this is a breaking change, styles without `sections` was considered invalid in older versions.

**Comment by tophf** [comment]
Ah, indeed, and it was the reason why I didn't implement this earlier. An option, disabled by default, then? Most people don't mind the duplication anyway.

**Comment by tophf** [comment]
Or maybe add a right-click to the `Export` button and a tooltip?

**Comment by tophf** [comment]
I found a better solution: a dummy empty `sections`.

**Comment by tophf** [comment]
Hmm, it's only compatible with v1.5.18 and newer. In older versions the empty `sections` will be imported as is. Welp, for practical purposes I guess this is good enough as we don't support severely outdated versions anyway.

**Comment by tophf** [comment]
Re-added shift-click/right-click for a full export as I found a way to show the corresponding note without complicating the UI:

image

>To import the backup file, drag'n'drop it into this page or click the Import button.
>To export a compatible backup for Stylus older than 1.5.18, right-click or shift-click the Export button.

**Pull request merged**
