### PR TITLE
add ":" to prop names in css autocomplete menu

### LINKED ISSUE #914: Suggest auto-comple add a colon symbol
Snipaste_2020-04-30_21-35-19
Current results after Auto-comple: 
### `padding-bottom`

Auto-comple(Ctrl+Space) auto add <kbd>:</kbd> a colon symbol, 
Results after Auto-comple:

### PR DESCRIPTION
**Pull request by tophf**
Fixes #914.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
LGTM. Should we add a space after?

**Comment by tophf** [comment]
I guess we should...

**Comment by tophf** [comment]
Done.

**Comment by tophf** [comment]
Wait, I should add another check...

**Comment by tophf** [comment]
No, everything's fine as it is.

**Comment by narcolepticinsomniac** [comment]
I'll take your word for it. That pig's got some pretty lipstick now. Thanks tophf!

**Comment by dnknn** [comment]
> LGTM. Should we add a space after?
No need to add space.

**Comment by tophf** [comment]
We already added it, tough luck.

**Comment by narcolepticinsomniac** [comment]
Yeah, who asked you? =)

**Comment by dnknn** [comment]
> We already added it, tough luck.

OK, Well, the default seems to be with space.
My personal CSS generally does not have extra space.

**Pull request merged**
