### PR TITLE
Change: a better way to defer page script injection, switch to inline script

### LINKED ISSUE #577: Stylus breaks Zimbra Webclient
* **Browser**: Firefox 63.0.3
* **Operating System**: Windows 10
* **Stylus Version**: 1.5.0
* **Screenshot**:
stulus_bug

Zimbra Webclient (8.7.5_GA_1764.FOSS) is not able to view a mail, it just shows empty space.
Disabling all userstyles does not fix issue.
Disabling Stylus fixes the issue.
Reverting to version 1.4.23 fixes the issue.
Webclient works in AJAX mode, changing to HTML mode fixes issue, but in this mode it's not very convenient to use.

When clicking a mail to open, browser console shows some errors (screenshot):

Error: WebExtension context not found! 3 ExtensionParent.jsm:1021:13

TypeError: x.body is null mail:6621:18

Loading failed for the <script> with source “data:application/javascript;base64,KEVWRU5UX05BTUUgPT4gew0KICAgICAgICBkb2N1bWVudC5jdXJyZW50U2NyaXB0LnJlbW92ZSgpOw0KICAgICAgICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcihFVkVOVF9OQU1FLCBmdW5jdGlvbiBoYW5kbGVyKGUpIHsNCiAgICAgICAgICBjb25zdCB7bWV0aG9kLCBpZCwgY29udGVudH0gPSBlLmRldGFpbDsNCiAgICAgICAgICBpZiAobWV0aG9kID09PSAnc2V0U3R5bGVDb250ZW50Jykgew0KICAgICAgICAgICAgY29uc3QgZWwgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChpZCk7DQogICAgICAgICAgICBpZiAoIWVsKSB7DQogICAgICAgICAgICAgIHJldHVybjsNCiAgICAgICAgICAgIH0NCiAgICAgICAgICAgIGNvbnN0IGRpc2FibGVkID0gZWwuZGlzYWJsZWQ7DQogICAgICAgICAgICBlbC50ZXh0Q29udGVudCA9IGNvbnRlbnQ7DQogICAgICAgICAgICBlbC5kaXNhYmxlZCA9IGRpc2FibGVkOw0KICAgICAgICAgIH0gZWxzZSBpZiAobWV0aG9kID09PSAnb3JwaGFuJykgew0KICAgICAgICAgICAgd2luZG93LnJlbW92ZUV2ZW50TGlzdGVuZXIoRVZFTlRfTkFNRSwgaGFuZGxlcik7DQogICAgICAgICAgfQ0KICAgICAgICB9LCB0cnVlKTsNCiAgICAgIH0pKCJ7N2E3YTRhOTItYTJhMC00MWQxLTlmZDctMWU5MjQ4MGQ2MTJkfSIp”. mail:1:1

Promise resolved while context is inactive
 promisify.js:13
	promisify/</< moz-extension://73d53a57-8f8f-4687-ae22-6cc6c3f9c8ac/js/promisify.js:13:7

Decoded base64 script:
`(EVENT_NAME => {
        document.currentScript.remove();
        window.addEventListener(EVENT_NAME, function handler(e) {
          const {method, id, content} = e.detail;
          if (method === 'setStyleContent') {
            const el = document.getElementById(id);
            if (!el) {
              return;
            }
            const disabled = el.disabled;
            el.textContent = content;
            el.disabled = disabled;
          } else if (method === 'orphan') {
            window.removeEventListener(EVENT_NAME, handler);
          }
        }, true);
      })("{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}")`

### PR DESCRIPTION
**Pull request by eight04**
Reverts openstyles/stylus#758
Fixes #577

### CODE REVIEW

**Comment by eight04** [comment]
> un-cached page loads

Do you mean Ctrl+F5? Not sure if `sessionStorage` will be cleared.

@TayliaM 

How does it compare to the current master?

**Comment by eight04** [comment]
> random FOUC

Can you confirm whether it happens on the first load? The first load is still deferred and the second load (i.e. `sessionStorage` is set) should be identical to the current master.

If we want to reduce the "first load FOUC", maybe we can switch to `localStorage`.

If the "random FOUC" does exist, it might be caused by other changes e.g. the script is injected to `document.head` instead of `document.documentElement`.

> seems like it's faster

The timing should be identical to the current master.

> but it's still a race

Loading page script is always a race, including the current master.

**Comment by narcolepticinsomniac** [comment]
This works exactly as you might expect, which is imperfect to say the least.

>If we want to reduce the "first load FOUC", maybe we can switch to localStorage.

This is still an issue, and switching to `localStorage` doesn't help. Unless we can defer earlier reliably, this is just trading a more obscure bug for one that'll negatively affect far more users. I don't see how we can implement any workaround which we're well aware causes FOUC. 

FOUC on initial load before `localStorage` is set:

screenshot 1890

**Comment by eight04** [comment]
I think it is acceptable since it only appears once.

> I don't see how we can implement any workaround which we're well aware causes FOUC.

Some options:

1. Remove the page script injection. (Which may revert #461)
2. Inject inline scripts instead of using data URL. This is similar to (1) because nowadays, websites usually disable inline scripts. (It fixes #461 though)
3. Create an option to toggle the behavior. Something like Tampermonkey:
  image

**Comment by narcolepticinsomniac** [comment]
>I think it is acceptable since it only appears once.

Once per domain though, which resets when local storage is cleared. The idea that any FOUC is acceptable is a foreign concept to me. If once per domain is NBD, the method should probably be reversed, so we set local storage on no active styles to defer subsequent script injections. I'm not really advocating for that though, because it's similarly flawed.

>Remove the page script injection

Work around one FF bug by removing the workaround for another FF bug. We should probably avoid that rabbit hole if at all possible.

The other suggested options both look like trading one problem for another as well. Unless I'm reading the tone wrong, you don't seem all that thrilled about either of them.

What's really bugging me is that we're debating less than ideal solutions to a bug, which AFAIK, none of us has even personally inspected. There's a few users reporting in that issue, which is already more than I figured would even be affected. I don't imagine there could be whole lot more given the fact that "installing it (if you haven't done it before) can take a while", and "it's a linux based installation / service", but OP lists Win 10 as their OS.

This is likely either another FF bug, or a Zimbra bug, and yes, we should try to work around it just like all the others. A workaround for any particular edge case should never have any negative impact on the majority of users though. If we could actually repro, I have to think there's a better way to detect this conflict earlier and account for it without blindly slowing down injection across the board.

I sympathize with the users experiencing this bug. I guess their best option currently is to either use an older, unaffected version, or a different extension altogether. I googled the install instructions for Zimbra, and on any platform it looks like a goddamn nightmare. Unless somebody can simplify that to the point where installing isn't ten times more annoying than fixing the actual bug ¯\\_(ツ)_/¯.

Maybe someone with it already installed could hook up a Teamviewer session with 8 if he's up for it, since he's basically rewritten most of the content script himself. Otherwise, IDK, since all the proposed solutions seem pretty jenky, I suppose maybe we could implement that blacklist feature and at least offer a way to unbreak it rather than fix it.

**Comment by eight04** [comment]
> Work around one FF bug by removing the workaround for another FF bug. We should probably avoid that rabbit hole if at all possible.

Well, it already happened. Page script injection fixes #461 but breaks #577 and #769.

> you don't seem all that thrilled about either of them.

Suppose a deferred page script is unacceptable:

1. I prefer removing the page script injection because technically, #461 is a website bug, not the extension.
2. If #461 affects too many people, we can try using inline scripts. Since #461 happens on outdated websites, usually, inline scripts are not blocked.
3. If using inline scripts doesn't work (e.g. causes other issues or a buggy site rejects inline scripts), we can implement the `injectMode` option so users can toggle the inject method manually.

**Comment by narcolepticinsomniac** [comment]
>Well, it already happened. Page script injection fixes #461 but breaks #577 and #769.

Yeah, we're already pretty far down that rabbit hole. You don't seem all that bothered about not inspecting the Zimbra bug. Can you tell by the errors that coming up with a better workaround compatible with the others is a lost cause?

If so, I guess the steps you suggested that you'd prefer are the logical choice. I think #461 affects enough people that it's likely a problem, but if there's an alternative workaround that might not be so problematic, that's worth a shot.

I'm not crazy about the idea of `injectMode` as a feature in general. Most users either won't know it exists, or won't really know exactly what it does, no matter how well it's explained. It'd suck to have to flip it globally to fix a single site, and a per-site switch seems unrealistic. Every future injection issue would be even more convoluted.

**Comment by tophf** [comment]
Probably related, here's the FOUC problem I'm observing in Chrome Canary in Stylus style manager, git-bisected to e3d3604afc56357d749237db3e8824a3d3accc99 "Refactor the entire storage system and the section editor (#518)". Also observed with this PR's branch.

Normally I'm still using the same old local Stylus 1.4.22 that I've been working on in the past so I didn't investigate what happens nowadays. And I see a white flash/FOUC on each reload via F5 key in the extension's own style manager page, using a very simple dark style ("Atom styled Stylus", not that it matters) and a lot of styles (like 100). I have a fast PC (i7 4GHz) so maybe it's too fast and it manages to paint those white frames whereas most people don't experience this? Or maybe I have too many styles for the new Stylus.

devtools profiler now: https://puu.sh/EdddQ/493d9a80ef.png
devtools profiler 1.4.22: https://puu.sh/Eddrc/31519263c2.png

BTW importing of my json in the current Stylus takes 10 seconds vs just 2 in 1.4.22. With only one tab open. As someone who spent a lot of time optimizing Stylus I'm disappointed.

**Comment by eight04** [comment]
This is a FF-only bug. Chrome shouldn't be affected.

> here's the FOUC problem I'm observing in Chrome Canary in Stylus style manager

I opened an issue for this: #771

> importing of my json in the current Stylus takes 10 seconds vs just 2 in 1.4.22. With only one tab open

This is an important issue. Would you like to post your styles in a new issue?

**Comment by tophf** [comment]
Done: #772

P.S. given the fact that culprit of FOUC in Chrome is the storage rewrite commit in my use case, maybe it's also negatively impacting the issue at hand in FF, both are FOUC-related after all.

**Comment by narcolepticinsomniac** [comment]
>As someone who spent a lot of time optimizing Stylus I'm disappointed.

1b260ceb62c6c7ac69a3130c5a5b36ad

**Comment by eight04** [comment]
Switched to inline script in e0d8317.

**Comment by narcolepticinsomniac** [comment]
Correct me if I'm wrong, but AFAICT this current version has issues with CSP, and won't even apply styles to sites like Github.

**Comment by eight04** [comment]
> issues with CSP, and won't even apply styles to sites like Github.

Fixed.

---

I disabled the page script preload. There is a bug which makes it impossible (taking at most 3 seconds) to detect if the page is blocking inline styles:
https://bugzilla.mozilla.org/show_bug.cgi?id=1579345

However, since we switched to inline scripts, it should be fast enough. It would be nice if someone can test it on pages without CSP.

**Comment by tophf** [comment]
Technically it should be possible to use webRequest.onHeadersReceived (limited to a hardcoded list of known URLs like github) to add a `nonce` token into Content-Security-Policy header for `script-src` or reuse an existing once (some sites use it) and set that value on the script element's `nonce` attribute. The *adding* of a nonce is not something that should be enabled by default though.

**Comment by narcolepticinsomniac** [comment]
>it should be fast enough

Seems like it is. I tested it briefly, and asked Taylia to as well. I saw no issues, and neither did she. 

>I disabled the page script preload. There is a bug which makes it impossible (taking at most 3 seconds) to detect if the page is blocking inline style.

If it is indeed fast enough, wouldn't the current method be superior anyway? It should fix #461 and any other related bugs for sure. I'd assume it'd also fix the Zimbra bug, at least with no active styles, but we should definitely verify that.

If we go with the current method, is there some reason we'd wanna switch it in the future if Mozilla ever addresses the bug you filed? Is there any reason to leave a FIXME, or any of the `localStorage` code for that matter?

Zimbra users, please test [this version](https://github.com/openstyles/stylus/archive/revert-758-revert-defer-page-script-injection.zip) @AmpliDude @miniBill @flying-sheep @0ki @hwti

Also, please browse around a bit when testing to verify that styles are applying seamlessly.

**Comment by eight04** [comment]
> If we go with the current method, is there some reason we'd wanna switch it in the future if Mozilla ever addresses the bug you filed? Is there any reason to leave a FIXME, or any of the `localStorage` code for that matter?

I'll remove the `localStorage.stylusStyleCount` since we don't need it now. I prefer to keep the comment. It is possible that we have to drop the inline script when those site starts rejecting them (or use the nonce technic suggested by @tophf ).

**Comment by narcolepticinsomniac** [comment]
>It is possible that we have to drop the inline script when those site starts rejecting them

As I understand it, I'm surprised it actually does work, but I tested a few sites I'm aware of in stable and nightly, and it LGTM so I'm not complaining. Hopefully they'll address that bug you filed beforehand if that ever changes.

Let's try this again, since it's pretty much the whole point of this PR. Zimbra users, please test [this version](https://github.com/openstyles/stylus/archive/revert-758-revert-defer-page-script-injection.zip) @AmpliDude @miniBill @flying-sheep @0ki @hwti

**Comment by hwti** [comment]
> Let's try this again, since it's pretty much the whole point of this PR. Zimbra users, please test [this version](https://github.com/openstyles/stylus/archive/revert-758-revert-defer-page-script-injection.zip)

It works fine for me, even when applying a style to Zimbra.

**Comment by AmpliDude** [comment]
Looks OK

**Comment by narcolepticinsomniac** [comment]
Seems like the best option currently. Fixes all the related issues in the limited testing everyone's done so far. Hopefully it holds up better than previous method.

**Pull request merged**
