### PR TITLE
indicate sync error as 'x' in icon badge

### LINKED ISSUE #800: Update browser icon when getting a 401 sync error
https://github.com/openstyles/stylus/pull/787#issuecomment-546574893

### PR DESCRIPTION
**Pull request by tophf**
Fixes #800.

It shows `x` in a red-colored icon badge when any sync error occurs with a tooltip `Sync failed. Please re-login.`
Maybe I should limit it to certain errors, @eight04 do you know which ones?

### CODE REVIEW

**Comment by eight04** [comment]
I think we can ignore network errors. We probably don't want to notify the user when there is no connection.

For the error message, we can't always suggest the user to re-login. There might be other errors e.g. server error, network error, or even bad code.

1. It should be safe to tell user to re-login when we get a 401 error.
2. Maybe we can try to check the error message when getting a 400 oauth error (https://tools.ietf.org/html/rfc6749#section-5.2). [Here is an example](https://github.com/openstyles/stylus/issues/860#issuecomment-661617902)

**Comment by tophf** [comment]
Okay, now it's shown only on 401 and when `interaction` is present in the error text. I don't know about `400` so it's up to you to decide.

**Comment by narcolepticinsomniac** [comment]
> check the error message when getting a 400 oauth error

Seems like this would also be necessary. I'm guessing we've already gotten enough significant bug fixes to warrant a follow up release in the immediate future. We probably wanna give it a little while to make sure anything major has been addressed, but sometime soon, and this PR should definitely be included.

@eight04 Can you hook up a proper 400 error message check?

**Comment by eight04** [comment]
Done. IDK why the lock file was updated.

I'll file a PR with better (?) sync logic that handles #1152 and with automatic re-log disabled.

**Comment by narcolepticinsomniac** [comment]
Finally saw this occur naturally, but it was triggered by a 502 "unknown" error. Seemed to happen after the computer came out of sleep, so probably just some momentary connection issue. I didn't think these types of errors would trigger a warning. I assume it reconnected on its own, but the warning badge remained till I restarted the browser.

**Comment by tophf** [comment]
I don't think it reconnected because [emitStatusChange](https://github.com/openstyles/stylus/blob/c17dddb0ee82244a7afe1f7dc736c5e5f843a3ad/background/sync-manager.js#L207) would run on success and clear the badge.

As for 502, https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502

>502 error is usually not something you can fix, but requires a fix by the web server or the proxies you are trying to get access through.

So this is a network error which we need to ignore. Gonna add it now.

**Comment by tophf** [comment]
Er, wait, maybe we don't need any special processing for 502... What was the error in the icon's tooltip?

**Comment by narcolepticinsomniac** [comment]
Tried to grab a screenshot, but it's one of those fluky Chromium things where the tooltip disappears. The error message was "unknown", or something along those lines.

> Hmm, maybe on 502 we should simply retry one time in a few minutes...

Seems reasonable. Not sure you'd need to wait that long. Maybe recheck fairly frequently over the next few minutes.

**Comment by eight04** [comment]
IIRC someone had suggested using incremental delay for retries. It should be a good way to handle most errors including connection issues? Capped at 30 mins?

**Comment by tophf** [comment]
I've added a tentative fix 01e2e09f to ignore HTTP502 error when syncing. As for retrying that's probably a separate thing because it's not exactly trivial.

**Pull request merged**
