### PR TITLE
save-as-template button in editor

### LINKED ISSUE #896: Make editing usercss template more intuitive
For any new css I make I want the default template to have @preprocessor set already.

### PR DESCRIPTION
**Pull request by tophf**
Fixes #896.

Agonized for a while as to where to put the button. Went with `Editor settings` because this feature is rarely used and is kinda about customizing the editor.

Screenshots:

<details><summary>Normal mode</summary>

image

</details>

<details><summary>Compact mode</summary>

image

</details>

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
I see why you're torn. The setting makes sense there, but a button looks out of place. 

If it's gonna be a button, I'd probably suggest sticking it at the top with the others, regardless. I'd also switch the message to 'Save meta', or something short with the word 'meta', so its purpose is more obvious, and maybe a more descriptive tooltip.

Could this not be converted into a `Save current meta as template` checkbox in editor settings? You check it, it saves the current template, uses that as the default, and always shows as enabled. If you disable, it reverts to the default default.

**Comment by tophf** [comment]
Yeah, thought about grouping it with the main buttons, and the checkbox too but if it's not immediately next to the Save button then it's quite hard to discover and easy to forget e.g. you check it, get distracted by something, then click Save and ugh!

We should probably use *split* buttons:



And use it for our right-clicked buttons, there's like 2 IIRC.

**Comment by narcolepticinsomniac** [comment]
Split buttons seem like a reasonable alternative.

**Comment by tophf** [comment]
chrome_2022-01-19_02-22-12

**Comment by tophf** [comment]
Seems fine so I'm merging now and reusing it for other buttons. We'll fix problems later if any.

**Comment by narcolepticinsomniac** [comment]
Just got around to testing this. For the most part, I think they're a solid choice. 

A couple suggestions, and a bug:

* Any click outside the menu should close it, including re-clicking the button.

* We should reuse select SVG arrows instead of using unicode arrows - they'll look better. 

* Right-click actions appear to be bugged on the actual buttons now, duplicating functions in most scenarios.

**Comment by narcolepticinsomniac** [comment]
Also, if I'm correct in assuming that the 'save as template' option only applies to meta, it should probably say exactly that - 'Save meta as template' - to avoid confusion. Maybe some simple method of reverting to the default meta as well.

**Comment by tophf** [comment]
> Any click outside the menu should close it

Yes, it does.

> including re-clicking the button.

Not sure. I don't have a preference personally so the current behavior simply matches the existing implementations in the top online demos I found by googling "split button demo".

> select SVG arrows

Yeah, but after trying it just now I didn't like the amount of added code so I imitated it using CSS borders.

> Right-click actions appear to be bugged on the actual buttons now, duplicating functions in most scenarios

Not sure. The old quirk is preserved because I don't want to break the feature which was present for a relatively long time. The advantage is that it's much faster to perform on a large button compared to aiming at a small pedal, clicking, then moving the mouse into the menu and clicking again. The reason I wanted the pedal was to notify an alternative exists, not to replace the quirk.

Maybe we should add the quirk to the Save button instead? :-)

> 'save as template' option only applies to meta

It actually preserved the entire code except for the last section, which was removed blindly.
Fixed now by removing only the dummy section(s) that consist of a sole comment from our default template.

A template may include multiple sections, e.g. with author's common styles or comments, so in a new style the author will reuse the applicable sections and the remove the unnecessary ones.

> reverting to the default meta

Yeah. Although it's possible to save an empty template but that's not obvious, so I've added a `Reset` button with a tooltip in the confirmation dialog shown when clicking `Save as template`.

The tooltip:
```
Restore the default template.
(The currently open editor pages won't change.)
```

Pushed into master for convenience of testing as there is another PR waiting...

**Comment by narcolepticinsomniac** [comment]
> imitated it using CSS borders.

Well, they're less goofy shaped now, at least. I'd still rather reuse existing SVG icons, which are more likely to already be accounted for in userstyles.

> Right-click actions appear to be bugged on the actual buttons now, duplicating functions in most scenarios

I think I wasn't clear enough here. I'm not saying we should lose right-click because it duplicates the split button function, I'm saying the right click function is bugged, and executes twice. Save right-click opens two save dialogs, one regular, one compatible. Manager right-click opens two "site only" manager tabs, if no manager tabs are already open - otherwise, the dupe check seems to prevent it.

> I don't have a preference personally so the current behavior simply matches the existing implementations in the top online demos

Then those demos are also annoying. Re-clicking buttons should close menus, not make them blink in and out as they reinitialize.

**Comment by tophf** [comment]
Aye! Fixed the activation bugs.

**Comment by narcolepticinsomniac** [comment]
> I didn't like the amount of added code

**Pull request merged**
