### PR TITLE
[simple-window editor] embed popup as iframe

### PR DESCRIPTION
**Pull request by tophf**
There's a problem with our otherwise cool `simple window` option: browsers can't show the browser_action popup neither via a click nor a hotkey.

This PR adds such a button in the top-right corner and a hotkey: <kbd>Shift</kbd><kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>S</kbd>.

The button looks bad in usercss non-compact mode though so maybe you could find/suggest an acceptable solution @narcolepticinsomniac ? For today, I'm off to sleep.

### CODE REVIEW

**Comment by dnknn** [comment]
Great/Perfect/Creative solution for simple-window to show Stylus-Popup!  and I personally make 4 suggestions:

- Can reserve space for `#popup-button` to solve "_The button looks bad in usercss non-compact mode_" problem?  For example:
```css
html.usercss :not(.compact-layout) .single-editor	{margin-right:36px}
```

- I think the tooltip is enough to only display the prompt-info of the hotkey, which will be more concise, because people will know the meaning after using it once.

```html
<img id="popup-button" title="Shift-Ctrl-Alt-S" ...>
```
　　Instead of `title="Popup \n Shift-Ctrl-Alt-S"`

- ~~Should it be default transparency?~~(unimportant)  i.e. like  `#popup-button:not(:hover)	{opacity:.6}`

- Is it possible to allow users to customize this default hotkey (Shift-Ctrl-Alt-S)  ?
The purpose is to maintain the same browser built-in Popup-hotkey  as `chrome://extensions/shortcuts#:~:text=Stylus,Activate the extension` (e.g. `Alt+Z`)

If the custom hotkey can be higher than the built-in browser, so can set `Alt+Z` 
if no ...  at least the user can customize a relatively close hotkey, e.g. `Ctrl+Shift+Alt+Z`

**Comment by tophf** [comment]
No to everything.

**Comment by narcolepticinsomniac** [comment]
>The button looks bad in usercss non-compact mode

No great solution AFAICT. The selectors are there to swap sides in that particular layout, so we could stick it in the upper left or right side of the header. Maybe it's worth considering relegating it to the context menu.

**Comment by tophf** [comment]
Huh, maybe I'll make it movable horizontally? Don't want to use the context menu as it's very far from the original UI moreover the button already looks great in compact mode and acceptable in sectioned full mode.

**Comment by narcolepticinsomniac** [comment]
>Huh, maybe I'll make it movable horizontally?

Kinda sounds like overkill, plus we'd want it to not be positioned poorly by default in any layout. As long as it's always positioned decently by default though, knock yourself out.

Maybe we're asking the wrong question. I haven't use this mode much, so it's not something I've put a lot of thought into, but I'm finding it hard to imagine a scenario where I wouldn't want simple window mode compact.

**Comment by tophf** [comment]
Indeed, it's the right question. I've tried making it movable but the amount of code rivals the embedding code which seems an overkill. A simple `right: 24px` looks fine either with or without a scrollbar so this is it I guess.

**Comment by narcolepticinsomniac** [comment]
Oh, I thought you wanted to avoid the icon overlapping the editor altogether. Doubt it does much harm there though, particularly in a layout I doubt is used much in that mode. Good enough, if you ask me.

**Comment by narcolepticinsomniac** [comment]
Minor oversight. Should be: `.usercss body:not(.compact-layout) #popup-button`.

**Comment by tophf** [comment]
My bad, even dnk got it right...

**Comment by narcolepticinsomniac** [comment]
AFAIK, there's no way to set 'always on top' automatically, but it'd be really useful for window edit mode, IMO. We could at least add a constant unique string to the window title, so it can be keyed on by AHK, or other similar programs.

Switch:

https://github.com/openstyles/stylus/blob/a91183e1bb4154e418e561d2059cace6f4008218/edit/edit.js#L302-L304

to:

```
  function updateTitle(isDirty = dirty.isDirty()) {
    document.title = `${isDirty ? '* ' : ''}Stylus - ${style.customName || style.name}`;
  }
```

**Comment by tophf** [comment]
IIRC we added something like that in the title but it was a prefix and we removed it. A suffix though would work nice.

**Comment by narcolepticinsomniac** [comment]
Sure. Doesn't really matter where it is, just need a constant string to watch for.

**Comment by tophf** [comment]
Done: 355f2407.

**Comment by dnknn** [comment]
This suffix ` - Stylus`   constant, can it be an ON/OFF option ?

For people of not need to set 'always on top' automatically,  maybe they don’t want extra strings in the window title, because no ` - Stylus`  it can makes the window title more concise and intuitive.

I just suggest it, it's up to you to decide..

**Comment by narcolepticinsomniac** [comment]
No. We can't add prefs for every trivial, insignificant thing. Well, technically we can, but from a UI perspective, it'd be silly. 

If I were you, I'd encourage tophf to implement that prefs JSON he was talking about. If the UI was not a concern, and you catch him in a good mood, he might be inclined to add all kinds of stupid prefs.

**Comment by tophf** [comment]
> I just suggest it, it's up to you to decide..

lol thanks, didn't know that.

**Comment by dnknn** [comment]
Thank you, how to use prefs JSON ?
I agree and understand your point of view, and that's certainly correct.
I personally think that there can be a Misc option, which is specially processed trivial, insignificant thing.... Misc option (default collapsed state) generally does not affect the UI.
Like this `add a suffix in editor title` change ,  After all, it has been very simple before, and now there is a fixed suffix suddenly, if no need external utilities to process windows, will feel that this forced change is not good.

**Comment by tophf** [comment]
There'll be no such option. The JSON is about CodeMirror internal preferences. Also, this is a trivial change, which actually restores the old behavior, so no need to get obsessive-compulsive about it. Unless you want to annoy us in retaliation (this ain't gonna work though).

**Comment by tophf** [comment]
OTOH I can limit it to the simple mode... @narcolepticinsomniac WDYT?

**Comment by narcolepticinsomniac** [comment]
Nah, it should be available in either. We should make the string longer, and see if dnknn has an aneurysm. He picks the weirdest stuff to fixate on.

**Comment by dnknn** [comment]
@tophf  
- Stylus-Popup on the browser toolbar-icon is perfect, no any problem.  

- Only [simple-window editor] iframe-Popup,  when clicking the ⚙button to  show `#message-box.config-dialog.stylus-popup` , will have 2 problems: 

- Horizontal and vertical scrollbar always appear, of course, this is not a big problem.
<details>
<summary>Details</summary>

image

</details>


- Sometimes the `#message-box.config-dialog` content will be incomplete, this Bug can be reproduced in the following 2 steps :
1) First click the ⚙button of `Test-short`, then close.

```css
/* ==UserStyle==
@name		    Test-short
@namespace		1
@version	0.0.5
@preprocessor	stylus
@var text		test1	"11"	haha
@var text		test2	"11"	haha
@var color		test3	"color"	#00f
@var checkbox	test12	"ONoff"	0
@var number		Min_vh		"test"	[99,95,99,1,'vh']
==/UserStyle== */
@-moz-document url-prefix("chrome-extension://clngdbkpkpeebahjckkjfobafhncgmne/edit.html") {
    #abcdefg {z-index:1}}
```
---
2) click the ⚙button of `Test-long`, at this time, the content cannot be displayed normally, in other words, it cannot automatically open the height.

```css
/* ==UserStyle==
@name		    Test-long
@namespace		1
@version	0.0.5
@preprocessor	stylus
@var text		test1	"11"	haha
@var text		test2	"11"	haha
@var color		test3	"color"	#00f
@var color		test4	"color"	#00f
@var color		test5	"color"	#00f
@var color		test6	"color"	#00f
@var color		test9	"color"	#00f
@var color		test11	"color"	#00f
@var checkbox	test12	"ONoff"	0
@var number		Min_vh		"test"	[99,95,99,1,'vh']
==/UserStyle== */
@-moz-document url-prefix("chrome-extension://clngdbkpkpeebahjckkjfobafhncgmne/edit.html") {
    #abcdefg {z-index:1} }
```

---
<details>
<summary>Gif demo bug</summary>

image

Bug2

</details>

**Comment by tophf** [comment]
Yep, I forgot to hook resizing when config icon is used.

**Comment by tophf** [comment]
Fixed in `master` via a87c49f0.

**Pull request merged**
