### PR TITLE
improve bookmarking

### LINKED ISSUE #952: Improve CM bookmarking
Click line numbers to bookmark/unbookmark, some kinda convenient click function to cycle, and it'd be way more useful if it actually cycled through all sections.

### PR DESCRIPTION
**Pull request by tophf**
Fixes #952.

Line number area accepts mouse clicks now:

* <kbd>Left button</kbd> toggles bookmark
* <kbd>Right button</kbd> goes to the next bookmark (or previous if <kbd>Ctrl</kbd> is held)
* <kbd>Middle button</kbd> selects all bookmarked positions, useful when multi-editing

Changed the default style so it's more noticeable especially in the dark themes:

image image

As for cycling through all sections, that's not reliably possible with the way sublime bookmarks work as their next/previous order isn't based on a line number but rather on the bookmarking order so it may jump all around the place within one section. This implementation seems weird but I'm not sure we can convince CodeMirror's author so maybe I could just re-implement bookmarking myself one day. That would make it available for all keymaps not just `sublime`.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
LGTM. Might be cool if scrolling line jumps always centered, like swatch cycling. It'd be kind of a shame if this goes unnoticed, but I'm not sure there's a great visual indicator which won't be distracting though.

Mostly unrelated, I'd like to get rid of all the orange eventually. I get why we're using it in search and bookmarks, because it's a solid highlight color that works well, but damn it's fugly. Cyan stands out pretty well against most backgrounds too, so some shade of it must work decently.

**Comment by tophf** [comment]
Switched to cyan. I'm fine with orange but cyan matches our palette especially in the sectioned editor which has a focus outline of the same color.

**Comment by tophf** [comment]
> scrolling line jumps always centered

Done.

**Comment by narcolepticinsomniac** [comment]
Everything LGTM. You think we should at least give em hover backgrounds to indicate action? NBD either way. Up to you.

**Comment by tophf** [comment]
The cursor is changing, I thought that's enough.

**Comment by narcolepticinsomniac** [comment]
Cursor changes after you click it. I'm just concerned that no one will realize their clickable in the first place, particularly since they never have been previously.

**Comment by tophf** [comment]
Ah. Maybe you can find a satisfactory solution then. If not, I'll try something tomorrow.

**Comment by tophf** [comment]
Turns out the feature works with all keymaps as long as we simply load sublime.js which we will always do. So now `cursor:pointer` is always present on line numbers. The only missing indication would be the right-click but maybe the users will find it eventually. Someone could add it to wiki as well.

**Comment by dnknn** [comment]
> Someone could add it to wiki as well.

https://github.com/openstyles/stylus/wiki/Hotkey-shortcuts#editor-shortcuts
May need to be modified

**Comment by tophf** [comment]
We can find a way to indicate the feature later.

**Comment by dnknn** [comment]
> > scrolling line jumps always centered
> 
> Done.

@tophf Now, `right-click` on the bookmark-line-number can do this, but can let `F2/Ctrl+F2` do the same this (jumps always centered) ?

**Comment by tophf** [comment]
Yeah that's good for consistency. Done in c635f2e3.

**Comment by dnknn** [comment]
@tophf  I found 2 bugs in actual use that is difficult to describe clearly:   R-click the line number = `F2`

Bug1:   press `F2`, the cursor can jump, but can't jump/scroll  into  the view/viewport .
Bug2: e.g. set 2 bookmarks, but sometimes need to press `F2` twice to jump to the viewport.


- Note: Test the Bookmark jumping bugs from the **second** section (the first section seems no problem)

the Bookmark jumping should still be defects, I tested it for a long time, and i have conducted detailed tests and troubleshooting on Chrome86 and Chrome84 respectively, and I couldn’t find the reason for the trigger condition, below is a simple code and gif demo:

- [Bug-demo.txt](https://github.com/openstyles/stylus/files/5597602/Bug-demo.txt)


Bug

**Comment by tophf** [comment]
Apparently it's because your section is taller than window. I'll look into that.

**Comment by dnknn** [comment]
> Apparently it's because your section is taller than window. I'll look into that.

I also thought about it, and I tested it also, like: `.section>.CodeMirror	{max-height:99vh}`

**Comment by dnknn** [comment]
Specific test data, maybe it will help you :
- The most important point is that the first `.section` (tested) has no problems at all, so from this point, it seems that this problem has nothing to do with the height of the window and the height of the editor.

- I only encountered this problem in the **second** `.section` (I didn't test more other sections)
1) A total of 265 lines,  and set the first bookmark on line `50`
2) Set the second bookmark from line `80-108`, **can’t jumping**. 
3) Set the second bookmark from line `108-*` , will back to normal.

**Comment by tophf** [comment]
Should be fixed in a91183e1.

**Pull request merged**
