### PR TITLE
show write-style entries for iframes in popup

### LINKED ISSUE #191: IFRAME support in popup for write-new-style, style list, badge
%subj%

### PR DESCRIPTION
**Pull request by tophf**
Closes #191.

If the site has iframes a `[+]` toggle is shown to the left of the #write-style block.

* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
  image
  image

* https://css-tricks.com/responsive-iframes/
  image

* https://www.tutorialrepublic.com/html-tutorial/html-iframes.php
  image

Styles for iframes are shown in the list and counted in the badge text.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
The UI LGTM. I don't see a partial implementation working all that well though. To me, it seems like one of those things where we either support iframe detection, or we don't.

**Comment by tophf** [comment]
Okay, I'll add the other parts.

**Comment by tophf** [comment]
Now the popup shows the additional unique styles for frames.

image image

* hovering `iframe` element shows the URL in a tooltip
* no option to toggle this feature - do we need it? I'd say no because it's relatively easy to customize via CSS, and those who might dislike this innovation are likely to know CSS sufficiently well.
* the `iframe:` prefix is not translatable, but it probably should be - _if_ we keep it.

As for the badge number I'll wait for #856 because it moves the icon manager js. The label might be `2+1` or just the overall number of unique styles - not sure which one would make more sense so maybe I'll add an option to toggle it.

**Comment by narcolepticinsomniac** [comment]
>not sure which one would make more sense so maybe I'll add an option to toggle it.

If you think it's worth the trouble, go right ahead. I'd say counting iframes in the normal overall count is fine though.

**Comment by tophf** [comment]
My idea is to keep a dimmed icon for tabs that don't have their main document styled. They could have a few styled iframes but those aren't necessarily contribute to the page appearance as they can be even hidden or just too inconspicuous. So in order for the icon's behavior to appear non-bugged I think the separate numbers are the only solution.

**Comment by narcolepticinsomniac** [comment]
Not something I feel strongly enough about to put up much of an argument, so if you do, go ahead and do whatever you have in mind. Only thing I'll say is that I don't think dimming the icon when the main document isn't styled, while still showing iframes in the count, would be all that confusing or buggy.

**Comment by tophf** [comment]
I thought so too just a few minutes ago so yeah gonna decide later.

**Comment by tophf** [comment]
`1+2` covers the entire bottom half of the icon so that idea is dead.

**Comment by tophf** [comment]
Updated.

**Comment by eight04** [comment]
👍 

Do we need to list the entire iframe tree? or just a list of unique frames?

**Comment by tophf** [comment]
Only childless duplicates are hidden now, hiding all duplicates would be confusing because of broken parent-child relations that help identify the iframes in devtools. As for the large tree on tutorialrepublic their iframes have different full URLs so only their domain parts are identical, but anyway it's negligibly rare to have that many iframes so my gut feeling is that the current approach is fine. Well, at least until proven otherwise.

**Comment by narcolepticinsomniac** [comment]
In testing, I'm running into a lot of heisenbugs in the total count. I'll have a couple active globals, and one site specific, no iframes in the page, and the total will be 5 or 6. Load everything from scratch, go back to the same page, and the total's correct. I know that's not helpful, because I can't repro consistently, but it's happening pretty consistently on random, different pages.

One bug I can repro consistently. Seems like opening edit pages of disabled styles from the popup fails to update the icon and count correctly on the opened edit page. This assumes you have active globals or UI styles for edit pages.

**Comment by narcolepticinsomniac** [comment]
Ran into an error, which I also can't repro after relaunch:

split

**Comment by tophf** [comment]
Fixed something 🤪

**Comment by narcolepticinsomniac** [comment]
>opening edit pages of disabled styles

Fixed.

>heisenbugs in the total count

So far, so good.

>Ran into an error, which I also can't repro after relaunch

Same site, similar bug, different error. Also couldn't repro after reload.

foreach

**Comment by narcolepticinsomniac** [comment]
Mostly looking pretty good now. I'll keep testing. 

I'm clicking on random, old bookmarks, and ran into an issue which seems [site-specific](https://comicbook.com/dc/2018/05/21/kevin-smith-ben-affleck-havent-spoken-in-years/). Disabling styles in the popup doesn't update the count. I'm curious if you can repro.

**Comment by narcolepticinsomniac** [comment]
>Disabling styles in the popup doesn't update the count

See the same on [this site](https://streamable.com/videos). Not sure if it depends on styles.

**Comment by narcolepticinsomniac** [comment]
[rmz-test.zip](https://github.com/openstyles/stylus/files/4244784/rmz-test.zip)

Test DB for [this site](http://rmz.cr/). Not sure why active iframe styles aren't factored into the count.

**Comment by tophf** [comment]
I can repro. Looks like an irrelevant wrong style gets matched by apply.js but not by the popup. We didn't see the bug previously because iframes weren't processed.

**Comment by tophf** [comment]
Er, no, the iframe was present and its styles got remembered, then the iframe got removed by the site, but the count wasn't removed. Gee I wonder if I can detect this efficiently...

**Comment by tophf** [comment]
Should be fixed now.

**Comment by narcolepticinsomniac** [comment]
>Disabling styles in the popup doesn't update the count.

Yep, fixed. Nice.

AFAICT, [this one](https://github.com/openstyles/stylus/pull/861#issuecomment-590323608) is still unresolved though.

**Comment by narcolepticinsomniac** [comment]
rmz

**Comment by tophf** [comment]
I can't repro with my styles. I wonder if another extension like an ad blocker could interefe...

**Comment by narcolepticinsomniac** [comment]
>I wonder if another extension like an ad blocker could interefe...

Yep, uBO with [ultimate list](https://www.fanboy.co.nz/r/fanboy-ultimate.txt). That's just a combo of popular filter lists like easylist, annoyances and social. It's not some advanced filters injecting js or anything.

**Comment by tophf** [comment]
Can repro now, investigating...

**Comment by tophf** [comment]
Should be fixed now.

**Comment by narcolepticinsomniac** [comment]
Yep, everything's looking good. I'll keep testing regularly for a bit.

**Comment by narcolepticinsomniac** [comment]
LGTM. This is pretty dope. Thanks tophf!

**Comment by tophf** [comment]
So I guess we're not adding an option to disable this iframe features? Gonna wait for user feedback then.

**Comment by narcolepticinsomniac** [comment]
>So I guess we're not adding an option to disable this iframe features?

>...do we need it? I'd say no because it's relatively easy to customize via CSS, and those who might dislike this innovation are likely to know CSS sufficiently well.

I agreed with your original assessment.

**Comment by tophf** [comment]
I meant an option to toggle inclusion of iframes in the badge number.

**Comment by narcolepticinsomniac** [comment]
Well then, I agree with my misinterpretation of your original assessment. =)

**Comment by narcolepticinsomniac** [comment]
Truth is, other than just hating change, there's no downside IMO. If there's a substantial amount of negative feedback, I suppose we could consider it. I'd be surprised if that happens, tbh.

**Pull request merged**
