### PR TITLE
Add: store the reason why db failed

### LINKED ISSUE #546: All styles missing in manager page though present in Indexed DB (normal browsing, not private)
* **Browser**: Firefox 63.0 (64-bit)
* **Operating System**: Kubuntu 18.04
* **Screenshot**: 
image
All my installed styles suddenly "disappeared" from the manage page.  **This is not the Private Window mode** and I have not changed any privacy settings since years.
The Indexed DB  section in the Dev Tools show some parameters as null, but that is exactly how they are in my working Chromium because they are totally local: md5Url, originalMd5, updateUrl and url are null, and all the others, as far as I can tell, are normal. In fact, in the Indexed DB section I can see that all the other parameters are also the same as in Chrome (originally written in Firefox, then exported to Chromium).

Although I have seen the closed bugs #528 and #530, those referred to Chrome 72.0.3592.0, and in my case I have had no issues with Stylus yet in my Chromium because it's at version 70.0.3538.77.  I am opening this bug here because neither of those closed bugs will help Firefox users because their titles and contents point to Chrome. It is important that there is a bug with a title clearly saying "styles missing" without referring to any browser in particular.

I do have a backup, but before "fixing" it with restoring a backup, I think it is more important to get more information and support for users and clear statements of what actions are necessary to get things working. Not all users of this extension are JavaScript developers. So please don't dismiss this bug with "somebody else's problem" or with an ultra "kind"  _[that's even dumber](https://github.com/openstyles/stylus/issues/530#issuecomment-433527126)_ remark... if that is not asking too much.   Thanks!

**Edit**: I forgot to mention, about what is suggested in [a comment in #528:](https://github.com/openstyles/stylus/issues/528#issuecomment-433441967)
image
So, the name of the `BG.dbExec` function is `dbExecChromeStorage`  and `BG.cachedStyles.list` is an empty array.

### PR DESCRIPTION
**Pull request by eight04**
Fixes #546 

It saves the validation error so we can inspect it with
```js
chromeLocal.getValue('dbInChromeStorageReason')
```
However, I don't know how to test this branch. Is there a way to make indexed DB fail manually?

### CODE REVIEW

**Comment by Mottie** [comment]
Should we also open a modal showing the error?

**Comment by eight04** [comment]
In the manager? I think it won't work if the user doesn't open the manager page.

**Comment by Mottie** [comment]
What about an alert then?

**Comment by eight04** [comment]
You can't use alert in the background page in Firefox.

**Comment by Mottie** [comment]
I'm not sure how to test this PR. What if we also store the URL (or just the domain; to ensure privacy) causing the error so we know the source? I thought I saw an error pop up when the Firefox add-ons manager page was open, but now I can't reproduce it.

**Comment by eight04** [comment]
The validation only happens when the DB is initializing i.e. when the extension startups, so there is no URL that could be recorded. I also don't think the error would relate to a specific page because `db.js` is used in the background page.

> I'm not sure how to test this PR.

Then we just merge it?

**Pull request merged**
