### PR TITLE
Account for Dropbox bug

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
We can't really push an update containing the new sync feature with one of the hosts being broken in the last few versions of Chromium, unless we at least address the issue. It's not ideal, but the new sync feature is cool and we don't wanna sit on it forever, so I guess we could just disable the option with a generic message we can re-use in the future, about the host being disabled due to a browser bug.

The old Dropbox sync is obviously bugged too, so we should work that out here as well. I would've been all for deprecating it and attempting to transition gracefully, but since it's gonna be broken for the vast majority of users, perhaps we should just gut it now. I doubt a ton of people use it, and there's not a lot of great options for those who do. I'm open to suggestions, but mine would be to get rid of it entirely, and maybe replace the menu item with a "sync" option, which simply opens up options.

@eight04 WDYT?

### CODE REVIEW

**Comment by eight04** [comment]
I think it should be safe to remove Dropbox export. Unlike GDrive which hides application folders, users can still download the backup ZIP from Dropbox.

**Comment by narcolepticinsomniac** [comment]
We'll gut it now then. You're more familiar with what needs to go and what needs to stay. You wanna get rid of it here, or you want me to wing it first, and then tell me what I did wrong after? =)

**Comment by eight04** [comment]
> replace the menu item with a "sync" option, which simply opens up options.

Which menu item?

**Comment by narcolepticinsomniac** [comment]
I figured we might replace the old "Dropbox import" and "Dropbox export" menu items in the backup section of the manager, so when people go looking for them, it directs them to the new sync feature instead of just being gone altogether. 

Either that, or we just revert them to local import/export buttons. I'd like to do that eventually anyway, but I thought it might be nice to redirect anyone looking for the old "sync" to the new one for a while.

**Comment by eight04** [comment]
Instead of replacing "Dropbox import/export", it might be better to disable the menu item and put a "Dropbox import/export is broken and is deprecated" message in the title.

**Comment by narcolepticinsomniac** [comment]
Sure, whatever works. There should be some mention of the new sync feature in options though.

**Comment by narcolepticinsomniac** [comment]
Is that it? I was expecting some deletions. Is everything still used by the new sync feature?

**Comment by eight04** [comment]
Still WIP. Some vendor files will be removed. BTW, I'll push package-lock.json to this branch.

**Comment by narcolepticinsomniac** [comment]
Okay then.

**Comment by eight04** [comment]
The entire dropbox backup feature is removed.

**Comment by narcolepticinsomniac** [comment]
Thanks 8. I'll merge it soon, and I think we'll be in pretty good shape to push the next update. Hopefully sometime in the next few days. Anything else you wanna get into the next one?

**Comment by FranklinYu** [comment]
Look forward to next release in Beta channel!

**Comment by narcolepticinsomniac** [comment]
@FranklinYu If you're talking about CWS beta, for some reason, the same exact update which was approved for stable, is stuck in "pending review" for beta.

Might as well switch to stable anyway. We haven't really utilized beta in the traditional sense in a long time. They've been getting the same updates at the same time for years now.

**Comment by FranklinYu** [comment]
Thanks for the note. Is there any plan to make use of it in future? If not then I would be switching all my devices to Stylus Stable.

By the way the new sync works nice. Thanks!

**Comment by narcolepticinsomniac** [comment]
>Is there any plan to make use of it in future? 

Doubtful. It's nice to have the option, but I don't trust that the feedback would be sufficient in most cases. If we push a bad update, everyone can suffer. =)

>By the way the new sync works nice. Thanks!

That was all 8. I'm enjoying it too.

**Comment by narcolepticinsomniac** [comment]
@eight04 @Mottie AMO has an issue with 1.5.7. Figured there's a good chance something in this PR is to blame. If not, it's as good a place as any to let you guys know.

"The build script doesn't work https://github.com/openstyles/stylus/tree/master/vendor. I tried npm i and npm run update, but I'm getting errors and the vendor folder isn't populated. Please take a look and let me know if I'm missing any details."

**Comment by eight04** [comment]
The reviewer shouldn't have to `npm run update`. This command is used to update dependencies (e.g. CodeMirror) to the latest version. By running the command, the reviewer may get a different version of the dependency.

I think we can update our build steps:

1. Remove `updates` from dev-dependencies. It's a bad idea to blindly upgrade everything to the latest version (especially we use a lot of low-level APIs). To upgrade everything to the compatible version, run `npm update`. To upgrade a single package to the latest version, run `npm install package@latest`. If you really want to upgrade everything to the latest, use a 3rd-party tool. Don't forget to test after the upgrade.
2. `uuid` is not generated by the build script and is downloaded from https://bundle.run. It is not in our dependency. When it comes to v4.0.0, we will get a UMD bundle. Before that, we can write a script fetching it from https://bundle.run, or create a bundle version like less/stylus-lang.
3. Because of (2), `Vendor files are populated by the build script` is technically incorrect.
4. There is no need to remove the entire `node_modules` folder. Running `npm install` ensures that `node_modules` matches `package.json` and `package-lock.json` (unless you modify files inside `node_modules` manually).
5. We can use `npm version` command to bump the version number. This allows us to test/build before tagging a release and it updates the version number in `package-lock.json`.
6. Rename `vendor/README.md` to `BUILD.md`. The current filename may confuse the reviewer that commands should be run inside the vendor folder.
7. Setup a CI.

**Comment by narcolepticinsomniac** [comment]
>It's a bad idea to blindly upgrade everything to the latest version

Yeah, we should only update dependencies when there's significant improvements. I cringe every time I see it happen, then immediately forget all about it.

All your suggestions SGTM, and I'm not gonna pretend to have anything useful to add to the conversation. Anything you wanna switch up to make the review process go more smoothly, hook it up and I guess we'll resubmit.

**Comment by Mottie** [comment]
1. Yeah, I know we should test a bit more before updating our dependencies. I did briefly test to make sure CodeMirror was still working. Most of the other packages are from our own repositories that bundle packages, so it seemed safe. I forgot about the newer sync packages that were added.
2. I'm not sure what you're discussing here. I've never heard of bundle.run, nor do I understand how it will solve our issue, but it does look interesting.
3. It hasn't changed yet, has it?
4. In my past experience, `npm install` did not replace some dependencies, thus the reason I removed the entire `node_modules` folder before installing. Maybe this has been fixed in the latest node?
5 & 7. Sounds like we need to start adding unit tests?
6. Good idea.

**Comment by eight04** [comment]
> 2\. I'm not sure what you're discussing here. I've never heard of [bundle.run](http://bundle.run), nor do I understand how it will solve our issue, but it does look interesting.

[This file](https://github.com/openstyles/stylus/blob/master/vendor/uuid/uuid.min.js) is not generated by the build script.

**Comment by narcolepticinsomniac** [comment]
Regarding AMO's issues with 1.5.7, they did specify we had a week to rectify the situation, which is up in a couple days. Obligatory threat saying "your extension may be removed". AMO can kiss my ass, for all I care, but I'm relaying the message.

If we work it out, I plan to respectfully request to be removed from recommended extensions program and put back on auto reviews. I knew signing up for manual reviews was asking for trouble, and we should've declined to begin with.

**Comment by eight04** [comment]
Does the reviewer want to take down 1.5.7 or all versions? Since we have a DB bug in 1.5.7, I think we should take it down anyway since chrome DB is used by many FF users.

**Comment by narcolepticinsomniac** [comment]
1.5.7 was never approved/released. I think it's just a blanket, empty threat that they'll pull the extension entirely. If we work out the issues the reviewer was having, I guess the plan would be to resubmit with all the fixes.

**Comment by Mottie** [comment]
I think the uuid file is small enough, we may not have to minify it. Has the DB bug been fixed? If so, I am available to resubmit.

**Comment by eight04** [comment]
> we may not have to minify it

Do you mean to create a `uuid-bundle` repo?

**Comment by Mottie** [comment]
Naw, just include it as a un-minified file. AMO only complains if the code is unreadable.

**Comment by Mottie** [comment]
Hmm, I guess uuid doesn't provide a bundle. Maybe we will have to create a `uuid-bundle` repo :(

**Comment by Mottie** [comment]
Oh, maybe we could just include the link (for AMO to see) to cdnjs: https://cdnjs.cloudflare.com/ajax/libs/node-uuid/1.4.8/uuid.min.js

**Comment by eight04** [comment]
I think the content is different:
https://bundle.run/uuid@3.3.3/v4.js

Do they accept `https://bundle.run`? If so maybe we just have to fix the document.

**Comment by Mottie** [comment]
Hmm, weird. The code is different, but the link to https://github.com/kelektiv/node-uuid/tree/v3.3.3 redirects to https://github.com/uuidjs/uuid/tree/v3.3.3

**Comment by Mottie** [comment]
I'm not sure if they'd accept bundle.run... I think as long as the code matches, it'd be okay.

**Comment by eight04** [comment]
Do you want to update the script? or I can file a PR.

**Comment by Mottie** [comment]
Sorry, I have to start working in a few minutes.

**Comment by narcolepticinsomniac** [comment]
AMO:

"uuid.min.js is not present in node_modules after installation. We don't accept minified js files from cdnjs because cdnjs is not the official source code repository. Please provide instructions on how to reproduce the minification for this library. You add-on will be pending until you fix this issue."

**Comment by tophf** [comment]
>You add-on

Oh you add-on!

**Comment by narcolepticinsomniac** [comment]
IKR? I reject their rejection and request changes.

**Comment by eight04** [comment]
I guess we still have to build a `uuid-bundle`. I think we can publish it to npm. Do we have an organization on npm? If not, I'd like to create `@openstyles` and name the package as `@openstyles/uuid-bundle`.

**Comment by Mottie** [comment]
https://www.npmjs.com/~openstyles

**Comment by eight04** [comment]
https://docs.npmjs.com/converting-your-user-account-to-an-org

**Comment by tophf** [comment]
That library is ~1 page of code and ~1 page of module import overhead so maybe it's better to rewrite it and include in Stylus.

**Comment by eight04** [comment]
A pro of bundle packages is that it can easily receive upstream updates. Or, do we want to put the bundle script in this repo?

**Comment by tophf** [comment]
It's an implementation of RFC-compliant algo so what do you think can change in the next 100 years?

**Comment by eight04** [comment]
Bugfix, new feature, performance improvement, etc? BTW, I found that we already have a UMD build in the 7.0 beta:
https://unpkg.com/browse/uuid@7.0.0-beta.0/dist/umd/uuidv4.min.js

**Comment by tophf** [comment]
That's a trivial algo so there's no reason to expect any changes in the next 100 years.

**Comment by tophf** [comment]
I've just looked at the code again and I find it quite funny that we're using an external package (half of which is the module import overhead) for such a trivial thing.

**Pull request merged**
