### PR TITLE
Advanced options toggle

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
Whole div is clickable. Arrows to indicate functions. I went with carets and centered collapsed text, but we can use different arrow and/or keep the text to the left.

### CODE REVIEW

**Comment by tophf** [comment]
Hehe, that's more obvious indeed, even though label jumping is unusual. LGTM. You can select `Squash and merge` in the merge button so that all WIP commits are combined in one.

**Comment by narcolepticinsomniac** [comment]
Any FF conflicts here? Should I add `html:not(.firefox)` to selectors and hide the icons for FF?

**Comment by tophf** [comment]
Ah, yes, neither `.firefox` nor `.opera` need it.

**Comment by narcolepticinsomniac** [comment]
Alright, I'll fix it in a bit. I can use `:not(.firefox):not(.opera)` but we might consider adding a `.chromium` class to our pages as well.

**Comment by tophf** [comment]
Uhm, I think it might be easier (or rather less intrusive) to remove `collapsible` from options.html, and add it in options.js so the new line 9 would be:

```js
block.classList.add('collapsible', 'collapsed');
```

And then you can style based on the presence of `.collapsible` on the advanced block.

**Comment by narcolepticinsomniac** [comment]
Sure.

**Comment by tophf** [comment]
Okay, then please do it.

**Comment by tophf** [comment]
Uhm, the files got moved to the root folder...

**Comment by narcolepticinsomniac** [comment]
I know. =) Should be right now.

**Comment by tophf** [comment]
There's a problem in Opera fixed by the following:

```css
.collapsible-resizer h1 {
    width: 100%;
}

.collapsible-resizer {
    width: 30%;
}
```

Maybe you can find a better solution. Please test it in a portable Opera.

**Comment by tophf** [comment]
Actually the same problem is present in FF.

**Comment by narcolepticinsomniac** [comment]
I didn't look at the js really, but otherwise, why are we using it to exclude FF and Opera?

**Comment by tophf** [comment]
Well, the problem is caused by the lack of explicit width specification for `collapsible-resizer` in FF/Opera.

**Comment by tophf** [comment]
> why are we using it to exclude FF and Opera?

because their options page aren't shown in a tiny box.

**Comment by narcolepticinsomniac** [comment]
I get it. I thought you meant `.collapsible` wasn't excluding, but it's a lack of any properties on the new div.

**Comment by narcolepticinsomniac** [comment]
Fixed it Opera, broke it in Chrome. Fixed it again, should be good now.

**Comment by tophf** [comment]
Yep, LGTM, squash it.

**Pull request merged**
