### PR TITLE
build using webpack

### LINKED ISSUE #514: Move extension content to a subfolder?
* **Browser**: Chrome
* **Operating System**: Windows 7 x64
* **Screenshot**:
image

Currently, we put everything in the project root. When those files are loaded as an unpacked extension, Chrome would walk through the entire file tree.

I suggest moving extension files (i.e. `background/`. `content/`, `blabla.html`, etc) to a subfolder (e.g. `extension`), so it should reduce the startup time and also simplify the build process. Note that we have to resolve all PRs first or there will be a bunch of conflicts.

### LINKED ISSUE #1366: Add build system
@tophf Since it is so important that we can't add new js/css files to the page without it. I'd like to know what do we expect from a build system PR.

1. Just find a tool that can concatenate CSS/JS on an HTML page automatically? Maybe we can try parcel and start from non-shared modules.
2. Convert the page into individual components (svelte?), still have to exclude shared modules until all pages have been converted.
3. Start building the project structure from scratch? Build the project in another branch and eventually use it as the main?
4. Other plans?

### PR DESCRIPTION
**Pull request by tophf**
* fixes #1366
* fixes #514

Seems to work, but I didn't test everything, so I plan to publish it only into beta for a while. Editor/manager now open slightly faster, as expected, due to bundling and minifying dozens of scripts.

Todo:
- [x] MV3 build
- [x] MV2 builds + zips for web stores
- [x] tests
- [ ] (eventually) actions to upload build artifacts
- [ ] (eventually) actions to publish in the web stores

@eight04, now the source code is using modern conventions (more or less), so it's easier to work with, especially in nontrivial ways. I'll be primarily working on MV3 (arguably using conditional compilation, I don't know yet), so maybe you could take a look at this PR as a whole and advise or participate. Since I don't have a lot of experience in tooling, there's probably a lot to improve. BTW I've tried rollup and although it produced nice ES modules, I still switched to webpack because it's much more flexible at about the same speed. Regarding all those WIP commits, I won't merge them, I'll rebase/regroup everything or just squash it in one commit later.

### CODE REVIEW

**Comment by tophf** [comment]
Here's the diff after moving to src which makes more sense for online browsing: https://github.com/openstyles/stylus/pull/1828/files/b4aa1c4d4a2b13ff778dcf16f7b1e57591787394..62af62d57fd54dc8f8f4128a1f17bb71f384bdd0

**Comment by eight04** [comment]
I have never used webpack either so I can only tell from my rollup experience:

1. It seems that library/content scripts are built separatedly. IDK how webpack handles multiple configs. Does it generate duplicated code when both of them import the same module?
2. [comlink](https://github.com/GoogleChromeLabs/comlink-loader) may make it easier to work with workers.
4. I noticed that there is a `src/package.json`. Is that how babel config works?
6. Put static files in a `static` folder to simplify the config for `CopyPlugin`.
7. Some pre-built IIFE libraries are also copied. I think it is possible to import them with a custom loader simply prepending `export ` to the source.
3. Now we can switch to a component system supporting templates. It will be way more readable than `createElement` and `addEventListener`.
5. My browser freezes when navigating to https://github.com/openstyles/stylus/pull/1828/files so I can only view the code from my editor.

----

Here are some examples using rollup:

* A single config to bundle multiple entries, using comlink. After rollup generates chunks for multiple entries, it writes their paths to `manifest.json`, `options.html`, etc. https://github.com/eight04/ansi-viewer/blob/master/rollup.config.js
* Two configs with different entry points. One for extension and one for userscript. https://github.com/eight04/linkify-plus-plus/blob/master/rollup.config.mjs

**Comment by tophf** [comment]
Great stuff, thanks.

> duplicated code

I had to split the worker scripts manually into separate compilation items in webpack (previously did the same in rollup) to reuse the code, but comlink should greatly simplify it, thanks.

The content script is intentionally a single bundle because only ~600 bytes for `msg-base` are duplicated, which isn't worth extracting.

> src/package.json

Dunno yet, I forgot to finish my investigation about it. I'll probably remove it, if the extra `re` plugin doesn't break node_modules and doesn't slow down compilation.

**Comment by tophf** [comment]
MV3 test build: [stylus-mv3-test-6b0f4475.zip](https://github.com/user-attachments/files/17604639/stylus-mv3-test-6b0f4475.zip). Back up your styles first, install it as an unpacked extension, import the data and keep the backup in a safe place in case the data gets rek, which shouldn't happen, but just in case.

**Comment by tophf** [comment]
[stylus-mv3-test-6c3ccc82.zip](https://github.com/user-attachments/files/17612347/stylus-mv3-test-6c3ccc82.zip)

**Comment by tophf** [comment]
[stylus-mv3-test-ec135d6a.zip](https://github.com/user-attachments/files/17618029/stylus-mv3-test-ec135d6a.zip)

**Comment by tophf** [comment]
[stylus-mv3-test-42278e61.zip](https://github.com/user-attachments/files/17638828/stylus-mv3-test-42278e61.zip)

BETA for the web store with `Stylus (beta)` name in manifest.json: 
[stylus-mv3-beta-42278e61.zip](https://github.com/user-attachments/files/17638833/stylus-mv3-beta-42278e61.zip)

**Comment by tophf** [comment]
[stylus-mv3-test-7c205b95.zip](https://github.com/user-attachments/files/17670123/stylus-mv3-test-7c205b95.zip)

**Comment by tophf** [comment]
[stylus-mv3-test-b32a8a99.zip](https://github.com/user-attachments/files/17683510/stylus-mv3-test-b32a8a99.zip)

**Comment by tophf** [comment]
[stylus-chrome-beta-3.0.1.zip](https://github.com/user-attachments/files/17738316/stylus-chrome-beta-3.0.1.zip)

**Comment by tophf** [comment]
[stylus-chrome-beta-3.0.1-c5552bf.zip](https://github.com/user-attachments/files/17923994/stylus-chrome-beta-3.0.1-c5552bf.zip)

**Comment by tophf** [comment]
[stylus-chrome-beta-3.0.1-afcfdef.zip](https://github.com/user-attachments/files/17926466/stylus-chrome-beta-3.0.1-afcfdef.zip)

**Comment by tophf** [comment]
[stylus-chrome-beta-3.0.2.zip](https://github.com/user-attachments/files/17932944/stylus-chrome-beta-3.0.2.zip)

**Comment by tophf** [comment]
[stylus-chrome-beta-3.0.2.zip](https://github.com/user-attachments/files/17939032/stylus-chrome-beta-3.0.2.zip)

**Comment by tophf** [comment]
[stylus-chrome-beta-3.0.3.zip](https://github.com/user-attachments/files/17949900/stylus-chrome-beta-3.0.3.zip)

**Comment by tophf** [comment]
[stylus-chrome-beta-3.0.3.zip](https://github.com/user-attachments/files/17960445/stylus-chrome-beta-3.0.3.zip)

**Comment by tophf** [comment]
[stylus-chrome-beta-3.0.4.zip](https://github.com/user-attachments/files/17962861/stylus-chrome-beta-3.0.4.zip)

**Comment by tophf** [comment]
[stylus-chrome-beta-3.0.4.zip](https://github.com/user-attachments/files/17965929/stylus-chrome-beta-3.0.4.zip)

**Comment by tophf** [comment]
[stylus-chrome-beta-3.0.4.zip](https://github.com/user-attachments/files/17970587/stylus-chrome-beta-3.0.4.zip)

**Pull request merged**
