### PR TITLE
Refactor chromeStorageDB

### LINKED ISSUE #839: Stylus stopped enabling / disabling or installing userstyles! (Chrome)
* **Browser**: Chrome 79.0.3945.130 and  80.0.3987.87 (Official Build) (64-bit)
* **Operating System**: Windows 10.0.18362 
* **Stylus Version**: 1.5.7
* **Screenshot**:

image
image
image

`Error while downloading usoID:............ Reason: TypeError: Cannot read property 'result' of undefined`

Today my long-time install of Stylus stopped working partially. I cannot install new styles, getting errors visibly shown above. Also, I cannot disable or enable individual styles now. The checkbox changes in both the popout and the extensions manager page, but no page updates ever trigger, and if you simply toggle the check and leave the window and return, the previous checkbox state is restored. And when I edit an individual style, toggle enabled checkbox, click save, and try to refresh, Chrome warns me "changes may not be saved", which definitely means they're not.  I can delete styles or turn all styles off at once though.

Tried restarting Chrome, nothing. Tried using incognito Chrome with very few plugins, same errors happen (which perhaps always happened?). Haven't tried reinstalling (fear losing a hundred styles hand-picked for high contrast accessibility). Haven't tried rebooting yet (lots of ongoing tasks!).  Checked on random popular sites: Google, Wikipedia, LinkedIn, GitHub, all the same result.  Never seen this behavior before ... in years?! Suspect an auto-update somewhere broke? Unsure.

Just saw Chrome ask me to relaunch to update to 80.0.3987.87, so I did, saw this:
image
So clearly all those are my individual repeated clicks to install random non-dark theme, a very unusual state! So redundant instances are 'semi-installed' which ... only became visible upon relaunch? Regardless, same issues remain.

I'm invested in seeing this plugin work well. I can check some things on behalf to help diagnose if it's uniquely on my system, if given some direction pointers how to do so.

### PR DESCRIPTION
**Pull request by eight04**
Fixes #839

* Fix: a save style error. The process failed but the data is stored in the DB.
* Fix: a race condition that may result in duplicated ID.

To test this branch, you have to switch to chrome storage DB by setting `localStorage.dbInChromeStorage` to `"true"` and reload the extension.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
>To test this branch, you have to switch to chrome storage DB by setting localStorage.dbInChromeStorage to "true" and reload the extension.

Or you can test in FF by setting it to "never remember history". AFAIK, the fallback storage should never be triggered in Chromium, correct? Isn't that one of the main bugs this PR is addressing? There's a couple/few settings/configs in FF which interfere with webextensions' access to indexedDB, so it it switches to the slower, accessible storage. 

This PR seems to work as originally intended, minus the bug where the fallback is erroneously triggered, presumably. As I understand it, the major drawback with the fallback has always been that by the time it's triggered, it's too late to transfer existing styles from indexedDB. Would it be worthwhile to always mirror them?

If not, then I guess I guess this improves the status quo, so we can merge as-is.

**Comment by eight04** [comment]
> the fallback storage should never be triggered in Chromium, correct?

No. The fallback is triggered when indexedDB is unavailable. #839 also uses Chrome.

> This PR seems to work as originally intended, minus the bug where the fallback is erroneously triggered,

No. This PR doesn't change how the fallback is triggered. It fixes:

1. A TypeError in chromeStorageDB when saving/installing a style.
2. A race condition that may result in duplicated style ID.
3. Drop `chromeLocal`, which doesn't handle errors correctly.

> Would it be worthwhile to always mirror them?

There are some discussions here: https://github.com/openstyles/stylus/issues/539

**Comment by narcolepticinsomniac** [comment]
>No. The fallback is triggered when indexedDB is unavailable

I realize that, I just assumed the fallback was strictly a FF workaround, and indexedDB should always be available in Chromium.

>#839 also uses Chrome.

I figured the fallback was getting triggered in Chromium due to a bug, which I thought you were addressing here. Are there really scenarios where indexedDB would legitimately be unavailable in Chromium?

**Comment by narcolepticinsomniac** [comment]
I get that this PR fixes issues with the fallback storage, and that's great. I'm still confused about #839 though, given the fact that I always assumed the fallback should never be triggered in Chromium. 

Obviously it was triggered in Chromium, and you made it pretty clear that "this PR doesn't change how the fallback is triggered". Unless I'm way off, and there is some legitimate reason the fallback would be triggered in Chromium, that still leaves us with a significant bug.

**Comment by tophf** [comment]
>fallback should never be triggered in Chromium

FWIW it did in #182, #187.

**Comment by narcolepticinsomniac** [comment]
So... it shouldn't happen, but sometimes it does, and it's nothing new. Guess that answers the question. At least this PR improves the fallback then.

**Pull request merged**
