### PR TITLE
add a hotkey & right-click to beautify silently

### LINKED ISSUE #970: Add option to not display beautify settings in editor
* **Browser**:
Firefox 77.0.1 (64-bit)
* **Operating System**:
Windows 10 
* **Stylus Version**:
1.5.11
* **Screenshot**:
image

Hi, cool extension, I'm enjoying being able to write some custom styles... 
This could be added as a checkbox unchecked by default. I just don't change my beautify settings that much so having to close the window every time I click Beautify is slightly annoying.

### PR DESCRIPTION
**Pull request by tophf**
Fixes #970.

Pressing a configurable hotkey or right-clicking the Beautify button will perform beautification silently i.e. without showing the dialog. This info and the hotkey input itself are shown at the bottom of the beautify panel.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
This is pretty cool. Only minor issue I see having the potential to be slightly confusing is global vs section beautify. 

The shortcut/right-click only works globally AFAICT, and only with the global button, but the hint is shown in the beautify dialog when beautifying by section. 

I doubt beautifying by section is all that popular, but we should probably avoid conflating the two. Section beautify should either get a separate shortcut/right click, or we should hide the hint for section beautify.

**Comment by tophf** [comment]
Eeeh I forgot about the per-section button. Fixed now. The hotkey now works for a section when its area is focused i.e. the code editor or the applies-to block. Otherwise it's global.

**Comment by narcolepticinsomniac** [comment]
That works. LGTM, thanks tophf.

**Comment by dogboydog** [comment]
Thanks!

**Pull request merged**
