### PR TITLE
fix nextcloud WebDAV csrf error

### LINKED ISSUE #1447: [Bug] Error when trying to sync to the cloud using WebDAV
# Bug Report

### Bug Description

When I configure to sync through WebDAV with Nextcloud I get the following error message:
`failed to fetch [401]: <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception> <s:message>CSRF check not passed.</s:message> </d:error> `
Is it possible, that the bug is only related to Nextcloud?

### Screenshots

grafik

### System Information

- OS: Windows 10
- Browser: Firefox 101
- Stylus Version: 1.5.25

### PR DESCRIPTION
**Pull request by tophf**
Fixes #1447.

@eight04, could you test this? I never used nextcloud...

### CODE REVIEW

**Comment by eight04** [comment]
I have never used Nextcloud either.

@MagicLike

**Comment by tophf** [comment]
@MagicLike, try installing this [zip](https://github.com/tophf/stylus/archive/refs/heads/fix-dav.zip) in a new browser profile as an unpacked extension on `chrome://extensions` page (in developer mode).

**Comment by MagicLike** [comment]
Ok, it works now...
But the strange thing is, it somehow loaded up my styles two days ago (Without me noticing) and synced it now... (Using Firefox and synced to Chromium)
So I don't know, if this fixed the error in particular, but it works.
Maybe someone else is also experiencing this issue?

**Comment by nawordar** [comment]
I had the same problem and installing the extension from zip worked

**Pull request merged**
