### PR TITLE
Install usercss

### PR DESCRIPTION
**Pull request by Mottie**
Added color & Stylus icon to the usercss install button - ref: https://github.com/openstyles/stylus/commit/e90de3783a36e782324663397680b917f3168749

### CODE REVIEW

**Comment by tophf** [comment]
@narcolepticinsomniac, @MechaLynx, thoughts?
Use any of raw github urls for testing e.g. [this](https://rawgit.com/RaitaroH/Jisho-DeepDark/master/JishoDeepDark.user.css).

**Comment by narcolepticinsomniac** [comment]
Nice! I really like them for the most part. Using the icon solves the translation issue where the position may be unpredictable. Maybe we should consider doing the same for the badge. 

I have a few suggestions. I like the buttons a bit shorter and wider. Maybe tweak the default install `:before` gradient to be a little darker and less saturated with slightly less blue. As for the box-shadow, I think it's good to give them a little contour, especially on a white background, but I prefer them a little more like a pseudo-border with different shades to work with the gradients.

```
@-moz-document regexp("chrome-extension://.*/install-usercss..*") {
.install:before {
    background-image: linear-gradient(hsl(176, 44%, 40%), hsl(176, 50%, 35%))!important;
    border: 0!important;
    box-shadow: inset 0 -1px 0 0 hsl(0, 0%, 24%), inset 0 1px 0 0 hsl(0, 0%, 30%), inset 1px 0 0 0 rgba(0, 0, 0, .3), inset -1px 0 0 0 hsl(0, 0%, 38%);
}
.install {
    box-shadow: inset 0 -1px 0 0 hsl(0, 0%, 24%), inset 0 1px 0 0 hsl(0, 0%, 30%), inset 1px 0 0 0 hsl(0, 0%, 24%)!important;
    padding: 4px 38px 4px 10px!important;
}
}
```

**Comment by MechaLynx** [comment]
I see nothing wrong with this. It's clear and prominent as an affordance but not gaudy so it's unlikely to trigger banner blindness. Works in responsive mode and it's clearly stylable. 👍

**Comment by Mottie** [comment]
> I like the buttons a bit shorter and wider

That looks good too.

> box-shadow, I think it's good to give them a little contour

I'm not sure I like the way the icon portion looks like it's inset into the button. This is especially prominent when I zoom in:



What do you think of this change:

* Remove the box-shadow on the icon portion.
* Adds the border to the `:after` definition.
* Adds a slight margin around the icon portion by insetting the `top`, `bottom` and `right` definitions.
* The border radius is adjusted to match the edges (at least that's the way it looks for me in Chrome).



```css
@-moz-document regexp("chrome-extension://.*/install-usercss.*") {
  .install {
      box-shadow: inset 0 -1px 0 0 hsl(0, 0%, 24%), inset 0 1px 0 0 hsl(0, 0%, 30%), inset 1px 0 0 0 hsl(0, 0%, 24%) !important;
      padding: 4px 38px 4px 10px !important;
  }
  .install:before {
      background-image: linear-gradient(hsl(176, 44%, 40%), hsl(176, 50%, 35%)) !important;
  }
  .install:before,
  .install:after {
      border-left: 1px solid rgba(128, 128, 128, .4) !important;
      top: 1px !important;
      right: 1px !important;
      bottom: 1px !important;
      border-radius: 0 3px 3px 0 !important;
  }
}
```

**Comment by narcolepticinsomniac** [comment]
Sure. I originally started with the 1px position on `:before`, but thought it looked slightly better with different shades for top/right/bottom. If I understand you right, it's the left one that's not as clean as the equivalent border, which seems accurate. Either way, the shading is so subtle it doesn't really matter. They look good with your last adjustment. Overall, huge improvement to the previous, over-padded default.

**Comment by tophf** [comment]
I like the shadow more than a border, but I guess either is fine.
Sow what do we do?

**Comment by narcolepticinsomniac** [comment]
>I like the shadow more than a border

Maybe we could just replace the left one with a border. NBD either way.

>So what do we do?

We in a rush?

**Comment by tophf** [comment]
Okay, let's go with the border-like shadow. It's fine too.

**Pull request merged**
