### PR TITLE
Fix: detect style CSP

### LINKED ISSUE #562: With v1.5.0, Stylus can't style AMO anymore despite setting the about:config prefs to allow webexts to run on AMO
* **Browser**: 65.0a1 (2018-11-17)
* **Operating System**: Windows 10
* **Stylus Version**: 1.5.0
* **Screenshot**: with `* { color: red !important; }` for `URLs starting with: https://addons.mozilla.org/`
<details><summary>v1.4.23</summary>

capture2
</details>
<details><summary>v1.5.0</summary>

capture
</details>

STR:
1. Clear `extensions.webextensions.restrictedDomains` or just remove AMO from it
2. Set `privacy.resistFingerprinting.block_mozAddonManager;true`.
3. With these two prefs set, Stylus used to be able to style AMO but with 1.5.0, it no longer can.

### PR DESCRIPTION
**Pull request by eight04**
Fixes #562.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Tested on AMO. Appears to work, and I didn't notice any speed issues, but sometimes there's dozens of errors:

csp

Sometimes there's only one or two, which seems more reasonable.

**Comment by eight04** [comment]
I think it is not related to Stylus. Does it happen with a fresh profile?

**Comment by narcolepticinsomniac** [comment]
It's a clean profile 60.3.0esr. Oddly enough, I can only repro consistently if I paste a link in the URL bar and navigate to an AMO that way. Maybe just FF being a buggy POS as usual, and it's probably just a harmless edge case, but I'd prefer if I wasn't the only one seeing it. Using our URL, not that it should matter:
https://addons.mozilla.org/en-US/firefox/addon/styl-us/

**Comment by Mottie** [comment]
It seems like changing the UserCSS settings is only making the first change... all additional changes (at least for GitHub Dark) aren't applied, until you close the settings and open it again. This is the same from the popup or the manager... no errors in console.

**Comment by eight04** [comment]
> It's a clean profile 60.3.0esr. Oddly enough, I can only repro consistently if I paste a link in the URL bar and navigate to an AMO page that way. Maybe just FF being a buggy POS as usual, and it's probably just a harmless edge case, but I'd prefer if I wasn't the only one seeing it. Using our URL, not that it should matter:
> https://addons.mozilla.org/en-US/firefox/addon/styl-us/

I can reproduce it without installing Stylus so it should be unrelated to Stylus.

> It seems like changing the UserCSS settings is only making the first change... all additional changes (at least for GitHub Dark) aren't applied, until you close the settings and open it again. This is the same from the popup or the manager... no errors in console.

Why do you think it is related to CSP? BTW I think there is a problem about usercss live preview, which should be recompiled when the style setting is changed outside of the editor. Currently, it is only recompiled on the change event of the editor.

**Comment by Mottie** [comment]
> Why do you think it is related to CSP? BTW I think there is a problem about usercss live preview, which should be recompiled when the style setting is changed outside of the editor. Currently, it is only recompiled on the change event of the editor.

Too many tabs open! Wrong issue 😛

**Pull request merged**
