### PR TITLE
auto-promisify browser.* methods on call

### PR DESCRIPTION
**Pull request by tophf**
@eight04 here's the auto-promisifier I meant back then. Could you take a look, please? There's a potential weak point which I'd like to strengthen if possible in regards to callbackless methods such as browser.runtime.getURL: currently the promisifier always tries a promise first (except for addListener and such), then if an exception occurs it retries in direct call mode.

This is not a problem currently - our code doesn't hit this fallback path because we use these callbackless methods via `chrome` e.g. chrome.runtime.getURL. Strictly speaking, it wouldn't be a problem either way but it'd spoil debugging when "pause on caught exceptions" is enabled.

So here's an idea: we can generate a list of callbackless methods during build, for example. See `chrome-api-no-cb.js` in this PR. It just lists the methods currently. How can we use it? Splice the names into polyfill.js so it can check them like we do with codemirror-themes.js maybe? Or run a check on the source code to show warnings when such a method is called via `browser`?

<details>
<summary>Here's the generated list of callbackless methods limited to our `permissions`</summary>

```
chrome.alarms.create(optional DOMString name, AlarmCreateInfo alarmInfo): void
chrome.extension.getBackgroundPage()
chrome.extension.getExtensionTabs(?windowId: integer)
chrome.extension.getURL(path: string)
chrome.extension.getViews(?fetchProperties: object)
chrome.extension.setUpdateUrlData(data: string)
chrome.i18n.getMessage(messageName: string, ?substitutions: any, ?options: object)
chrome.i18n.getUILanguage()
chrome.identity.getRedirectURL(optional DOMString path): DOMString
chrome.runtime.connect(?extensionId: string, ?connectInfo: object)
chrome.runtime.connectNative(application: string)
chrome.runtime.getManifest()
chrome.runtime.getURL(path: string)
chrome.runtime.reload()
chrome.runtime.restart()
chrome.tabs.connect(tabId: integer, ?connectInfo: object)
```

</details>

P.S. We could generate this from @types/chrome package instead but it's rarely updated and I'm not sure it's 100% correct.

### CODE REVIEW

**Comment by eight04** [comment]
How about switching to [webextension-polyfill](https://github.com/mozilla/webextension-polyfill)? I think our solution is getting more and more complicate.

**Comment by tophf** [comment]
webextension-polyfill creates all methods at once even though they're not used so it wastes time. It's also huge because it lists every method's number of parameters, which we also don't need.

**Comment by tophf** [comment]
Fine, I've added a small list of methods to call directly just in case, even though it's not necessary now, but thanks the weak point can be considered strengthened now.

**Comment by narcolepticinsomniac** [comment]
Probably gonna update beta in the immediate future. Merge whatever you're comfortable with, and wanna include.

**Comment by tophf** [comment]
@narcolepticinsomniac this PR isn't essential so let's release at the current `master` 3db6662d.

**Comment by narcolepticinsomniac** [comment]
Fine by me. Mottie said he'll probably get to it in the morning. Just letting you know in case you wanted anything else included.

**Pull request merged**
