### PR TITLE
update deps + split devdeps/deps

### PR DESCRIPTION
**Pull request by tophf**
* Split production deps into `dependencies`
* Didn't update `endent` because it breaks `build-vendor` action in package.json

@eight04, @Mottie please either review it ASAP or say you won't so I'll undo everything except CodeMirror update.

### CODE REVIEW

**Comment by eight04** [comment]
Haven't test it but LGTM. It seems that uuid update doesn't affect browser build (https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md).

**Comment by tophf** [comment]
The contents of uuid.min.js differs slightly e.g. it uses a typed array now.

**Comment by tophf** [comment]
@narcolepticinsomniac I guess then this can be merged if it passes your test. Of production dependencies only CodeMirror and UUID were updated.

**Comment by narcolepticinsomniac** [comment]
I have tested this a little, and haven't noticed any issues. Gotta pull the trigger sometime, so might as well merge it. Hopefully that'll help get at least a few more people testing.

**Pull request merged**
