### PR TITLE
Adding external licenses

### PR DESCRIPTION
**Pull request by stonecrusher**

### CODE REVIEW

**Comment by tophf** [comment]
I think the file name should always be LICENSE. I never saw it being otherwise.

**Comment by stonecrusher** [comment]
I'll change it.
It was just very inconvenient to have 10 times LICENSE open in editor.
And for jsonlint it's not clear what license to use because the code we're actually using seems to be generated by jison

**Comment by tophf** [comment]
Almost everything is fine AFAICT but one thing - since Stylus might still have bits of code authored by Jason, I think our readme should simply list him in present time without mentioning "Stylish" or "predecessor".

**Comment by tophf** [comment]
Something like:
Inherited code from the original Stylish: copyright 2005-2014 Jason Barnabe
Current code: copyright 2017 Stylus Team

**Comment by stonecrusher** [comment]
Done.
I wonder if "Stylus Team" even is allowed. Pseudonyms are allowed, but it doesn't point to a person or legal person / corporate entity.

**Comment by tophf** [comment]
IANAL so LGTM.

**Comment by stonecrusher** [comment]
Ah sorry forgot to change one link in readme.md from COPYING to LICENSE, maybe you could change it so I don't have to make a new PR

**Comment by tophf** [comment]
Done.

**Pull request merged**
