### PR TITLE
update USO-archive urls

### PR DESCRIPTION
**Pull request by tophf**
@33kk, could you please take a look at this PR as we want to use your new USO-archive URLs (including CDN) to avoid a couple of minor issues: flashing of the old address during redirection and flashing of style text when installing from the site page.

Questions:
1. I have to prefetch a big style json when the author label is clicked to get its id. This can be solved by a) adding `ai` to the index but it's rarely used so I'm not keen on this idea, b) adding a search mode `browse/styles/?author-for=${styleId}` so your site's page will download the json, extract the author id, and show the results, c) split your json to ###.meta.json without CSS and ###.css with just the css and no usercss header, by the way who uses this css in json?
2. Do you plan to change the USO-archive URLs anytime soon? When you do, could you inform us beforehand and/or maintain the redirection for a while until we publish a new version of Stylus just like you do currently with the old site?

### CODE REVIEW

**Comment by tophf** [comment]
`ai` it is then, great! As for `css` in json, we never used it. I don't see how it can be useful without the usercss header, which is already present in a separate file. I wonder if you can generate this json on-the-fly from the original uso json if your statistics show it's rarely used...

**Comment by 33kk** [comment]
> I don't see how it can be useful without the usercss header

Generating full css files without placeholders like USO did

> I wonder if you can generate this json on-the-fly from the original uso json if your statistics show it's rarely used...

I don't really have any detailed statistics and I don't have any servers, it's all hosted on Github

**Comment by tophf** [comment]
I see.

@Gusted, I wonder if USW can also expose `authorId` as `ai` in its index file and support `user/id/` or `user-id` endpoint? Or do you simply disallow registering an already existing user name? Currently we use it in the popup for the author link in the style search results.

**Comment by Gusted** [comment]
#

>  I wonder if USW can also expose `authorId` as `ai` in its index file

That's possible. 



>  and support `user/id/`

Still possible @vednoc FYI. `/user/id/:id`.



> Or do you simply disallow registering an already existing user name?

What you mean? Registering an already existing user name? Do you mean the login/register behavior? You currently can only register a unique username and we assign a userID to that account which is an simple increment.

**Comment by tophf** [comment]
> You currently can only register a unique username

In this case Stylus doesn't need `ai` and the `id` endpoint because the user name is already unique.

**Pull request merged**
