### PR TITLE
Copyable elements accessibility

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
@Mottie @eight04 We good with this for accessibility?

**Comment by eight04** [comment]
Isn't a link leads to nowhere actually against accessibility?

**Comment by narcolepticinsomniac** [comment]
>Isn't a link leads to nowhere actually against accessibility?

If it is, we sure do it a lot. It allows you to tab through them and execute their click action on enter, which is pretty much my gold standard for accessibility.

**Comment by eight04** [comment]
I suggest using the following HTML structure:
```html
<span class="code-snippet-inline">
  <code>Some code</code>
  <button type="button" class="copy-button">(a clipboard icon or something?)</button>
</span>
```

**Comment by narcolepticinsomniac** [comment]
It's some small font, and we want these clickable text strings to wrap pretty normally with their surrounding text. I used the tiniest copy icon possible, and I don't see that making for much of a button. 

Any decent size button is sure to throw off line-height. I don't get the aversion to using links to simplify accessibility. If we want them to wrap naturally, I'd think they'd make the most sense.

If it's gonna bug you, you're welcome to change the html to whatever you want, as long as the appearance and functionality are identical. Otherwise, links are simple, wrap nicely, and are accessible.

**Pull request merged**
