### PR TITLE
set min-height outside of query

### LINKED ISSUE #871: Usercss editor performance issues Chromium v80
The larger the stylesheet, the worse the performance. Github Dark is practically uneditable. No such issues in Chromium 78 or FF.

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
Closes #871

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Pretend there's no typo in the branch name. =) 

@Mottie This does the trick, right?

**Comment by Mottie** [comment]
> This does the trick, right?

Sorry, what are you trying to accomplish? All I am seeing is `min-height: 0;` moving from one `#sections` block to another `#sections` block. Nothing should change. In fact we should probably combine those two sections.

**Comment by narcolepticinsomniac** [comment]
>Sorry, what are you trying to accomplish?

You brought the Github Dark issue up, so I was asking you to verify that this simple change resolves it. Obviously, I already tested, so I'm pretty sure it does.

>All I am seeing is `min-height: 0;` moving from one `#sections` block to another `#sections` block. 

Because that's all it is.

>Nothing should change.

It was in a compact layout media query, and now it's not, so I beg to differ.

>In fact we should probably combine those two sections.

Again, one's a query, so... no.

**Comment by xt0rted** [comment]
I was the one who brought this issue up in the GitHub Dark repo, I just tried the fix in the latest version of Chrome 80 and it does fix the issue I was having. Editing the style is back to being just as responsive as using VS Code. Thanks for looking into this and fixing it.

**Pull request merged**
