### PR TITLE
Flex popup with optional layouts/click actions

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
It's been about a year since both of my PRs for improving the popup. The main objectives were to make it a full-flex icon-action layout, with optional style name click actions. There would, of course, be an option to revert to the classic layout, with style name click action being a separate pref so you can mix and match. All rearranging for layouts, including "actions on top" is achieved via all action wrappers being siblings and moving them around with `order:`.

Tophf never felt like hooking up the js, so I finally decided to give it a shot. JS isn't my strong suit, but I think I got it all working properly. There's probably room for improvement. I spent a lot of time on the icons, fine-tuning a couple in Inkscape. I think they're good, but nothing is set in stone. The Wikipedia icon for "wiki" may be a reach, but I thought it was decent. Try it out and let me know what you think.

### CODE REVIEW

**Comment by tophf** [comment]
I see many small things in the code that need simplification so I'll handle the other PRs first (sync and exclusions). BTW did you check how the change affects the existing popular themes?

**Comment by narcolepticinsomniac** [comment]
>I see many small things in the code that need simplification

I'm gonna call that a win. =) I've certainly gotten worse reviews. I know I probably at least duped some functions unnecessarily in the interest of getting everything working. Easier to optimize some js if all the supporting code is already working around it.

I'm also gonna take the fact that you didn't immediately hate on anything in particular as win. Not exactly a compliment, but I'll take what I can get. Maybe a few cosmetic details, but I think it's pretty snazzy looking.

>I'll handle the other PRs first (sync and exclusions)

Those two have dragged on forever. This one needs testing for a good while anyway. but hopefully you actually believe they're close?

>BTW did you check how the change affects the existing popular themes?

No. I've said before it should be pretty low on the priority list. I've been working on this off and on all week and never even checked my own. I could've told you before looking though that it wouldn't be great.

The only userstyle-friendly way to do the light grey is to put it on the `body`, which would require reworking zebra-striping, and I wasn't sabotaging the actual objectives here by messing with it. Semitransparent on `body` gets messy with the inline search gradient, but that could probably be adjusted. Any which way to get the same color scheme is a simple adjustment, but I'd rather you do it the way you like than suggest something you hate. 

Otherwise, all icons have the common selector, which should be covered by most. Mine doesn't, but my mind works in mysterious ways. =) Anyway, most popular UI styles are pretty well maintained, so they'll adjust to whatever.

**Comment by tophf** [comment]
It's weird how every discussion between you and me starts to deviate into name calling and ad hominem recently. What should we do about it?

**Comment by narcolepticinsomniac** [comment]
Intentional or not, you're the who starts with the little insults. It's great that you're above arguing on the internet, but that only works if you're not rude, otherwise it's just a way to be rude without having to argue about it.

>What should we do about it?

Idk, not be dicks? If you have some strong opinion about, shoot me a PM. I'll likely agree to whatever.

**Comment by narcolepticinsomniac** [comment]
You're the last person I'm looking to argue with, it's just not in my nature to ignore perceived insults. I can tell myself it's lost in translation and ignore it in the future. Can't argue if I'm not offended. We should be able to make that work. Otherwise, I'm the supporting cast here, so I'd definitely take more of a backseat if need be. This PR is dope though. =)

**Comment by Mottie** [comment]
Deferred to #517.

**Pull request closed without merging**
