### PR TITLE
Make fieldset labels siblings to selects

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
It's odd that they're parents IMO. Since selects have their own click action, clicking to the right of them registering as a checkbox click seems like an oversight, but I just noticed a hover background that suggests otherwise. I think they're better like this, but NBD if you disagree for whatever reason. I suppose I could fix it with pointer events or something in my personal CSS.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Looking real quick, my indents may be off. I'm out the door for now though. I'll fix it if you agree.

**Comment by tophf** [comment]
Hmm, labels that encompass both the dependent control and the label text itself are normal and standard I think, and rather convenient, especially to toggle the row without aiming at the checkbox. Why is that a problem? Extending clickable area beyond the displayed text is common in UI, provided it's indicated by a hover effect.

**Comment by narcolepticinsomniac** [comment]
Yeah, clickable labels are standard and convenient, but these are not standard labels. The checkbox click action being disrupted by the `select` and then being present again on the random amount of trailing space feels disjointed to me. 

Quite likely another detail which bugs me more than most. If I haven't sold you on it yet, I won't try to convince you.

**Comment by narcolepticinsomniac** [comment]
>less disjointed (why is that important?)

Well, that's not the adjective you shoot for when designing, and it's pretty accurate here. 

"Convenient" is an adjective you shoot for, however. I don't find it convenient, but at least someone does. I'll fix it in my personal style. Figured it was worth suggesting, but it isn't of the utmost importance.

**Comment by tophf** [comment]
I just tried to reduce the damage we did to the basic checkbox behavior when the filters became inline selectors - previously users could click anywhere on the label to toggle it.

**Pull request closed without merging**
