### PR TITLE
async'ify update.js + metacss + uso2usercss

### LINKED ISSUE #892: Implement .meta.css
It is available on GreasyFork now:
https://github.com/JasonBarnabe/greasyfork/issues/657

### LINKED ISSUE #1122: [Feature Request] Check for presence of UserCSS header in styles installed from UserStyles.Org and parse it if present
* **Browser**: Google Chrome 86.0.4240.198 (doesn't matter)
* **Operating System**: Windows 10 (doesn't matter)
* **Stylus Version**: 1.5.13
* **Screenshot**: none

I have a style on USO used by over 260k users. Recently decided to move it on GitHub, but apparently Stylus ignores UserCSS header in styles installed from USO. As the result I can't use @updateURL to point users with existing installations to a new location and the only option I have is to make them remove existing one and install manually from a new location.
Style in question: https://userstyles.org/styles/101141/ru-adlist-css-fixes

Is it possible to implement UserCSS header parsing for styles installed from USO and use it when it's present and valid?

### PR DESCRIPTION
**Pull request by tophf**
Fixes #892.
~Fixes 1122.~

@eight04 if you'd like to review, here's a simpler PR extracted from that monster.

### CODE REVIEW

**Comment by tophf** [comment]
Ah, damn, looks like USO doesn't return a comment-only global section in its json so I guess this doesn't work unless the style starts with `@namespace` or `@charset`...

**Comment by eight04** [comment]
> downloading the original css text from USO and parse it locally

I wonder what will happen if someone uploads a usercss file to USO. It sounds like we can treat it as a simple text host.

**Comment by tophf** [comment]
We can but there are problems I noted above.

**Comment by tophf** [comment]
Well, we can make an additional request for JSON sections to read the name though...

**Comment by eight04** [comment]
> looks like USO doesn't return a comment-only global section in its json

Does USO also strip comments in sections? If our goal is to fix #1122, maybe we don't have to implement the entire usercss metadata spec. Just try to search (regex) an `@updateURL` in all sections and reinstall? Also we don't have to stick with `@updateURL` but search something like `*** USERCSS MIGRATION LINK: http://example.com/test.user.css ***` since it is just a piece of comment.

**Comment by tophf** [comment]
It only removes empty sections that contain only comments.

**Comment by tophf** [comment]
Will be implemented in #1116.

**Comment by tophf** [comment]
Er... will wait until the big one is merged.

**Comment by tophf** [comment]
BTW there'll be a superfast mozparser so parsing the original css won't be a problem anymore.

**Comment by tophf** [comment]
Removed uso2usercss because it looks like we should expose it in UI so it'll be a separate PR.

**Pull request merged**
