### PR TITLE
option to open editor in a simple window (no omnibox)

### PR DESCRIPTION
**Pull request by tophf**
Adds an option to use a simple window (no omnibox) when opening editor in a new window.

The option is not enabled by default in order not to aggravate the users. FWIW personally I like this simplified window better as there are no distractions and it provides more space for the code.

### CODE REVIEW

**Comment by dnknn** [comment]
open a simple window (no omnibox), Is very good, but there is a problem: It will not be able to use Stylus-Popup’s hotkey.

`chrome://extensions/shortcuts#:~:text=Stylus,Activate the extension`
↑ This URI link can be directly opened and jumped to highlight the destination(Chrome⁸¹ᐩ is valid)


So, if "open a simple window" can still use Stylus-Popup's hotkey, it will be perfect. Is it possible?

**Comment by tophf** [comment]
No. This is a bug (or an inherent deficiency) of Chrome.

**Comment by dnknn** [comment]
That's really a pity...

**Comment by tophf** [comment]
Why do you need it in the editor window?

**Comment by dnknn** [comment]
Because I set the ON/OFF switch of Stylus's own style :) , So sometimes need to use `Alt+Z` .:)

**Comment by tophf** [comment]
You can use a hotkey to toggle all styles or press Alt-Enter to toggle the current style in the editor.

**Comment by dnknn** [comment]
> You can use a hotkey to toggle all styles or press Alt-Enter to toggle the current style in the editor.

I know all of these, it has nothing to do with them. Except that the hotkey of ʻActivate the extension` cannot be used, everything else is fine.

Is it really impossible to use `a simple window` and the hotkey of `Activate the extension` at the same time?

If there is no solution, I still use traditional window.

**Comment by tophf** [comment]
> it has nothing to do with them

I still don't understand what you're using it for.

> Is it really impossible

Still is.

**Comment by dnknn** [comment]
> I still don't understand what you're using it for.
> 
> >

Because I modified Stylus-editor with CSS/UserCSS(Configuration), so sometimes need to use `Alt+Z` to activate the Stylus-Popup.

I recorded a gif to show you, you will understand the specific meaning:
http://note.youdao.com/s/bhUsZu1z

**Comment by dnknn** [comment]
> I still don't understand what you're using it for.
> 
> >

Because I modified Stylus-editor with CSS/UserCSS(Configuration), so sometimes need to use `Alt+Z` to activate the Stylus-Popup.

I recorded a gif to show you, you will understand the specific meaning:
http://note.youdao.com/s/bhUsZu1z




 `Alt+Shift+Z` and `Alt+Shift+A`  are valid and available, only `Alt+Z` cannot be used.

**Comment by tophf** [comment]
I see now, thanks.

**Comment by dnknn** [comment]
> I see now, thanks.

so, can not use hotkey to activate the Stylus-Popup, it is the biggest problem, otherwise `a simple window` will be perfect, with no extra disturbing elements.

**Comment by dnknn** [comment]
> I see now, thanks.

so, can not use hotkey to activate the Stylus-Popup, it is the biggest problem, otherwise `a simple window` will be perfect, with no extra disturbing elements.

Because I don't understand any code language or extension API except simple-CSS, can  you help find the information, maybe there is a fix/solution?

**Comment by tophf** [comment]
For the third time: no, it's not possible.

**Comment by dnknn** [comment]
> For the third time: no, it's not possible.

Ok, I see. Thanks you! not a big problem either.

**Comment by tophf** [comment]
I've added a button and hotkey that shows the popup in iframe right inside the editor, #1128.

**Comment by dnknn** [comment]
@tophf  I also like this simple editor window, and I solved it in 2 ways before:

1) In simple editor window, I first press the shortcut(`Alt+Shift+A`) of the manager  to open manager page,  then Stylus-popup(`Alt+Z`) is displayed there, finally switch to simple editor window.

2) [Make this request to Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1139712)
---
And now it's perfect, it can be achieved directly in simple editor window, Thank you very much!

**Pull request merged**
