### PR TITLE
Opt-out of buggy embedded options

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
I'm sick of hearing about different versions of different browsers breaking embedded options, and all the ridiculous workarounds which inevitably cause new conflicts. This PR gets rid of embedded options altogether in favor of opening them in a separate tab. Not sure if the "Stylus" header needs translations.

@eight04 @Mottie WDYT?

**Comment by tophf** [comment]
Originally in Stylish there was just a couple of options which were shown in the manager's header pane so I'd say it would make sense to move them all back in the manager page but show inside a `MessageBox()` just like style config is shown or linter options in the editor page. The page URL would be `manage.html#options` or `manage.html?mode=options` (in manifest.json and other places where options.html was used) so manage.js would check that on start and show the UI accordingly.

**Comment by narcolepticinsomniac** [comment]
If you care enough to hook it up, feel free to do it here or in another PR. As long as embedded options are eliminated, I'm good. Sounds like it might be a little cooler, but this PR already accomplishes the main objective, and I don't care enough to screw around with it any further.

**Comment by tophf** [comment]
No, not really interested myself, just an suggestion.

**Comment by narcolepticinsomniac** [comment]
@tophf I decided to experiment with a lazier version of your suggestion, embedding options as-is in the manager. It is kinda cool, but there's some minor issues with `chrome.runtime.openOptionsPage()` when it determines if the options page is already open. 

I ended up having to add the question mark before the hash `manage.html?#stylus-options` for Chromium not to forego opening the options URL and just focusing the open manager tab without adding the hash. 

FF worked with or without, but either way, both will open a new manager page, which isn't ideal, but not exactly terrible either since it's sorta an edge case. It only occurs if the manager's already open, and you're not launching options via the button inside the manager, which of course just updates the parameter/hash with `history.replaceState()`.

Check it out and LMKWYT. 
[stylus-master.zip](https://github.com/openstyles/stylus/files/4080087/stylus-master.zip)

**Comment by tophf** [comment]
Yay, looks even better than I thought it would! As for the "manage styles" button opening a new tab it felt weird so maybe just remove the button? And probably let the Esc key close the UI for consistency.

**Comment by eight04** [comment]
I pretty like the builtin options page in Firefox, which acts as a tab and sits beside add-on information.

For the standalone options page, I think we can make it more like a web page, so the scroll bar locates on the right side instead of the middle area.

For "embed options page in manager", I think you have to write a router that handles search params. Some code is [here](https://github.com/openstyles/stylus/blob/a3c22325b88688ff1c1387b735dac3c855c8e790/manage/filters.js#L13). Using URL hash is a bad idea IMHO. Do you want to close this PR and create a new "embed options page in manager" PR?

**Comment by narcolepticinsomniac** [comment]
Closed in favor of #828

**Pull request closed without merging**
