### PR TITLE
Update Stylelint defaults for Stylus-lang at-rules

### PR DESCRIPTION
**Pull request by stonecrusher**

### CODE REVIEW

**Comment by eight04** [comment]
What is the purpose of this PR? If you want to ignore `at-rule-no-unknown` lint error in the editor, this PR should have no effect, because this type of errors is always ignored:
https://github.com/openstyles/stylus/blob/b48817fe01d4079b5eeec0e817e3ed6f240a16f9/edit/linter-engines.js#L43-L44

**Comment by stonecrusher** [comment]
I remember tophf added those lines 43, 44... after request.
The second part of the condition doesn't work anymore as the text has changed to `Unknown at-rule`.
2019-04-14 17_13_53-_ github com - 14 4 2019, 17_03_25

Furthermore the second part should be enough and specifying `@block`, `@extend` and `@extends` would be redundant. But then ignoring all unknown at-rules is hardcoded instead of being optional in the linter options.

Linter options were broken the past months anyway so I have no fear of overwriting custom saved rules. I think the problem was that the updated defaults will only reach fresh installs of Stylus, but I don't see a problem in this.

IMHO: The message filter can be deleted, we're scoping the root of the problem now.

**Comment by Mottie** [comment]
> What is the purpose of this PR?

I noticed the warnings showing up as well, even with the `@preprocessor stylus` rule set. I didn't realize there were exceptions set up in the code base. If you think hard-coding these settings are unnecessary, then please revert these changes.

I did find anther issue with using the stylus preprocessor. I tried copy/pasting the following `@extend` example from [this page](http://stylus-lang.com/docs/extend.html). It wouldn't save because of missing curly brackets:

```css
red = #E33E1E
  yellow = #E2E21E

  .message
    padding: 10px
    font: 14px Helvetica
    border: 1px solid #eee

  .warning
    @extends .message
    border-color: yellow
    background: yellow + 70%

  .error
    @extends .message
    border-color: red
    background: red + 70%

  .fatal
    @extends .error
    font-weight: bold
    color: red
```

**Comment by stonecrusher** [comment]
> If you think hard-coding these settings are unnecessary, then please revert these changes.

I can't understand what you mean? Current status (after changes) is:  
hard-coded message filter is removed; suppressing warnings directly from the linter via default linter options (user customizable) now.

> It wouldn't save because of missing curly brackets

Yeah unfortunately the backetless syntax of Stylus-lang was never fully supported, I'm using the bracketed variation all the time (which is no big deal). But that's not a linter problem, otherwise it would show an error before saving.

**Comment by Mottie** [comment]
Hard coding means that the stylus language `@rules` won't not throw an error if the preprocessor isn't set to `stylus`. So it may appear that it will work but not work at all - making it more difficult to troubleshoot the problem.

**Pull request merged**
