### PR TITLE
import/export options in backup json

### LINKED ISSUE #596: Export should include prefs & custom usercss settings
Title says it all.

### PR DESCRIPTION
**Pull request by tophf**
Fixes #596.

Potential problems:

* The `_rev` property is no longer checked when comparing for metadata equality so exporting a backup and immediately importing it back will say nothing's changed as one would expect. Previously we showed helluva lot of changes in this scenario which was weird.

  AFAICT, nothing should break due to this change as the style's contents is the same but I'd like to confirm just in case, @eight04, is it okay in regards to sync?

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
This will be way more convenient. I'm seeing an issue with instant inject slider in options not reflecting the imported pref though.

>import prefs only on demand

I'm trying to imagine a scenario where you wouldn't wanna include prefs. Doesn't hurt to make it optional on local imports, but I kinda figured we might wanna include prefs in cloud sync eventually as well. I suppose that could also be optional, if and when they're ever available to be synced, but I do wonder if it's necessary in either case.

**Comment by tophf** [comment]
1. Fixed the instant inject pref.

2. The prefs are always *exported* as it's just a few kilobytes, but auto-importing prefs from an old backup may be undesirable as the user's personal preferences may have changed since, which is why there's a separate button to import the options explicitly. This separation will only become more important as we add more options. The button is shown when the backed up prefs differ from the current ones.

**Comment by narcolepticinsomniac** [comment]
Hmm. Instant inject still isn't initializing. Everything looks like it is, but it's not. If I reload Stylus, it applies.

**Comment by tophf** [comment]
That's the best I can do with it being an optional permission.

**Comment by tophf** [comment]
Ah, now I understand what you meant. Should work now.

**Comment by narcolepticinsomniac** [comment]
Yep, nice. LGTM now. Seems unlikely it'll conflict with sync, but hopefully 8 can confirm.

**Comment by tophf** [comment]
More goodies.

* include lint configs and usercss template
* simplify exportFile as crbug.com/798705 was fixed

**Comment by eight04** [comment]
>  * The `_rev` property is no longer checked when comparing for metadata equality so exporting a backup and immediately importing it back will say nothing's changed as one would expect. Previously we showed helluva lot of changes in this scenario which was weird.
>    AFAICT, nothing should break due to this change as the style's contents is the same but I'd like to confirm just in case, @eight04, is it okay in regards to sync?

Yes. The `_rev` tag shouldn't affect the import process. It is reset before saving the style:
https://github.com/openstyles/stylus/blob/a94969e47d082e700b121c88b5d8e4c874b4d058/background/style-manager.js#L211
https://github.com/openstyles/stylus/blob/a94969e47d082e700b121c88b5d8e4c874b4d058/background/style-manager.js#L400

**Comment by tophf** [comment]
Turns out this PR introduced a bug, fixed in 1bd366be.
The non-usercss styles were unconditionally updated during the check, AFAICT.

I'd say it warrants releasing a new version ASAP, just in case.
@narcolepticinsomniac, @Mottie.

**Pull request merged**
