### PR TITLE
reduce usercss bubble to `U`

### PR DESCRIPTION
**Pull request by tophf**
Showing `usercss` was probably warranted at the beginning to introduce the feature but now it's just wasting space and attention so let's reduce it to just `U`:

image

### CODE REVIEW

**Comment by tophf** [comment]
What about switching to sliders?

image

**Comment by dnknn** [comment]
Is it better to put `U` after the style name position?

> What about switching to sliders?

I personally think that for the manager, the checkbox is more appropriate and clearer,  sliders are not suitable.

**Comment by tophf** [comment]
@dnknn I've seen your sense of aesthetics in the way you format your messages and in your gifs so I'm ignoring that.

**Comment by narcolepticinsomniac** [comment]
> let's reduce it to just `U`

I went with `UC` in my compact layout. Might be a little a little more obvious as an acronym, but I suppose either works. Not sure if we shouldn't just leave them trailing style names, as they were. If we're going to move em, they look a little squished where they are currently.

> What about switching to sliders?

I'm not opposed to the idea in general, but if we went with sliders, I'd suggest more understated icons. Perhaps something more like Google's, at the bottom of the page [here](https://material.io/resources/icons/?style=twotone).

**Comment by tophf** [comment]
image
I wouldn't be able to tell the on/off difference when they're small. Surely we could tweak/tint it but I already like our sliders because they're airy and clean.

Here's a less cramped and more subdued version:

image

**Comment by tophf** [comment]
As for the checkboxes, they'll be shown additionally on demand when we implement selective export and group management actions.

**Comment by narcolepticinsomniac** [comment]
Slider tweaks look pretty damn good. Judging strictly by the screenshot, I'd be cool with those. Spacing for `U` looks good too, but I wonder if that's because there's only one traditional style. If, like me, usercss styles are only a small percentage of installed styles, I'm a little concerned the spacing will look odd.

**Comment by dnknn** [comment]
> I wouldn't be able to tell the on/off difference when they're small.

For the manager page, most people rarely toggle on/off here, right? So I think the toggle of the manager is mainly for viewing, not for operation.
This is also the biggest reason why I think slider ON/OFF is not ideal for the list of manager, but slider ON/OFF is very ideal when used in UserCSS-configuration-UI (`@var checkbox`), 
anyway, it doesn't matter, as long as can **easily/obviously** distinguish between `ON` and `OFF` visuals, it is not a big problem.


What you saw before was semi-finished, I recently completed CSS-DIY ( It's completely my personal flavor , so CSS-DIY completely based on the personal flavor based on the familiarity with Stylus use, not suitable for most people's flavors.)
<details>
<summary>I use CSS to DIY for manager list</summary>



</details>


<details>
<summary>I use CSS to DIY for Popup list: `disabled` is border-radius:99%; </summary>




</details>

**Comment by tophf** [comment]
@dnknn, it's the other way around: the checkboxes are used to indicate targets for an action.

**Comment by dnknn** [comment]
@tophf But looking at https://github.com/openstyles/stylus/pull/1117#issuecomment-731045832 seems to feel good, fresh and simple!  but you should tweak/tint a little bit to clearly distinguish ON and OFF.

**Comment by tophf** [comment]
Just stop already, will you.

**Comment by tophf** [comment]
The clickable area of the slider is bigger now | The `UC` label is dimmed even more
-|-
image | image

@narcolepticinsomniac do you think we should keep the old `checkmate` element in a hidden state? I'd rather not because that would mean there'll be two `input` elements to maintain but it's doable.

**Comment by narcolepticinsomniac** [comment]
>do you think we should keep the old checkmate element in a hidden state

Probably a good idea since people hate change. Always easier if you can tell them their preference is still available with minor tweaking.

Changes LGTM though. Still kinda getting used to it, but it feels like an improvement.

While testing, I'm noticing a couple unrelated things. Applies-to ellipses could use some padding/space underneath, and they don't appear to collapse rules anymore, once they're expanded. I see you've added search filters sometime recently, which is cool, but why wouldn't 'all' be the default?

**Comment by narcolepticinsomniac** [comment]
> darker 'on' background

Heh, I was thinking about suggesting this. A little more contrast does look better.

> `.style-name:hover .onoffswitch input:checked + span`

Toggling enabled state is not the `.style-name` action. Should be `.onoffswitch:hover input:checked + span` if you wanna change the background-color, and transition should match box-shadow.

**Comment by tophf** [comment]
Thing is, when the name is hovered its background becomes greenish so the slider looks "off", as though it's gray tinted by the hover overlay.

**Comment by narcolepticinsomniac** [comment]
>as though it's gray tinted by the hover overlay

Not seeing it. It'd be an optical illusion anyway, since the pseudo is underneath. Might help to switch enabled box-shadows to dark cyan. 

If a toggle changes styling on hover, I'd assume that's the action, and it's not.

**Comment by tophf** [comment]
Fixed by switching to a more saturated background with .5 alpha so it blends with the overlay and retains its dominance.

Added an option to use sliders.
Placed it in a global `UI` group because the popup will have them too I guess.

**Comment by narcolepticinsomniac** [comment]
Might wanna darken `UC` a bit as well, maybe .5 transparency. Apparently, margins are condensed in compact, which was probably me. Anyway, it doesn't work well for sliders.

Still wondering why search now defaults to metadata. Seems like an odd choice, when it's always searched everything, IIRC.

**Comment by tophf** [comment]
> Might wanna darken UC a bit as well, maybe .5 transparency

Increased to .35, why do we want to indicate it in the first place? Why not remove the bubble and the filter?

> compact [...] doesn't work well for sliders

Fixed.

> Applies-to ellipses could use some padding/space underneath

That would increase the height, which I didn't want when I implemented it. A better solution might be moving the expander some place else, maybe a bigger square button with `>>` label or smth shown on hover, idk.

>don't appear to collapse rules anymore, once they're expanded

Fixed.

>why wouldn't 'all' be the default?

Because people arguably use the search to find a style by something they remember in its name and other meta stuff like applicable targets or description, so incremental search would produce a lot of irrelevant matches when the typed characters match a base64-encoded `data` image or some background image url or a CSS keyword.

**Comment by narcolepticinsomniac** [comment]
> why do we want to indicate it in the first place?

I thought that was all you. It's somewhat useful IME, since I only have a handful, and it makes it easier to find one quickly when I need to test something. I never understood the point of the 'disabled' pseudo, since they look pretty obvious via styling, to me. IIRC, I said so at the time, but you seemed to like them, and it wasn't worth arguing about.

> arguably use the search to find a style by something they remember in its name

I don't use it much, but when I have, searching everything is what I've come to expect as the default. If you say it's better this way, I guess I'll take your word for it.

**Comment by tophf** [comment]
I guess I wanted to keep the historical behavior of Stylish-for-Chrome which showed `disabled` after the names. Nowadays though, the original extension is trash not worth even remembering so we can remove the redundant stuff like this.

**Comment by dnknn** [comment]
> Because people arguably use the search to find a style by something they remember in its name and other meta stuff like applicable targets or description,

> My fault for not implementing the metadata search earlier...


@tophf  Can you make `metadata` also include search for CSS `comment` content ?  WDYT？
`/*comment*/` and  @preprocessor stylus  `//comment`  

I think it will maximize the usefulness of metadata as a default! personally think there is no negative effect.
Because CSS comments are custom text, people can remember most specific comments, generally not produce a lot of irrelevant matches .

<details>
<summary>Current inclusions of metadata</summary>

searches in names, "applies to" specifiers, installation URL, update URL, and the entire metadata block for usercss styles.

</details>

**Comment by dnknn** [comment]
> Because people arguably use the search to find a style by something they remember in its name and other meta stuff like applicable targets or description,

> My fault for not implementing the metadata search earlier...


@tophf  Can you make `metadata` also include search for CSS `comment` content ?  WDYT？
`/*comment*/` and  @preprocessor stylus  `//comment`  

I think it will maximize the usefulness of metadata as a default! personally think there is no negative effect.
Because CSS comments are custom text, people can remember most specific comments, generally not produce a lot of irrelevant matches .

<details>
<summary>Current inclusions of metadata</summary>

searches in names, "applies to" specifiers, installation URL, update URL, and the entire metadata block for usercss styles.

</details>

---

In addition, No problem with remove 'disabled' bubble, But very curious that why [`remove 'usercss' bubble&filter`](https://github.com/openstyles/stylus/pull/1117/commits/e0a53b5156a667eccd3bccf94f337c6f7daf8706) ?

I think UserCSS filtering and list display UserCSS logo are very useful basic functions, so request not to remove them...-_-

**Comment by tophf** [comment]
Comments are part of code so no, metadata won't include them.

> I think UserCSS filtering and list display UserCSS logo are very useful basic functions

How is it useful?

**Comment by dnknn** [comment]
> How is it useful?

Generally, classic-CSS is mainly used, and UserCSS is used as auxiliary (when custom configuration is required)
1) Quickly filter out UserCSS, UserCSS is less and classic-CSS is more.
2) UserCSS logo used to quickly distinguish.

**Comment by tophf** [comment]
>Generally, classic-CSS is mainly used, and UserCSS is used as auxiliary (when custom configuration is required)

Who decided what's main and what's auxiliary? There's no such distinction.

>Quickly filter out UserCSS, UserCSS is less and classic-CSS is more.

Doesn't make any sense to me.

>UserCSS logo used to quickly distinguish
Note that both these features can be replicated via CSS.

**Comment by tophf** [comment]
Also note that both the logo and filtering by usercss can be replicated via CSS, which is pretty trivial.

**Comment by dnknn** [comment]
Otherwise, wait for what @narcolepticinsomniac  has to say about [`remove 'usercss' bubble&filter`](https://github.com/openstyles/stylus/pull/1117/commits/e0a53b5156a667eccd3bccf94f337c6f7daf8706)

**Comment by tophf** [comment]
That was the plan all along so just don't butt in.

**Comment by tophf** [comment]
It occurred to me there could be many people who misuse the usercss bubble as a tag so we'll keep it until proper tagging is implemented. The `disabled` bubble stays removed. If someone wants it they can write a style themselves or ask someone to do it, there are just a few lines.

**Comment by tophf** [comment]
So I guess this PR is complete then.

**Comment by narcolepticinsomniac** [comment]
A few issues:

* Disabled popup entry contents should not be opaque.

* Slider knob pseudos cannot take up over 60% of the slider's width. It looks weird. Switching to 7px looks fine to me in both the popup and manager. If not, they need some other kinda tweaking.

* Popup entry actions _are_ actually toggle, so styling sliders on `.style-name:hover` in terms of box-shadow would be advisable, if not expected.

* In the popup, the entire `.style-name` element should have the right-click to edit event. Removing pointer-events from `.onoffswitch` should be fine. Also, the 'iframe' indicator shouldn't interfere with right-click.

* The popup is not right on CWS. Now shows 'Could not communicate'. Arguably, it hasn't been great since iframe detection was added to the popup, since styles are injected in iframes there. Ideally, there'd be the restricted message, while still listing active iframe styles.

**Comment by tophf** [comment]
Added the fixes in #1123.

**Comment by narcolepticinsomniac** [comment]
Just getting around to looking at accommodating sliders in my dark style, and I'm a little concerned that our "airy and clean" sliders don't adapt very well at all. In order to achieve the same kinda subtle charm they have in the default theme, authors are gonna need to experiment quite a bit with tweaking a few properties, IMO, and even then, I'm not sure it translates.

Not to mention the fact that many won't bother with anything other than background color, and they'll probably wind up looking pretty sloppy in most dark styles. If we could come up with some decent svg icons, most styles will likely accommodate them decently by default, and much better with minor tweaking.

**Comment by tophf** [comment]
Not gonna work on svg icons ever again, probably :D

**Comment by tophf** [comment]
BTW, regarding icons, our 19px `light` icon is incorrectly 16px...

**Comment by narcolepticinsomniac** [comment]
Not gonna work on browser icons ever again, probably :D

Seriously though, I wonder if it's an oversight, or if we did in on purpose. Doesn't ring any bells, so probably not. It's just Vivaldi, and perhaps some other random forks which use them, right?

I guess we'd need to sift through that godforsaken icon thread to see if there even were 19px made correctly for light icons. IIRC, I did the 19px, which basically just have wider borders, but I don't recall much beyond that.

**Comment by tophf** [comment]
Same thoughts here, not gonna touch it.

**Comment by tophf** [comment]
Exposing the slider's colors via css variables might be a much simpler solution. There's just a few colors and we can even probably reduce it by deduplicate the similar ones.

**Comment by narcolepticinsomniac** [comment]
> a much simpler solution

That always SGTM. One of the main issues for compatibility is gonna be that the lack of definition doesn't work well, particularly at the bottom. There's some weird border code: `border: 0 solid #E3E3E3;` which accomplishes nothing. Probably better off with a 1px inset box-shadow to accentuate the shape/definition.

> I guess we'd need to sift through that godforsaken icon thread

The tail end of that thread is us coming to the realization that they actually prefer down-scaling 38px, so those were the ones which were optimized. Seems like we intended to remove 19px altogether at the time, and simply forgot.

**Comment by narcolepticinsomniac** [comment]
> Exposing the slider's colors via css variables

Done in this [this version](https://github.com/openstyles/stylus/files/5609175/stylus-master.zip). @tophf WDYT?

> a much simpler solution

Nah, I decided I needed to give myself a headache today instead, so I hooked up some svg sliders. I spent an absurd amount of time editing and tweaking them, so here's hoping you don't hate em. I think you might dig em though, they're fairly similar.

**Comment by tophf** [comment]
I don't like them as they look heavier. The reason I suggested using sliders is because they were airy and unobtrusive in the default light theme. Can you mimic the current look exactly using this svg?

**Comment by narcolepticinsomniac** [comment]
> mimic the current look exactly

I was going for similar, but more solid, with higher contrast, for sure. I get what you're saying, and they could be made more subtle, but I think there's a real downside to it, which you're no taking into account. the "airy" ones do look good, but really only  in the default theme, and even then, only if you've got a decent screen and normal resolution.

They fall apart big time on my TV screen. I can barely even tell what disabled sliders are supposed to be. Using only subtle box shadow for the shape doesn't work in dark themes either, unless you overdo it, which loses all of the charm.

**Comment by tophf** [comment]
Damn, I hate this UI stuff so I suppose we'll just revert back to the checkboxes.

**Comment by narcolepticinsomniac** [comment]
I don't feel like arguing about it right now either. =) We could always have more than two options.

**Comment by tophf** [comment]
No, that'd be too weird for something so trivial.

**Comment by narcolepticinsomniac** [comment]
> No, that'd be too weird for something so trivial.

No.

Does it work when I say it to you? I'm guessing it goes over about as well as it does when you say it to me.

I don't even particularly disagree, if you're referring to complicating the pref. Adding an extra slider alternative would be intended for theming, so it'd be more useful as a CSS override than a pref anyway.

I like the sliders. I like the box-shadow sliders. I like the svg sliders. In the default UI, I find either preferable to checkboxes. This mindset that if they aren't exactly the way you want them, then it's a terrible idea, which needs to be scrapped altogether, is such a shortsighted take on it.

Fact is, I'm fine with them being exactly the way you want them. I think they work well in the default UI, for the most part. I think they're problematic in other scenarios, which I don't need to reiterate. I can rework it so it defaults to box-shadow sliders, and svg sliders are hidden by default, but there's no harm in adding them so they're available for theming.

**Comment by tophf** [comment]
Thing is, I simply forgot that UI is complicated with different themes, resolutions, and whatnot. I really don't want to work on that which is why I'm fine with taking the easy way out - just revert it.

**Comment by narcolepticinsomniac** [comment]
What I'm suggesting is just as easy. You like the CSS sliders, and so do I. They're fine for the default. I firmly believe the svg sliders will work far better for theming, and they're already made, so making them available for userstyles is a no-brainer.

Whatever you think about the svg sliders, they're fairly unique. I used Google's and separated the knob from the border, and added a shadow filter to it. A few easily interpreted variables, and the fact that they're more solid/substantial by nature, should make them simple as hell to style well in any scenario.

**Comment by tophf** [comment]
Okay, I'll try to elaborate. When I saw your version it immediately impressed me as darker, heavier, flatter, with a really dominant border. There's also less difference between the states in the light theme at a glance (should be fine in the dark theme though).

image image

The amount of changes was surprising, I didn't expect my variant to be so lacking as to need all these changes, but then I remembered how long it may take to find common ground when UI is concerned especially since I'm not using dark themes anymore so I can't care about them and you don't care about the light themes so I guess it'll be hard to settle on something.

**Comment by narcolepticinsomniac** [comment]
I'm not looking for a compromise here. Once your mind's mad up about something, me trying to convince you otherwise is unlikely to end well. I pick my battles, and this ain't one of em.

The CSS sliders will be the sliders. All I'm suggesting now, is that we add the svg sliders alongside them - hidden - so they're available for theming.

**Comment by tophf** [comment]
I'm just trying to avoid having any battles at all about something that's inherently opinionated. Since you seem to really like the sliders I guess we can make a selector in options like the one we use for the main icon because I don't want to inflate the DOM tree with the extra unused stuff. There'll be three rows (checkbox, css slider, svg slider), each with a radio button and two example icons for the on/off states.

**Comment by narcolepticinsomniac** [comment]
> I guess we can make a selector in options

That'd be fine by me, but it's not what I was suggesting. I guess I'm either somehow not getting the point across, or you think a pref is warranted if we add them. To me, they'd be fine as a theming easter egg. Anyone who goes to inspect can find them and check them out.

As long as they're available in some form or fashion, pref or no pref, doesn't really matter to me.

**Comment by tophf** [comment]
I understood, I just don't want to add hidden unused stuff into DOM in order to keep it fast and not set a bad precedent so we don't end up with 10 hidden easter eggs per each style entry.

**Comment by tophf** [comment]
@narcolepticinsomniac my body is ready to tackle the sliders and I started doing it but seeing that both our variants need quite a complex CSS to make them work I want to explore a third option - a monochrome primitive slider similar to the one you suggested initially or simpler. The goal is that it should be trivial to customize and it should work with any (or most) custom themes out of the box.

Maybe even a black one (or rather `currentColor` so it reuses the font color) like Violentmonkey's:

image

**Comment by narcolepticinsomniac** [comment]
> a monochrome primitive slider

Not a big fan of that screenshot. I kinda like the green/grey.

> similar to the one you suggested initially

The one I suggested initially is the one I used. Google's two-toned material sliders, edited to separate the knob and borders, so I guess, technically three-toned.

You've got the side by side comparison a few comments up, and if your major issue is the coloring being more pronounced, we could go more subtle.

Otherwise, they're slightly more oval, which is a good thing IMO. The knob's slightly smaller, and the border's more solid, both of which solve the issue of the lack of definition which can result from shaping them almost entirely with box-shadow, particularly how that approach translates in a dark theme.

> both our variants need quite a complex CSS

Neither's all that complex. The svg icons have a few variables hooked up, and the same could easily be done for CSS sliders. Major difference, as far as I'm concerned, is that with the svg icons, it's just a matter of finding the right contrast to work in any theme. I don't think box-shadow adapts all that well.

I'm not looking to rehash the debate. Those CSS sliders are pretty charming in the default, but they fall flat in themes. The svg will work across the board, so if they could be tweaked to something you're cool with, that'd be ideal. If not, we can make em optional.

**Comment by tophf** [comment]
Turns out my variant can be rewritten to use our built-in rectangular checker SVG without any changes in HTML/SVG.

<details><summary>CSS</summary>

```css
#stylus .entry .checkmate {
  display: inline-block;
  width: 21px;
  height: 11px ;
  margin: 0 1ex 0 0;
  pointer-events: none;
  vertical-align: unset;
  user-select: none;
  -moz-user-select: none;
}
#stylus .entry .checkmate svg {
  display: block;
  width: 100%;
  height: 100%;
  margin: 0;
  border-radius: 1em;
  fill: transparent;
  background-color: rgba(128, 128, 128, .2);
  box-shadow: inset 1px 1px 2px rgba(0, 0, 0, .5);
  transition: box-shadow .25s;
  pointer-events: none;
}
#stylus .entry .checkmate input:checked + svg {
  background-color: hsla(180, 50%, 40%, .5);
}
#stylus .entry .checkmate:hover svg {
  box-shadow: inset 1px 1px 3px rgba(0, 0, 0, .8);
}
#stylus .entry .checkmate input {
  width: 100%;
  cursor: pointer;
  border: none;
  background-color: transparent;
}
#stylus .entry .checkmate::after {
  content: "";
  display: block;
  position: absolute;
  top: 0;
  right: auto;
  bottom: 0;
  width: 7px;
  height: 7px;
  margin: auto;
  border-radius: 1em;
  background-color: #fff;
  box-shadow: 1px 2px 3px rgba(0, 0, 0, 0.3);
}
#stylus .entry.disabled .checkmate::after {
  left: 2px;
}
#stylus .entry.enabled .checkmate::after {
  right: 2px;
  background-color: #fff;
  box-shadow: 1px 2px 3px rgba(0, 0, 0, 0.3);
}
```

</details>

So if you can tweak my draft to your liking (or make your own one) there will be no need for this option at all and we'll just publish our userstyles so they'll be available in the inline search. Maybe add them to our Wiki along with the links to some known themes for Stylus that aren't listed on USO (and USO-archive).

**Comment by narcolepticinsomniac** [comment]
> Turns out my variant can be rewritten to use our built-in rectangular checker

It's more clever CSS than how it was originally written, but of course you could utilize existing checkbox elements for CSS sliders. They're mostly CSS checkboxes to begin with, so it's basically just changing shapes.

> there will be no need for this option at all and we'll just publish our userstyles

This is where you lost me. Sliders are a nice, and at least slightly more modern looking change for the default IMO. That was the goal here - changing the default - not making a userstyle. The option was for users who hate change, to be able to revert to classic checkboxes, if they want.

> if you can tweak my draft to your liking

I prefer the svgs for styling purposes, but practically any styling can be mimicked with CSS. The main thing needed for ease of theming, would also improve the default - better definition. 1px solid border/box shadow on sliders, and some super transparent grey background on disabled sliders. Backgrounds/borders should be variables, 

A little proper definition, with variables for theming, and we'll abandon the svg option. Sliders should be the default though, and we _should_ provide an option to revert, since we usually do, because we're cool like that. =) I also appreciated when sliders had larger clickable areas, FWIW.

**Comment by tophf** [comment]
The reason I no longer want to include the sliders in the default theme is that I was reminded by 8 how much simpler our code would be if we use a modern UI framework so I think we should postpone changing the visuals if the change is serious enough to warrant an option to revert it.

>sliders had larger clickable areas,

Yep, forgot about it. I've updated the code above so now it's arguably a perfect replica.

**Comment by narcolepticinsomniac** [comment]
> how much simpler our code would be if we use a modern UI framework 

Huh? Since when are you interested in a UI framework? At this point, wouldn't switching to one properly be a pretty massive undertaking? We shouldn't add trivial features till we implement something which has hardly ever even been discussed?

If we tweak CSS sliders so they work better with themes, and we're utilizing existing elements, then we're literally talking about a pref which toggles a class, like countless others.

> so I think we should postpone changing the visuals

Well, we're long overdue to start gearing up for a stable update, so it shouldn't be prolonged for something so insignificant. We can certainly put it off, I just don't understand how adding a pref, to toggle a class, to change the shapes of checkboxes, is somehow contingent on reworking the entire UI.

**Comment by tophf** [comment]
I wanted to use a UI framework in Stylus long time ago. We'll probably need to rewrite a lot to make the extension work with the retarded ManifestV3 so might as well do the UI.

Meanwhile we can certainly add any trivial features that don't need an option to toggle.

As for sliders, I want to remove them and the option because the feature can be trivially implemented as a userstyle.

**Comment by narcolepticinsomniac** [comment]
> We'll probably need to rewrite a lot to make the extension work with the retarded ManifestV3

Surely, you'd know better than me, but... really? I thought the major change was `webRequestBlocking`, which doesn't affect us much at all.

> Meanwhile we can certainly add any trivial features that don't need an option to toggle.

It certainly doesn't need it. It was more of an afterthought, because we do usually provide options to revert. Not sure how that became some determining factor.

I don't follow the rationale, but if we agree sliders are nice change, and for some reason, a userstyle is preferable to adding a pref to revert, then why wouldn't we switch the default to sliders and make a classic checkbox userstyle?

IDK man. We can switch to sliders with no option to revert, or put it off. NBD either way.

**Comment by tophf** [comment]
ManifestV3 removes the background pages so we'll have to use a service worker which is essentially a severely downgraded background page, meaning we'd need workarounds. For example, updating userstyles from file:// won't work because `fetch` doesn't support this protocol (XMLHttpRequest does but it's not implemented in the service workers). As for webRequestBlocking its absence will break our instant inject and patchCSP. Right now there's no solution but maybe it'll be implemented in the future.

>  why wouldn't we switch the default to sliders and make a classic checkbox userstyle?

This might work, indeed, but does it require that someone comes up with a CSS that suits both light themes and dark themes?  For light themes I want the slider to be as airy as it is now because the checkboxes were originally inconspicuous.

The reason I don't want an option for such UI details is that it'd be like reinventing what's already possible via a configurable userstyle. It just occurred to me that a possible solution would be implementing an embedded protected userstyle for all of the UI and wire it to our config dialog to expose dozens of such small tweaks including the ones currently exposed in the manage/popup sections.

**Comment by narcolepticinsomniac** [comment]
> ManifestV3 removes the background pages

Holy hell. That has to be some kinda pipe-dream, and not a real thing they intend to do. Wouldn't that completely break the majority of existing extensions?

> does it require that someone comes up with a CSS that suits both light themes and dark themes

Of course. Darker themes require more definition than box-shadow, which fades to nothing at the bottom. If we're being honest, the default needs more definition as well, particularly disabled sliders, since they fade to the white background.

If I'm looking at em straight on, or the screen is above eye level, box shadow forms the shape fine. If my laptop is in my lap, and I'm looking down at a disabled slider at the bottom of the screen, they're barely recognizable.

Their backgrounds could be a transparent variable, for ease of theming, but they need some definition. "Airy" can't be so narrowly defined as to be cool from some angles, and practically invisible from others.

> an embedded protected userstyle for all of the UI

Solid idea.

We both prefer sliders. I imagine the vast majority of users will agree. Apparently, the only way you're okay with the change is if they're some narrowly defined, impractical version of "airy" you've set your mind to.

I have zero idea how the arguments against such a minor change devolved into UI frameworks, or ManifestV3. If the objective was to make it so convoluted that it's impossible not to wanna nope out of the discussion - mission accomplished.

Tweak em slightly, so their shapes aren't so fragile, and they're a cool little update most users will appreciate. Otherwise, let's gut em and move on.

**Comment by tophf** [comment]
> Wouldn't that completely break the majority of existing extensions?

Yes.

As for the sliders. I can't imagine how it looks on a display with such narrow viewing angles so I can't even test it and at the same time I can't accept the heavier version you've made as on my display it's like 10 times heavier than both the original checkboxes and my implementation. I could probably settle on a slightly darker version of my variant but now that it's extracted as a userstyle I no longer see the need to include it in the extension. Previously I thought it's impossible to implement via pure CSS which is why I wanted to implement this in the extension. I also don't see it as a definite improvement now that I know that it looks bad on certain displays. Let's do it later in that userstyle config and I'll revert the code for now.

**Comment by narcolepticinsomniac** [comment]
Right on. An embedded protected userstyle for all of the UI is a solid concept, which could eliminate all kinds of stupid bickering over little details. Definition properties could be transparent, with configs. Same goes for all kinds of similar disagreements. 

No rush, but LMK when you think the master is good to go, so we can pull the trigger. Too many cool features and fixes to keep dragging our feet.

**Pull request merged**
