### PR TITLE
Rewrite the build script

### PR DESCRIPTION
**Pull request by eight04**
Please fix the wording, grammar, etc.

### CODE REVIEW

**Comment by tophf** [comment]
Don't count on me 🤧

**Comment by tophf** [comment]
One thing though: it would make sense to produce a single bundle for each content script entry in manifest.json as well as the editor/manager pages which load tons of scripts, especially the editor. And minify them so they get parsed/compiled/loaded faster, the difference is often non-negligible.

**Comment by narcolepticinsomniac** [comment]
>One thing though...

This PR contains the changes specifically required to placate AMO reviewers. It needs to merged ASAP if we intend to resubmit by their arbitrary deadline, so if anyone wants to implement this suggestion beforehand, time is of the essence. Otherwise, we can put off any potential optimizations till the next release.

**Comment by narcolepticinsomniac** [comment]
@Mottie I thought you were gonna merge this?

**Comment by narcolepticinsomniac** [comment]
We've got bigger issues than onedrive in FF if this PR wasn't included in 1.5.8. This one was the whole reason we were rushing to get AMO an update.

I'm looking at the DM, and I thought I was pretty clear that this still needed to be merged. I just figured we'd wait as long as possible in case anyone wanted to hook up the optimization previously mentioned.

**Comment by eight04** [comment]
It will be a major refactoring to transfer to a modern code base. I suggest opening a new issue to discuss the tooling.

**Pull request merged**
