### PR TITLE
use color palette and enable a simple dark theme

### PR DESCRIPTION
**Pull request by tophf**
Turns out all dark themes for Stylus are incomplete and many of them break the layout. Many of them have a lot of code, which means maintaining them is a PITA. The underlying reason is that our CSS is inherently unfriendly due to the use of hardcoded colors. Each time we add a measly new color we're likely to break some or all userstyles.

This PR maps all our colors to a simple percent-based palette, except those that already look good in a dark theme, so assuming we diligently reuse this palette for new stuff the built-in dark theme will be automatically okay.

The theme switcher's default value is `system` now and it's moved up in the options. Explicit Dark/Light modes are added. The `never` mode is renamed to clarify that the style's dark/light option won't apply in this mode (a similar clarification is added to the style settings and installer when this mode is active).

image

The theme preference in style settings is reworked and rephrased.

image

image

image

The scrollbars are primitive, the same I made for Violentmonkey. I don't plan to improve them myself so it's up for grabs.

A few unused CSS rules were removed.

### CODE REVIEW

**Comment by tophf** [comment]
Simplified it a bit by converting the `!` modes into explicit global option's variants.

**Comment by narcolepticinsomniac** [comment]
Pretty damn good. 

Only a couple little CSS details I've noticed so far:

* filter selects should change bg color on label hover to match

* circles instead of arrows in scrollbar buttons is the work of the devil

Pref toggling has been erratic as I briefly tested a couple different browsers. Sometimes a reload was required, sometimes not. At one point, it reliable toggled the opposite of the expected theme when switching back and forth between light and dark.

**Comment by tophf** [comment]
> filter selects

I couldn't fix filter selects because browsers stupidly show the dropdown with white background unless I set the background on `select` itself. There's no CSS selector for the dropdown. I can set the background on `option` but there will be white parts around.

> circles

Fine by me. I couldn't draw triangles via CSS and didn't want to use a picture because it looks bad on retina displays.

> Pref toggling has been erratic

Welp, I need an exact sequence of actions to reproduce the problem...

> toggled the opposite of the expected theme

There was a mistake in options.html which reversed its `Dark` and `Light` options.

**Comment by narcolepticinsomniac** [comment]
> I couldn't draw triangles via CSS and didn't want to use a picture because it looks bad on retina displays.

Figured these might scale more decently, but I guess you'd need to confirm.

Also, CM and regular scrollbar corners needed to be accounted, and I took a lazy stab at filter selects. Only edited `global-dark.css`, so you can check the diff.

Noticed color-picker popups still need styling.

[global-dark.zip](https://github.com/openstyles/stylus/files/8074002/global-dark.zip)

**Comment by narcolepticinsomniac** [comment]
Forgot to mention, pref toggling seems fine now.

**Comment by narcolepticinsomniac** [comment]
Not sure exactly how you handled CM styling, but it looks pretty decent so far. Caret needs styling though. I used this in my style:

```
.CodeMirror.cm-s-default div.CodeMirror-cursor {
  border-left: 1px solid #fff!important;
}
```

**Comment by tophf** [comment]
Awesome!

**Comment by narcolepticinsomniac** [comment]
I duped `::-webkit-scrollbar-track-piece` in a copypasta. I didn't style color-pickers either, just noticed they weren't yet. I'll do em later if you want, but you may be more familiar with which variables you want used.

**Comment by tophf** [comment]
Our color picker guesses the theme automatically, it was bugged in this PR, fixed now.

**Comment by narcolepticinsomniac** [comment]
Should add FF scrollbar styling as well:

```
  * {
    scrollbar-color: var(--c70) var(--bg);
    scrollbar-width: auto;
  }
```

Search/replace dialog SVG icons have black hovers. 

Unrelated, but just noticed 'injection order' icon needs a rule which should probably be universal: 
`button:hover .svg-icon { fill: var(--fg)' }`

**Comment by tophf** [comment]
Modern FF (at least 91+) shows dark scrollbars automatically here so I guess you mean some very old version?

Fixed the hovers. As for the button's svg, I've used our standard button color for the icon so the icon doesn't change its color on hover because it's an integral part of the button.

**Comment by narcolepticinsomniac** [comment]
> I guess you mean some very old version

Pretty sure that's relatively new, in terms of supported versions. The color will blend better regardless, so it couldn't hurt.

**Comment by tophf** [comment]
Okay. BTW I've tried to mimic the layout of the standard mode scrollbars in Chrome, but I couldn't properly reduce the width of `-webkit-scrollbar-thumb` so its 2px border looks weird:

image

**Comment by narcolepticinsomniac** [comment]
Maybe inset box-shadow?

Pretty decent imitation, for the most part. I'm fine with the resizing, but I liked them either way.

`::-webkit-scrollbar-track-piece` bg colors are definitely more pronounced. Not necessarily a bad thing, but they could start darker, and have more subtle hover/active states.

**Comment by tophf** [comment]
SVG clinched it, I think, but I had to define hover/active with an svg too because `fill` wouldn't work.

**Comment by narcolepticinsomniac** [comment]
Came across an issue I can only repro reliably in outdated Cent, which I still use for casual browsing. Switching from 'light' to 'dark' doesn't appear to convey the message to the popup or edit pages:

cent-popup

A few other little details I've noticed:

* beautify dialog selects have no backgrounds

* shortcut explanation in popup has black text

* disable-all label/checkbox hover doesn't exactly work well in the dark theme

**Comment by tophf** [comment]
Fixed the colors except disableAll, which I deemed passable although it's slightly weird :-)
Cent is working correctly for me, the portable from the site, so maybe there's a setting you've customized?

**Comment by narcolepticinsomniac** [comment]
Hmm, IDK. You can tell from the screenshot, that's fresh side-load install. I don't really use any settings which I'd suspect being related. As long as it's just my setup, I guess it's NBD.

**Comment by tophf** [comment]
Are there any suspicious messages in devtools console for the tab/popup/background?

**Comment by narcolepticinsomniac** [comment]
Nope, nothing anywhere.

Maybe 'dark mode policy' setting has some affect? Mine's enabled, which seems to work fine as the system preference.

**Comment by tophf** [comment]
Ah, indeed, I can see it too.

**Comment by tophf** [comment]
Fixed it.

**Comment by narcolepticinsomniac** [comment]
Yep, nice.

**Comment by narcolepticinsomniac** [comment]
> I've tried to mimic the layout of the standard mode scrollbars in Chrome

> `::-webkit-scrollbar-track-piece` bg colors are definitely more pronounced. Not necessarily a bad thing, but they could start darker, and have more subtle hover/active states.

I don't particularly care how closely we do, or don't mimic the default, but this is one detail which is significantly overly emphasized. Hover and active track-piece states are hardly discernible in the default.

While I actually appreciate the noticeable distinction, I think they're too light to begin with, and the states aren't subtle enough. Hovers are almost as bright as the thumb, and an active track-piece is pretty much the same bg color as thumbs.

**Comment by tophf** [comment]
Our colors are currently much more subtle than what I have here in the light mode by default in Chrome:

**Comment by narcolepticinsomniac** [comment]
That's the thumb. Track pieces are the areas above and below. In the dark theme, their states are too pronounced.

**Comment by tophf** [comment]
Ah, ok, I'll fix it.

**Pull request merged**
