### PR TITLE
Editor fixes

### PR DESCRIPTION
**Pull request by tophf**
Turns out our sectioned editor's initialization phase was appallingly slow for ~2 years for styles that had dozens of sections. And as a workaround for this problem, all sections were hidden so the editor was unusable for a second (or more) on such styles. Now the first visible sections are shown instantly as they did when I implemented it back then.

A few cosmetic fixes:

* usercss mode: restored the full height of the code element (necessary for micro styles) which was lost somehow a while ago
* usercss mode: removed margins/padding around the code element in the responsive/narrow layout

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
This seems great.

>as a workaround for this problem, all sections were hidden so the editor was unusable for a second

That was actually to wait for editor resizing to finish - apparently because sectioned editors loaded so poorly in general. Pretty damn fast now though.

>autofocus when add/clone button is clicked

Didn't know I wanted that, but I do. Only minor issue is position. If the new editor's created off screen, it's pushed up by focus, but if a tiny sliver is visible, it's not. Might be cool to auto-focus applies-to field when they're added as well.


Now that I'm over-analyzing sectioned editor loading with multi-sectioned, monster styles, a couple other little details jump out. Save button should have a disabled attribute in the html by default, as it occasionally blinks in and out. 'Remove section' buttons are slow, and sometimes also the name input value, causing the `:invalid` styling to flash briefly.

**Comment by tophf** [comment]
✔️ positioning
✔️ autofocus on the text input as I thought we don't often change the type selector
✔️ save button is disabled

Name input validation flashing is fixed in the other PR for custom name.

>'Remove section' buttons are slow

Couldn't repro.

**Comment by tophf** [comment]
✔️ use standard CSS for a focused CodeMirror outline instead of the ring-color hack as it became ugly in new Chrome

**Comment by tophf** [comment]
Merging since the PR for custom names depends on some of the changes. If "'Remove section' buttons are slow" is still reproducible, gonna fix it separately.

**Pull request merged**
