### PR TITLE
Open Source compliance: un-minify less.js

### PR DESCRIPTION
**Pull request by onlyjob**
Minified javascripts should be avoided. Effectively minified code is equivalent of pre-compiled binary -- un-readable, non-modifiable and non-distributable in [Debian](https://debian.org).  
Also it is a bad practice to commit (pre-built) binaries to VCS. 

Availability of source code is a foundation of Open Source. Let's make sure that dependency libraries are (re-)distributed in source form (or at least with sources).

Read more in https://wiki.debian.org/onlyjob/no-minification

Thanks.

### CODE REVIEW

**Comment by tophf** [comment]
Nope. This is not applicable to the web-based technology stack used in extensions. Minified code is always used for performance. The minified LESS library we use is the official distribution: https://github.com/less/less.js/tree/master/dist - you can produce the exact file by running the official build script in the official repo.

**Comment by Mottie** [comment]
Also, please check the readme file added to each vendor folder. In this case it's https://github.com/openstyles/stylus/tree/master/vendor/less.

**Comment by onlyjob** [comment]
Still, distributing only minified version is bad. At least lets distribute them with sources?

I have a feeling you don't understand the problem at all, @tophf. :(
Open source compliance is very much applicable _"to the web-based technology stack used in extensions"_.

We have a practical problem with packaging of this extension for Debian due to lack of sources. You can't expect user to search for sources somewhere in the internet as resources may be unavailable.

**Comment by tophf** [comment]
Why should we complicate our lives (we are simply users who maintain Stylus) and compromise performance for abstract unrelated rules set somewhere else?

**Comment by onlyjob** [comment]
You don't have to compromise performance - please don't mix two different issues.

You can use minified versions if you wish, _as long as sources are included_.

Distributing just binaries is an abomination of Open Source idea. Always distribute binaries with sources, that's not hard.

You are wrong about writing simple script to replace minified files with unminified ones. That may not be the goal but unless sources are included, that script would have to download from different places in the internet and one can not do that from secure offline build environment.

> why only less.js

Because one has to begin somewhere and it would not be feasible to do larger work without testing your sanity first. Once again, it is not necessary to replace minified files with uncompressed ones - it is just my preference and best practice to keep binaries away from Vcs.
You can easily minify all .js files on build with simple script but not vice versa.

Would you be willing to merge if I modify this pull request with _adding_ unminified version of `less.js` along pre-minified one without replacing it?

Everybody should care about Debian as it is the world's most important universal free operating system.

**Comment by tophf** [comment]
I don't see any benefits for us.
This topic starts to seem insane and it definitely is getting annoying so I'm locking it.

**Comment by narcolepticinsomniac** [comment]
I'd just like to interject for moment. What you're refering to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.

Many computer users run a modified version of the GNU system every day, without realizing it. Through a peculiar turn of events, the version of GNU which is widely used today is often called Linux, and many of its users are not aware that it is basically the GNU system, developed by the GNU Project.

There really is a Linux, and these people are using it, but it is just a part of the system they use. Linux is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part of an operating system, but useless by itself; it can only function in the context of a complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called Linux distributions are really distributions of GNU/Linux!

**Pull request closed without merging**
