### PR TITLE
Fix appearance of non-disabled elements

### PR DESCRIPTION
**Pull request by Mottie**
Fixed:

* The all action buttons and external link (old UI), and checkbox (new UI) are now fully opaque when disabled.
* Disabled tag is fully opaque.
* <del>Added `#fee` background color to disabled entries to better visualize disabled entries.</del>

### CODE REVIEW

**Comment by tophf** [comment]
I definitely hate the red color.
@narcolepticinsomniac?

**Comment by tophf** [comment]
Although I do acknowledge current dimming is easy to confuse with the alternate coloring, but for me it was never a problem.

**Comment by Mottie** [comment]
I didn't like the red background color either, but I'd like it to be a different color from the zebra striping and hover color.

**Comment by narcolepticinsomniac** [comment]
Pink isn't a good look. `hsla(0,0%,0%,.1)` looks decent to me. We've tried a lot of different things for `disabled`. Been a while since I really looked at the default. It's pretty decent, but could use a little background differentiation. 

Also noticed an overflow issue with super long "applies to" rules:

overflow

**Comment by tophf** [comment]
Both background colors **EMPHASIZE** the disabled entry so it contradicts the goal of disabling.

**Comment by tophf** [comment]
I'd simply fade the disabled entry's text more.

**Comment by narcolepticinsomniac** [comment]
>EMPHASIZE
 
That's the catch 22. The more you differentiate, the more it sticks out. You want it to be obvious, but not so obvious that you're drawing attention to it. Probably why we have the same debate every so often. I don't really care. I just hated the pink, so if we were gonna give it a different background, figured i'd suggest something less pink.

**Comment by tophf** [comment]
We can keep the current colors, just make the label non-bold so it doesn't look almost the same:

```css
.disabled .style-name-link {
  font-weight: normal;
}
```

Now it doesn't stick out and doesn't look the same.

**Comment by MechaLynx** [comment]
Perhaps just do it like Violentmonkey does: 

2017-11-28 11_54_40-58 0-win-x86-32 _ 20171123161455 violentmonkey - firefox developer edition

High contrast is enabled (black on white), low contrast is disabled (grey on grey). Red/pink is semantic, as if something's wrong, but grey implies disabled. It also hints to userstyle authors that want to style Stylus on how to handle it, because it doesn't use a hue to convey the state.

**Comment by Mottie** [comment]
I removed the pink and made the font weight normal:

Before (new UI)



After (new UI)



It's a subtle difference, but at least the disabled tag isn't faded. 

In the old UI, you can now tell all the action buttons are still clickable

Before (old UI)



After (old UI)

**Comment by tophf** [comment]
> like Violentmonkey does:

It EMPHASIZES the disabled elements.

>same approach the browsers have for disabled extensions

Chrome just fades the opacity/color slightly like we did. It doesn't add a background color.

---

I like the normal font approach (obviously).

In the old UI I'm not so sure about the actions. I understand the new look is semantically correct, but whenever I disable a style it means I don't want it for the time being and I don't want its stuff being the same color. am I the only one?

**Comment by tophf** [comment]
I'm really reluctant to changing something that worked for years and raised no objections so what about restoring the button colors only when the `.entry` is hovered?

**Comment by Mottie** [comment]
Eh, nevermind

**Comment by tophf** [comment]
I'll do it myself then :-)
The issue is legit.

**Comment by tophf** [comment]
Merged as 56fb1c2f93150de525c14f8d4df557a6f9b3e779 with a followup I mentioned.

**Comment by narcolepticinsomniac** [comment]
@tophf I see you hooked up a max-width for "applies to" rules, but it's still a little too long:

overflow

Btw, probably not a popular opinion here, but I really hate variables.

**Comment by narcolepticinsomniac** [comment]
Overflow is caused by max-length "applies to" plus max-character style name before line-break, plus "disabled" pseudo-element being added:

**Comment by tophf** [comment]
Can you fix it? Without rewriting the entire thing, that is.

**Comment by narcolepticinsomniac** [comment]
Didn't really look at the code, but I'd like to think I can fix any CSS. If you tie my hands in regards to rewriting the entire stylesheet, that could throw a wrench in the works. I'll look at it tonight if you don't. Probably something simple.

**Comment by narcolepticinsomniac** [comment]
Finally figured out what causes overflow. I was so preoccupied with figuring out what that calc wasn't accounting for that I missed the obvious. Our CSS doesn't account for long strings in `.style-name`. Test style: [overflow-test.zip](https://github.com/openstyles/stylus/files/1539704/overflow-test.zip)

We use `overflow-wrap: break-word;`, which is good enough in most cases, but not good enough to keep the layout completely responsive. I imagine it has a higher probability of occurring on certain lower resolutions.

There are no great solutions, particularly for this layout. Only one that's really plausible is the same thing we do for "applies-to" rules with max-width and ellipsis. `word-break: break all;` works, but it's a sledgehammer, and it makes a mess of things, as always. Never seen hyphens work cross-browser successfully either.

**Comment by tophf** [comment]
I can try the same js hack currently used for editor options.

**Comment by tophf** [comment]
Found a much better method: a soft break is inserted every 10 characters in all localizable strings and in style names on the manage page.

**Comment by Mottie** [comment]
You mean like a soft hyphen (`&shy;`)?

**Comment by tophf** [comment]
Yep.

**Comment by narcolepticinsomniac** [comment]
Overflow js LGTM. Well done!

**Pull request closed without merging**
