### PR TITLE
support freestyler.ws

### PR DESCRIPTION
**Pull request by tophf**
Since USO devs are evidently determined to keep the site crippled forever I started working on #65 to support freestyler.ws.

- [x] install style button
- [x] open style manager button
- [x] find styles links
  ...became images; open for discussion.
- [x] customize style
  ...and warn if locally edited
- [x] uninstall style
- [x] auto-updater support
- [x] update style button
- [ ] ~tweak style parameters in our manager~ (not in this PR)

### CODE REVIEW

**Comment by tophf** [comment]
Uhm, I guess it's too soon to review this.

**Comment by tophf** [comment]
Okay, now it's ready for tests/review.
Zip for sideloading: [freestyler.zip](https://github.com/openstyles/stylus/archive/freestyler.zip)

As for tweaking parameters from within our manager, it's a separate task, we'll add it later both for FWS and USO.

**Comment by Mottie** [comment]
I can't seem to duplicate this issue every time, but if I uninstall a style using the "uninstall" button on freestyler.ws while I have the style open in the edit.html page, I see this error:

```
Unchecked runtime.lastError while running browserAction.setBadgeText: No tab with id: 2128.
    at getTab.then.realTab (chrome-extension://abejmoljcmmfbadecjncgdcdfojhobdl/background/background.js:314:32)
```

**Comment by narcolepticinsomniac** [comment]
Looking pretty good. The link to open the manager from FWS has the style-id added to the URL to focus it upon opening, but that's not working for me.

**Comment by Mottie** [comment]
I don't really like the freestyler logo, it doesn't resize very well.



Maybe we should use their super-ugly site icon instead?

**Comment by tophf** [comment]
I've decided to minimize the visual changes:

* the original long "find more styles" label is back
* a second row with site names and smaller icons
* freestyler's rectangular icon is used

clip339-fs8

I was thinking about an inline simple config to choose the find-styles block appearance e.g. only the "find styles blabla" label is displayed and it opens one of the sites configured in that dialog, but then decided against it because we might change the popup layout.

>link to open the manager

fixed.

>setBadgeText: No tab with id

AFAIK this is not related to this PR. I encounter it like once a year on my computer, but some users can see it more often despite multiple double-checks in our updateIcon before invoking the idiotic API method which doesn't have a callback so we can't clear the error.

**Comment by tophf** [comment]
I've removed the awkward links into a dropdown list shown only when clicking a nearby icon that shows which site is used by default.

**Comment by Mottie** [comment]
It's not obvious that you can choose a site to search for more styles. I thought I was on the wrong branch several times before I realized that the icon had a different tooltip. I liked the layout you had before



Also, the manage.html page needs to be updated with your choice (or show both sites)

**Comment by tophf** [comment]
We'll, it's okay to be subtle, we'll add a new compact layout anyway so I want the old layout to remain unchanged or at least just as cluttered as it is, not more. 

As for the get styles link, I always thought it's weird and useless. I really would like to remove it, but so far it escaped my attention.

Maybe we'll add an option in the options page, but I'm not convinced it's so important to advertise it everywhere. Or maybe we'll make an intro tutorial mode with hints and pointers for the new features.

**Comment by tophf** [comment]
On the other hand, a menu is a complication of UX in case the users want to search on both sites often so maybe it's worth showing both icons.

**Comment by Mottie** [comment]
Yeah, it might be better to remove that link... then maybe move the "get help" up to the top as a clickable (i) icon.

**Comment by tophf** [comment]
Chrome 63+ displays a warning in background page console when accessing fresstyler.ws:

>The SSL certificate used to load resources from https://freestyler.ws will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

I guess I'll wait for FWS to update the certs, otherwise I doubt we want to support their site as many users will be worried by that warning.

**Pull request closed without merging**
