### PR TITLE
Corrected to reflect actual functionality

### PR DESCRIPTION
**Pull request by Gitoffthelawn**
See also https://github.com/openstyles/stylus/issues/1143

### CODE REVIEW

**Comment by tophf** [comment]
Nope, the message itself is fine and its contents matches its id so it might be used somewhere in a correct context. We'll fix the feature itself later.

**Comment by Gitoffthelawn** [comment]
@tophf  Sounds good.  Correcting the functionality is obviously the real long-term goal.  

Note that the message itself is currently incorrect, as it says the domain will be excluded, but it's only a subset (the host) that is excluded.

**Comment by tophf** [comment]
The message itself is correct. Its use is incorrect.

**Comment by Gitoffthelawn** [comment]
@tophf  LOL! True! Very true!

**Pull request closed without merging**
