### PR TITLE
Custom UI elements

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
I regret calling these "easy CSS fixes". No CSS is easy in FF. Button text vertical alignment appears to be a foreign concept in FF. Even their default buttons have all text 1px lower than centered. When you customize them, about 50% require one padding rule, and the other 50% a different padding rule. Even tried losing top/bottom padding and setting a hard height/line-height and it still shits its pants. If there was some simple way to make them consistent, it wasn't obvious to me, but I'm pretty sure I fixed them all. This bug is strictly Windows, Linux requires only the one rule. Windows stable, beta, and Nightly all behave the same, so at least the workaround is consistent. ESR behaves the same, but requires different rules for each, also accounted for. Tested in Chromium/Linux Chromium, Opera and Vivaldi, and the one normal padding rule works for all. 

As for the buttons themselves, I think I've mimicked Windows Chromium buttons pretty well. As I mentioned, I recreated the subtle gradient using a transparent image, so we can put a slight transition on hover bg color. Hovers are smoother and slightly more obvious than the defaults, but nothing too drastic.

Regarding Linux, now that inputs and buttons are customized, the only thing preventing our UI from being 99.9% identical is the font issue. Shouldn't be too difficult, but I'm not sure what the most efficient way to load Arial would be. The number inputs are mostly stylable, except for the actual arrows, which are terrible in Linux FF. I've styled them to look normal, and set the arrows to be hidden unless the input is hovered or focused. They're rarely used, so at least they won't muck up the UI when they're not in use. I also abandoned trying to eliminate the dotted border inner text focus bullshit. I swear that one rule worked the other day, but turns out it doesn't. They actually render it according to text color. There are terrible hacks setting focused text to transparent and resetting text color with text shadow. They're buggy and shitty, so not worth implementing. No idea why they only still do this in Linux, but I guess they're used to it. Users who hate it probably figure out a config switch or some other workaround.

Didn't put a lot of effort into text inputs, but they all look fine in every browser/OS tested. We can tweak any properties to achieve the same styling if necessary. Only one styled differently is the manager search input, because it looks better shorter. In the search input, typed text and the clear "X" look 1px low vertically, which can't really be solved with padding, or the placeholder text becomes off center. This was the case with the previous CSS as well. NBD, but it'd be nice to fix. Double-check any obscure popups which may contain inputs/buttons I might've missed, particularly usercss shit.

I also found an unrelated Vivaldi bug. It fails to calculate the width of filter selects correctly on the initial page load. They only appear correctly after reloading the page. We set a max-width instead of any width property so they resize dynamically depending on the current selected option text. Works fine in all other browsers, so I don't wanna break it for a Vivaldi bug. Vivaldi has no special browser class, but it'd be nice if it did so we could only break dynamic resizing in Vivaldi to circumvent their bug.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Vivaldi bug: 
[Vivaldi-calc-bug.zip](https://github.com/openstyles/stylus/files/1537695/Vivaldi-calc-bug.zip)

**Comment by tophf** [comment]
* Please commit button.png
* `x` to the right of `Filters` heading is always visible now
* `(i)` to the right of search input field is not in the same row
* can't repro the Vivaldi bug, but I can add `.vivaldi` on `<html>`, it's trivial.

**Comment by tophf** [comment]
* the favicon expander triangle is misplaced now

**Comment by narcolepticinsomniac** [comment]
Yeah, had just remembered the image. Damn, you're quick.

**Comment by tophf** [comment]
Uhm, your CSS is based on some old commit, we no longer have `fieldset` and some other stuff.

**Comment by Mottie** [comment]
The video you shared is still using the Filters within a fieldset... so it's up to the same level as the master. I encountered the same issue with the select width when the filter detail was initially hidden. So maybe in the `adjustWidth` code we prevent the width being set to zero...

```js
// original: this.style.width = singleSelect.offsetWidth + 'px';
this.style.width = (singleSelect.offsetWidth || 'auto') + 'px';
```

**Comment by narcolepticinsomniac** [comment]
Dude, it's only been like 2 days. I can't keep up.

**Comment by tophf** [comment]
>so it's up to the same level as the master

The problem is that this PR's code was originally based on an old commit which was merged with the current master branch so quite a few deleted things crept in.

**Comment by narcolepticinsomniac** [comment]
The majority of the code should be easy to re-incorporate in a fresh master.

**Comment by tophf** [comment]
Well, so who will do it?

>So maybe in the adjustWidth code we prevent the width being set to zero...

It's best we don't do anything globally if we don't know the real cause so I think adding an exclusion for Vivaldi is better.

**Comment by tophf** [comment]
Can I push Vivaldi-detection commit here?

**Comment by narcolepticinsomniac** [comment]
Of course. If I'm gonna have to redo this with a fresh master, maybe better to do it there, however.

**Comment by narcolepticinsomniac** [comment]
Buttons look good, no?

**Comment by narcolepticinsomniac** [comment]
Fishing for a compliment here.

**Comment by tophf** [comment]
Buttons are cool. Now I can look at them in FF without facepalming.

**Comment by tophf** [comment]
Pushed Vivaldi detection in master.

**Comment by narcolepticinsomniac** [comment]
>x to the right of Filters heading is always visible now

I don't even know what you're referring to. 

filters

>(i) to the right of search input field is not in the same row

Again, unclear:

favicon

I'll re-implement the relevant code in a fresh master, but it can't be immediately. I can shoot for the next 12 hrs, but definitely the next 24. I need some clarity on the above bugs so I don't repeat them.

**Comment by tophf** [comment]
You're looking at some older commit. The filters section looks different now.

**Comment by narcolepticinsomniac** [comment]
Alright, but you're testing the same older commit, no? I don't get it. Regardless, they should be obvious when I redo it then, so I'll look out for them.

**Comment by tophf** [comment]
I'm testing whatever is downloaded from this PR and it seems the old code just got stacked onto the current master so the old and new got mixed up.

**Comment by narcolepticinsomniac** [comment]
OK then. NBD, I just wasn't seeing it. Good to know what to look out for anyway.

**Comment by narcolepticinsomniac** [comment]
Yeah, it wasn't sinking in how much had been rearranged in the master. Shit was buggy as hell with the commits I made. Good news is, getting rid of `fieldset` eliminated the Vivaldi calc bug. Probably best to have a class for it anyway for any future issues. Rearranging the header also screwed with a bunch of the button padding hacks, revealing how fragile they were. Wasted a bunch of time fixing and checking different versions. Noticed `select` elements have shitty line-height in FF. Checked it out, they use a different font and line-height with `!important` declaration. Override it. Selects look good. Joy. Now buttons next to `select` elements have different line-heights. Fucking ridiculous. Line heights move around googly like eyes in haunted house paintings whenever anything on the page is changed. Not all, just random buttons here and there with no rhyme or reason.

Obviously this is unmaintainable. Was about to throw in the towel. Started throwing random properties at FF buttons, and finally figured out the issue. FF absolutely, positively shits its pants when dealing with fractions in `font-size`. I'm using `13.3333px`, copied straight from Chrome devtools, because it makes quite a bit of difference when trying to copy them as closely as possible. Never even occurred to me that this could possibly be the problem in FF, but setting them to 13px for FF fixes all the weird line-height shit. FF... what a POS. At least they're good now.

I also noticed "write-a new-style" `a` was overflowing its button, and the usercss label and checkbox there wasn't strictly aligned, so I fixed those.

**Comment by tophf** [comment]
Everything looks great!
Will you style options.html buttons for Firefox in this PR or we merge it now and you do it later?

**Comment by Mottie** [comment]
It looks good to me too!

My only issue is that if I use <kbd>Tab</kbd> to navigate, I can't tell if the checkboxes or the filter selects are focused.

**Comment by tophf** [comment]
Hmm, yeah, we should retain visual indication for keyboard focus.

**Comment by narcolepticinsomniac** [comment]
>My only issue is that if I use Tab to navigate, I can't tell if the checkboxes or the filter selects are focused.

This is always some big deal to you, huh?

>Hmm, yeah, we should retain visual indication for keyboard focus.

What happened the "I don't care about that" guy? Me and that guy have a lot in common. =)

In this case, we wouldn't be "retaining" anything, we'd be adding it. All checkboxes have had `outline: none;` since way before we forked it. It's because they look like shit outlined. I get the accessibility factor, but it doesn't outweigh the aesthetics IMO. They've always been this way, and the only one I've ever seen bring it up as being an issue is Mottie.

>Will you style options.html buttons

I thought Mottie had mentioned that they weren't stylable, so I hadn't investigated. Maybe I misunderstood. Anyway, that's not the case, so I added the CSS for them. Can't even combine their regular selectors with those webkit abominations or they fail, so their code is separate.

**Comment by Mottie** [comment]
> This is always some big deal to you, huh?

Accessibility should be a concern everywhere on the web. People may use this extension to make sites more readable, have better contrast and even restore outlines. I'm not pushing anyone to do something they don't want to do... it's more of a reminder that hey, you can add an underline or something so a user knows what element is focused on the page.

> I thought Mottie had mentioned that they weren't stylable

Sorry, I meant that you can't target the options.html page with a userstyle in Firefox.

**Comment by tophf** [comment]
>you can't target the options.html page with a userstyle in Firefox.

works4me, that page is just like any other page in our extension from userstyle's point of view, it's just FF embeds it in an iframe-like container or whatever.

**Comment by Mottie** [comment]
Doh, you're right... I guess I don't use FF enough to notice 😛

**Comment by narcolepticinsomniac** [comment]
>Accessibility should be a concern everywhere on the web.

Well, I certainly don't disagree in theory, but in the case of checkboxes, whoever eliminated outlines (likely Jason since they've always been that way) had the right idea IMO. Go ahead and disable the property in devtools and toggle some. It's not a good look, especially since the state change for them is so obvious. 

I suppose maybe we could have an accessibility option which overrides the property globally. That's not my department, and I don't know that it's worth the trouble given the fact that I've seen zero negative feedback about it in all the years Stylish for Chrome has been hiding them.

**Comment by tophf** [comment]
I've removed the nonsensical `"chrome_style": true` from our manifest.json and everything seems fine.

**Comment by narcolepticinsomniac** [comment]
"Everything"? What was wrong?

**Comment by tophf** [comment]
Uhm, I mean the option did nothing so nothing changed when I removed it. Apparently.

**Comment by narcolepticinsomniac** [comment]
It specifies how to open options page, right? Is it not necessary for previous versions we support either?

**Comment by tophf** [comment]
Works in Chrome 49 (the last one that runs in dinosaur WinXP) and FF52 ESR.

**Comment by narcolepticinsomniac** [comment]
Nice.

**Comment by tophf** [comment]
Removing the option also removed those weird webkit selectors you mentioned.

**Comment by narcolepticinsomniac** [comment]
Alright. Well, I can either fix `options.css`, or I'm not sure why we wouldn't get rid of button code there and inject `global.css`. There's some number inputs that could use styling for Linux.

**Comment by tophf** [comment]
Uhm, fix what? Anyway, I've just tried removing the added code from options.css and adding `global.css` in options.html (before options.css). Everything's fine too so let's do that.

**Comment by narcolepticinsomniac** [comment]
>Uhm, fix what?

Hadn't looked yet, but I assumed you were saying the button selectors were no good.

**Comment by tophf** [comment]
Chrome's weren't. Yours are.

**Comment by narcolepticinsomniac** [comment]
Hey tophf, when you ignore something completely that usually means you don't care, but I still think it'd be  a much better look, and far better continuity to force Arial in Linux. Is `@import` a one shot deal and then it gets stored locally? Do you know the best way to go about it?

**Comment by tophf** [comment]
I just don't know the technical details about including fonts. What I do know is that almost all custom fonts used by almost any site seem retarded to me. But maybe we can find a better standard font. Arial was always berated for some issues (personally I like Tahoma's screen hinting at small font sizes the most).

**Comment by narcolepticinsomniac** [comment]
Fonts aren't something I usually bother with personally either. On the rare occasions I do, it's usually swapping one "web-safe" font for another. Arial doesn't bother me, and it's considered among the safest. Linux didn't get the memo. I'm open to whatever, but it'd be great if it was the same in all browsers/OSes. Not like I'm advocating for it specifically, but as I've mentioned, Roboto is capable of in-between font-weights, which is a cool option to have. The most recent version isn't too different from Arial to my untrained eye.

**Comment by tophf** [comment]
Arial normal and bold are 1.5MB, +italic = 1.9MB
Roboto normal and bold 0.3 MB which means it supports a lot less characters, meaning a fallback font installed in OS will be used.

I don't want to include any of that. I'd rather specify something in our `font-family` that's included in Linux and looks good.

**Comment by narcolepticinsomniac** [comment]
I looked at the fonts again in Linux, and it seems I'm somewhat mistaken. Computed shows it is using Arial. It just doesn't look anything like Windows Arial. Basically, their version is shorter and wider (more elongated, not bold). IDK if they use a different variant, which is something that could be corrected, or if that's just the way the OS renders fonts in general. For the most part it's not terrible, and it's certainly a constant reminder that you're a super cool Linux user.

It's not that different, and I'm sure some people prefer it, even if it could be fixed. I've just been on a mission to make it as close as possible. We could probably leave it as-is with a simple tweak for FF.
Besides being a little different looking, the real issue is font-weight. Their bolds are bolder, and it's worse with some fonts than others, particularly sans-serif which we use for `.style-name` in the manager. They're a main focal point, and they're crazy big and bold:

linux-ff-bold-style-name-sans-serif

Linux Chromium must know it'll look like shit, because it just straight up ignores it and uses Arial instead, even with an `!important` declaration. It says sans-serif in computed, but that's complete BS. If I paste Arial in the property it doesn't move, and when I switch FF to Arial, they look exactly the same. Chromium:

linux-chromium-ignores-sans-serif

FF with Arial override for `style-name`:

linux-ff-arial-override

With the Arial override for `style-name` in Linux FF, it looks identical to Linux Chrome. It's the only real terrible font issue, so we could probably leave it at that.

**Pull request merged**
