### PR TITLE
Another popup mockup

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
This is a fraction of what I want to do with the popup, but these are improvements that can be made to the existing version without a complete overhaul. Should be no difference appearance-wise, only some simple enhancements to existing functionality in terms of click area and stylability. 

Eliminates ill-conceived `.left-gutter` altogether. Checkboxes and labels are now either parent/child or siblings, with no weird spaces between them, and their hovers can therefore be styled together. `entry` checkbox/label `.style-name` now occupies the entire height/width of the `.entry` to the left of the `.actions` icons, so no more errant clicks.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Someday I'll quit uploading everything to the root directory. I miss those days.

**Comment by narcolepticinsomniac** [comment]
Also gave a little breathing room to entry numbers, and adjusted for added popup borders.

**Comment by tophf** [comment]
You seem to assume that checker has a certain size and you position it absolutely, but it's different depending on OS theme.

**Comment by narcolepticinsomniac** [comment]
True. In the original I replaced them. Should I do that again, or reposition more flexibly? Personally, I think we should eliminate as many OS inconsistencies as possible. Positioning is trickier here than usual when accounting for ellipsis in `flex`, but I'm sure it's doable one way or another.

**Comment by narcolepticinsomniac** [comment]
If replaced we can have a simultaneous checkbox/style-name hover to indicate the much bigger clickable area.

**Comment by tophf** [comment]
I don't know. I was planning to get back to the pending PRs, including yours and mine.

**Comment by narcolepticinsomniac** [comment]
Yeah... someday. =)

If it isn't obvious, I've been updating my dark style and hover checkbox/labels is something I'd like to include since I am replacing checkboxes in the style.

**Comment by tophf** [comment]
Custom checkbox is fine I guess. It shouldn't break anything, supposedly, but it'd be even better if someone does a quick test of 5 most popular extension themes that work with Stylus...

**Comment by tophf** [comment]
Or we can officially admit that we don't care and just go ahead with the change and let the theme authors sort their stuff out.

**Comment by narcolepticinsomniac** [comment]
Well, I'm off for a while. If you give me the go-ahead, I'll fix it up tonight. I recommend custom CSS checkboxes with SVG checks. Already got that code pretty well worked out in the other PR.

Eventually we should customize all weird OS shit. Buttons, checkboxes, selects, inputs, etc, but we might as well start somewhere. Could replace all checkboxes and wrap em tight with their labels so they always line up. IIRC, FF on Linux had giant checkboxes with labels a quarter inch underneath them.

**Comment by Mottie** [comment]
> quick test of 5 most popular extension themes that work with Stylus..

I did that last night in Chrome, but mostly Firefox, when I made screenshots for our [Product Hunt](https://www.producthunt.com/posts/stylus) page. Ok, maybe only 3 pages 😛.

**Comment by tophf** [comment]
Hey, the hover effect on checkbox seems to belong to your dark theme, but in the default white one it's too aggressive. Let it be subtle, really subtle, like the standard one.

**Comment by tophf** [comment]
(when hovering a checked checkbox).

**Comment by narcolepticinsomniac** [comment]
Subtlety is not my go-to, but ok. We do want it to be obvious, no? Should I not invert the hover check fill? And the background should be more subtle, like the unchecked hover?

**Comment by tophf** [comment]
On a standard checkbox there's no hover effect at all so either remove it or make it really subtle, even more subtle than the one over unchecked checkboxes. I would prefer the former solution as I don't like UI animations on a desktop computer and it would match the standard behavior.

**Comment by narcolepticinsomniac** [comment]
You're taking all the fun out of custom checkboxes, you killjoy. =)

I think it's kinda important to have at least a subtle hover, especially to indicate the much bigger clickable area. Let's see if I can do something more subtle that you won't hate.

**Comment by tophf** [comment]
You can highlight the entire row just a bit, which is used in many UIs so it would look pretty standard. My main objection is that an animated checkbox needlessly draws attention to itself away from the mouse pointer. In case the entire row is highlighted there will be no distraction because the animation wouldn't occur elsewhere, it would be right there where the users look.

**Comment by narcolepticinsomniac** [comment]
>an animated checkbox needlessly draws attention to itself

But... I feel the need. Drawing attention to the checkbox is intentional to indicate click action.

>In case the entire row is highlighted there will be no distraction

Clickable area isn't the entire row, it's everything left of action icons. Hovering background on part of the row will look odd, and it's also a less obvious indicator of click action IMO.

Didn't change "disable all" yet. It's a special kinda function, so maybe slightly more drastic is warranted, but I can tone that down too.

**Comment by tophf** [comment]
LGTM. I think we can merge as is.

>Drawing attention to the checkbox is intentional to indicate click action.

The initial hover effect might have worked in a one-time introductory course to using our UI :-)

**Comment by narcolepticinsomniac** [comment]
You want me to hook up all the other checkboxes on our other pages for continuity? Also, do I need to do anything special, or just squash and merge?

**Comment by Mottie** [comment]
I like it too! 👍

**Comment by tophf** [comment]
>hook up all the other checkboxes on our other pages for continuity? 

Makes sense.

>just squash and merge

Yeah!

**Comment by tophf** [comment]
SVGs aren't displayed in FF52.
Investigating...

**Comment by tophf** [comment]
Ah, svgs are displayed. It's the standard borders on checkboxes still persist for some weird FF reason.

**Comment by tophf** [comment]
Apparently there's a bug in old FF which makes `-moz-appearance: none` enforce a retarded `inset` border style regardless of anything I throw at it (even in an inline style attribute).

**Comment by Mottie** [comment]
Oh yeah, that's the reason we used to include `/* AGENT_SHEET */` to fix FF appearance none issues. I don't recall if we are still styling FF checkboxes in GHD; @silverwind can you shed some light?

**Comment by tophf** [comment]
I can only suggest disabling styled checkboxes in FF until we find a universal solution that works in old versions, which is used by hundreds of users currently according to the statistics.

[popup.css.zip](https://github.com/openstyles/stylus/files/1524479/popup.css.zip)

**Comment by Mottie** [comment]
Yeah, it looks like we only use `-webkit-appearance: none` and ignore FF ([ref](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L955-L983)).

**Comment by tophf** [comment]
hmm, I can add a class on `<html>` like `no-styled-checkboxes` when FF version is less than 57.

**Comment by tophf** [comment]
Done.

**Comment by silverwind** [comment]
I used AGENT_SHEET previously to raise the style weight to allow checkbox styling, but IIRC, this is no longer necessary as of Firefox 54 (https://github.com/StylishThemes/GitHub-Dark/issues/275#issuecomment-303793972).

**Pull request merged**
