### PR TITLE
show sublime bookmarks

### PR DESCRIPTION
**Pull request by tophf**
* Implements #949 since CodeMirror's author doesn't want to. The default style is really primitive: it's a gradient from currentColor to transparent over the line number.

* Removes the no longer needed optimization which is included in CodeMirror.

### CODE REVIEW

**Comment by dnknn** [comment]
Wow, show bookmarks needs to change many lines of code..Very thanks♪(･ω･)ﾉ for your hard work

**Comment by narcolepticinsomniac** [comment]
Playing around with it a little, I can't help but think how much cooler and more useful it'd be if it was more user-friendly though.

Click line numbers to bookmark/unbookmark, some kinda convenient click function to cycle, and it'd be way more useful if it actually cycled through all sections.

Seems to work as intended, so we can merge as-is if you're not into these suggestions.

**Comment by dnknn** [comment]
@narcolepticinsomniac 
E.g
chr (1)

If want to add a icon: e.g.🔖🠶 Unicode character
https://unicode-table.com/cn/1F836/
https://unicode-table.com/cn/1F516/

**Comment by tophf** [comment]
Nah, merge this as is. To make this mouse-controlled I would have to decouple the entire bookmarking functionality from sublime keymap so it works regardless of the keymap selected. This is something to do in the future.

**Comment by narcolepticinsomniac** [comment]
Fair enough. Figured it might be tedious. Hope you keep it mind though. 

I do think that what I'm describing would become a pretty popular little feature fairly quickly, particularly with a little visual indication of new functionality. 

If editing large styles, I'm constantly jumping back and forth between different code blocks in different sections,  by utilizing "find", which works, but is kind of a PITA comparatively.

**Comment by tophf** [comment]
I can forget... Better create a new issue.

**Pull request merged**
