### PR TITLE
Switch to duckduckgo favicon service

### LINKED ISSUE #918: Switch to duckduckgo favicon service?
I don't even use favicons in the manager, but I was using Google's service elsewhere, and was surprised by how many sites which have favicons it misses. I switched to DDG's service, and it seems to fetch the right favicons far more reliably. [Privacy policy](https://help.duckduckgo.com/duckduckgo-help-pages/privacy/favicons/) is good, but that's not even the main consideration here - it just seems like a better service.

@tophf WDYT?

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
Switch to duckduckgo favicon service. Closes #918

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Found a little pre-existing bug where `url-prefix` rules were adding wildcards to favicon URLs, breaking them, so I removed em.

**Comment by tophf** [comment]
Code is fine but icons with thin lines are worse:

image

Google's:

image

**Comment by narcolepticinsomniac** [comment]
Hmm. I hadn't noticed any difference. Guess it's a matter of png vs ico? Not sure if DDG serves up any other format. Changing the extension doesn't work, so I'm not optimistic.

**Comment by tophf** [comment]
Apparently DDG processes the icons on their servers and they do it in a way that mangles thin lines.

**Comment by narcolepticinsomniac** [comment]
I guess. I never would've noticed if you hadn't pointed it out, but there's a slight difference. It's a shame because Google misses a lot. So stupid, because it's something Google should be perfect at, but obviously it's not something they're even trying to be good at.

IDK man, I guess it quality vs quantity. Obviously isn't a huge deal either way. This was supposed to be all upside, no downside, so we could just stick with the status quo.

**Comment by tophf** [comment]
Will you report the problem to some DDG bug tracker? Maybe they'll fix it quickly.

**Comment by narcolepticinsomniac** [comment]
I don't even think it's technically a "bug", so much as a classic case of larger images scaled down to 16px not being as proportional as the same image, specifically designed for those dimensions.

DDG's approach seems pretty straightforward. I guess it might not be so much how they "process the icons on their servers", but maybe the fact that they serve up exactly what the site itself provides.

It's tough to say, not knowing exactly how or where Google pulls its favicons from. All I know for sure, is that it doesn't provide them as reliably, but the ones it provides are optimized for 16px.

You can check out the difference:

https://www.wikipedia.org/static/favicon/wikipedia.ico
https://icons.duckduckgo.com/ip2/wikipedia.org.ico

^ These look identical to me.

Then there's Google's:

https://www.google.com/s2/favicons?domain=wikipedia.org

Clearly made for favicon dimensions.

**Comment by tophf** [comment]
Indeed. Turns out the culprit is our `backface-visibility: hidden`. Removing it fixes the appearance.

**Comment by narcolepticinsomniac** [comment]
Huh. There's a multiple properties combined on those elements which are problematic in Chromium. Opacity, filters, and backface-visibility, all can cause glitchiness/pixelation, particularly combined with any transition. Been like that forever and probably always will be.

IIRC, `backface-visibility: hidden` was to fix a bug on OSX.

**Comment by dnknn** [comment]
https://icons.duckduckgo.com/ip2/unicode-table.com.ico

Looking,it is also very bigger, 512px×512px

Snipaste_2020-05-03_03-32-13

**Comment by tophf** [comment]
It was reported two years ago in https://crbug.com/833135 and no one bothered fixing it.

I guess this PR can be merged as is and I'll just limit the backface hack to MacOS in a separate PR.

**Comment by narcolepticinsomniac** [comment]
>I guess this PR can be merged as is

Not exactly a ringing endorsement. =) Or we can just close it and do nothing. Neither of us really care about this personally. I only hooked it up bc I thought it was a no-brainer. I wouldn't have bothered in the first place if I'd known otherwise.

I'm on the fence now, so LMK whether you think it's actually worthwhile.

**Comment by tophf** [comment]
Ewww... even if I remove the backface hack Chrome will randomly promote the images to a separate layer which flickers on hover:

**Comment by narcolepticinsomniac** [comment]
Gotta love Chromium. Let's just forget we ever bothered?

**Comment by tophf** [comment]
I'm trying to switch to background-image...

**Comment by tophf** [comment]
Nope, didn't help.

**Comment by narcolepticinsomniac** [comment]
Aah, forget this.

**Comment by tophf** [comment]
It's fine in new Chrome so I've used this PR in 4c4a319b.

**Pull request closed without merging**
