### PR TITLE
Refactor: rewrite style injector

### LINKED ISSUE #642: about:blank not injecting all applicable styles
It appears to return the first match, seemingly based on install order, and then declares mission accomplished.

STR:

Test URL with `about:blank` quiz iframe: `https://bit.ly/2RMhRgG`

Depending on your adblock, you may need to allow playbuzz:

ubo

Visit the test URL with a fresh install of Stylus, then make a test style:

(All test elements are at the bottom of the quiz iframe)

theChive Test Green:

```
@-moz-document regexp("https?://thechive\\.com/20.*") {
.pb-share-button{background:green!important;}
}
```

Style is applied immediately, and on page reload.

Install a second test style:

theChive Test Blue:

```
@-moz-document domain("thechive.com") {
.pb-story .bottom-share-bar-container{background:blue!important;}
}
```

Style is applied immediately, and on reload, but the first style is no longer applied on page load.

Install a third test style:

theChive Test Red:

```
@-moz-document regexp("https?://thechive\\.com/20.*") {
.pb-powered-by{background:red!important;}
}
```

Style is applied immediately, and on reload, but the first two styles are no longer applied on page load.

[Screen record](https://streamable.com/mxed2)

### PR DESCRIPTION
**Pull request by eight04**
Fixes #642.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Fixes the weird `about:blank` injection issue, so nice job on that. There's communication issues with our own internal pages though:

stylus

**Comment by eight04** [comment]
STR?

**Comment by narcolepticinsomniac** [comment]
Just test [my style](https://userstyles.org/styles/142097/stylus-insomniac) in Chromium. Should be pretty obvious.

**Comment by narcolepticinsomniac** [comment]
Injected styles' DOM location is inconsistent. Sometimes they're after `body` as expected, but quite often they're before:

style inject

**Comment by eight04** [comment]
Fixed in 788085d

**Comment by narcolepticinsomniac** [comment]
I tested this branch for a while after the last commit, and it seemed solid. Fixed the `about:blank` bug, and appeared to work well otherwise. It's the kinda thing you wanna test as much as possible, which probably isn't gonna happen in this PR, so I'm thinking we should probably merge it so those of us loading the master can all test it thoroughly. @Mottie ?

**Comment by Mottie** [comment]
Yeah, sounds good to me. I've been overwhelmed with unrelated stuff, so I haven't been very active here. I was planning on reviewing this repo's backlog (for me) this weekend.

**Comment by narcolepticinsomniac** [comment]
If you can give the code a once-over this weekend, it'd be preferable to hold off till then. I just don't want this branch to get lost in the mix as we test others.

**Comment by Mottie** [comment]
I'm seeing weird errors when I load this branch:

> Error: Extension context invalidated.
Context: https://github.com/
Stack Trace: js/msg.js:84 (ignoreError)

Then when I load any GitHub page:

> Uncaught Error: The page keeps generating mutations. Skip the event.
Context: https://github.com/
Stack Trace: content/apply.js:424 (anonymous function)

**Comment by eight04** [comment]
> Error: Extension context invalidated.
> Context: https://github.com/
> Stack Trace: js/msg.js:84 (ignoreError)

This error occurs when the extension is unloaded (reloaded). Since the background page is unloaded, `msg.js` failed to send messages to the background.

> Uncaught Error: The page keeps generating mutations. Skip the event.
> Context: https://github.com/
> Stack Trace: content/apply.js:424 (anonymous function)

This error occurs when the children of the HTML node keeps changing. Usually, we have to resort all styles on change.

How many styles are applied to the page?

**Comment by Mottie** [comment]
I have at least 5 styles applied to GitHub at all times.

**Comment by narcolepticinsomniac** [comment]
Yeah, I ran into some real issues when swapping out the exclusion branch to retest this one and then reloading the extension. Got the "could not communicate" BS until I restarted the browser. It also consistently throws the same couple errors when toggling the extension's enabled state. There's no obvious bugs caused by the toggle errors, and it appears to work well and error free, aside from that.

after

**Comment by eight04** [comment]
> Uncaught Error: The page keeps generating mutations. Skip the event.

I can't reproduce on github.com. Have you installed other extensions?

**Comment by narcolepticinsomniac** [comment]
I never saw the mutation error either. What about the couple which occur when toggling enabled state pictured in the screenshot above though?

**Comment by Mottie** [comment]
Sorry for taking so long to look into this... if I have userscripts being applied to the page, *that's when* I'm seeing the mutation error show up.

**Comment by narcolepticinsomniac** [comment]
>if I have userscripts being applied to the page

We've all got userstyles being applied though, so I'm not sure how that clarifies why you're seeing an error we haven't. Can you repro consistently?

**Comment by Mottie** [comment]
Yeah, it happens whenever I reload any GitHub page. And I have 25ish userscripts being applied each time.

**Comment by narcolepticinsomniac** [comment]
Very weird. You're gonna at least need to narrow it down to the culprit, I would think.

**Comment by Mottie** [comment]
Ok, install this userscript - https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-search-autocomplete - it's one that is causing the error.

**Comment by Mottie** [comment]
Hmm, that's one of the few userscripts that I use that load jQuery...

**Comment by Mottie** [comment]
This userscript loads jQuery as well, and causes the error - https://github.com/StylishThemes/GitHub-Custom-Emojis.

**Comment by eight04** [comment]
Which userscript manager?

**Comment by Mottie** [comment]
Tampermonkey

**Comment by eight04** [comment]
I can't reproduce on https://github.com/.

Windows 7
Cent Browser Version 3.8.5.69 (Official Build) (32-bit) (Chromium 71.0.3578.98)
Tampermonkey Beta 4.9.5914
GitHub Custom Emojis 0.2.7

**Comment by Mottie** [comment]
Windows 10 (64-bit)
Chrome v 72.0.3626.121 (Official Build) (64-bit)
Tampermonkey BETA 4.9.5914
GitHub Custom Emojis v0.2.7
**Octotree v2.5.6** <-- I see the errors when this is enabled.

Sorry. I didn't turn off _all_ of my extensions while testing. Now that I have, I see Octotree also needs to be enabled.

**Comment by eight04** [comment]
Fixed in 8458b6b

**Pull request merged**
