### PR TITLE
try to show applicable values in autocomplete for props

### LINKED ISSUE #1162: Autocomplete for CSS properties should show only applicable values
Just like autocomplete in DevTools styles panel, ours should only show applicable values, with the global values like `inherit` at the end of the list. For example, for `box-sizing` it'd be `border-box`, `content-box`, `inherit`, `initial`, `revert`, `unset`.

This can be probably implemented by using parserlib's [vtDescribe](https://github.com/openstyles/stylus/blob/7d6b4fc8ac2a08f7888f486108d9a17e47c45d74/js/csslint/parserlib.js#L2327) + a simple regexp to extract literal values from the result. If the current linter is csslint, it'll be used, otherwise a separate worker will be created.

### PR DESCRIPTION
**Pull request by tophf**
Fixes #1162.

Let's test/polish it.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Haven't tested a whole lot yet, but suggestions look infinitely less stupid. Pref change doesn't appear to be registering until the page is reloaded though.

Can't believe I'm gonna do this, but @dnknn might be the most thorough testing property related functionality.

**Comment by dnknn** [comment]
In fact, I rarely use `autocomplete` , because I output CSS directly from the input method, I first input the commonly used CSS (or CSS fragments) into the custom phrases of the input method, and then I can output them again anywhere.

> The input method is a software, can customize the phrase, used for quick output,
> Since not an English-speaking country, it is possible to do so.

**Comment by narcolepticinsomniac** [comment]
It's a backhanded compliment, for sure. You're good at testing this sort of thing, and that's a positive. You can also get sidetracked and fixate on irrelevant details, like responding about some alternative method you use. 

> I rarely use autocomplete

Neither do I. The majority of features we test here, we don't use personally. If you felt like testing it regardless, like we do, it might be helpful. If not, maybe give a thumbs-down, or don't bother responding at all.

**Comment by tophf** [comment]
> Pref change doesn't appear to be registering until the page is reloaded though.

I broke it in January, fixed now.

**Pull request merged**
