### PR TITLE
Attempt to get favicon for RegExp match

### PR DESCRIPTION
**Pull request by Mottie**
It's rudimentary, but the code matches a bunch of RegExp's for styles that I have installed. I'd rather see an icon than an empty space. 😉

### CODE REVIEW

**Comment by DanaMW** [comment]
Would that work for a url like this? 
/https://twitter.com(?!widget|cards).*/
I have one like this that also doesn't pick up an icon. Just so you know. Thanks.

**Comment by Mottie** [comment]
Yes, it would match... I created this demo: https://regex101.com/r/NRZ9nt/1/

**Comment by DanaMW** [comment]
Nice. Thank you.

**Comment by tophf** [comment]
1. You must handle regexps with negative assertions. 
2. Don't forget to test the impact on performance

**Comment by Mottie** [comment]
1. I haven't run across any styles that have a regexp with negative assertions. I think it would be relatively rare.
2. It looks like this change adds about 15ms, at least with the 35+ styles I usually use.

**Comment by tophf** [comment]
1. It's not rare enough to neglect it. LOTS of users edit their global styles locally to exclude sites, which is common practice. Some styles even provide a parameter on USO to add such sites via negative regexp assertion.
2. The problem is that it increases the time needed to build the first frame by 10% (250ms vs 220ms here). 1% would be acceptable, but not 10%. You need to postpone this into the subsequently invoked `loadFavicons`.

**Comment by Mottie** [comment]
It looks like I can speed up script execution by caching the regexp. I also get the script to remove any negative look ahead blocks in the regexp.

**Comment by tophf** [comment]
The negative assertions may be nested so you would erroneously match `site2` in `(?!site1(foo|bar)|site2)`. Removing the parenthesizes blocks properly isn't that hard so please do it :-)

**Comment by DanaMW** [comment]
I know your busy and this might seem like a silly question to people like yourself but I am going to ask anyway. One of the biggest shortcomings of web extensions is that you cant access outside of your addon for the most part. But the userchrome can. So my question is couldn't someone fashion a sort of responder or bouncer in the user files that you could send commands to and have it act on the rest of Firefox? That may be a substandard way of asking it but I hope you get what I mean...It might not be useful but I thought something like that would allow user scripts to access the browser functions.

**Comment by tophf** [comment]
@DanaMW, I don't really understand the idea, but please don't hijack an unrelated issue, open a new one.

**Comment by DanaMW** [comment]
yes sir..

**Comment by Mottie** [comment]
Or talk to us in Discord.

**Pull request merged**
