### PR TITLE
Improve issue template

### PR DESCRIPTION
**Pull request by Gusted**
- Add a CSS section(so I don't have to see those comments about posting CSS etc).
- Make it into more sections and separate them.
- Add notes to each section.

@narcolepticinsomniac this is what I had in mind.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Couple minor grammar issues aside, LGTM. I'd suggest adding something about restarting your browser, and testing in a clean profile before reporting as well. @tophf you have any thoughts on this?

**Comment by Gusted** [comment]
> I would use `###` instead of `##`.

As `#` indicate the amount of levels for headings, I'm trying to avoid any "skipping", as it's recommended[1][2] to only {in,de}cremenent by one. 

1. https://www.w3.org/WAI/tutorials/page-structure/headings/
2. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#accessibility_concerns

**Comment by tophf** [comment]
Semantic structure doesn't matter here, like totally.

**Comment by narcolepticinsomniac** [comment]
It's an improvement as-is, but I'm also sick of people reporting issues which are rectified by a browser restart, so that should be stated as mandatory. I suppose testing in a fresh profile doesn't need to be mandatory, but it should be strongly encouraged as a way to expedite things.

**Comment by narcolepticinsomniac** [comment]
Thanks Gusted!

**Pull request merged**
