### PR TITLE
small fixes and tweaks

### LINKED ISSUE #433: Add search parameter "name:" in manager's search
It would be a nice feature to be able to search in style names only.

E.g. I search for `dark` to examine my darkstyles and get lots of false positives from styles that contain something like `a { color: darkblue; }` or a classname that contains "dark".

This could be solved by searching for `name:dark`

### LINKED ISSUE #742: [Feature Request] Please add last updated Date column on the list page.
When we click the Stylus icon and go to Manage, we reach to home page where we see list of installed styles.

Can we please have last modified date column added there to identify when the style was updated last. This helps me to manage personal custom styles.

### LINKED ISSUE #1087: Keep page position when reloading instead of scroll to the top (multi-section page)
on multi-section (classic-CSS-editor) page,  Current issue: 
- When pressed `F5` to reload page , it always scroll back to the top instead of keep.

This is not a big problem, if it will affect something or not easy to achieve, please ignore  and close this issue.:)

### PR DESCRIPTION
**Pull request by tophf**
In addition to a few trivial fixes/tweaks it also fixes #1087: now the editor's scroll position and text selections are kept in tab's session for each style edited within this tab's session. It improves UX in these scenarios: `manager->editor->back->forward` or `editor->manager->back`. This can be used with any number of styles within the same tab's session. A session lives until the tab is closed.

Fixes #742.
Fixes #433.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
>the order might be decided by the extension installation order, IDK.

Usually, if that's the case, reloading affects the order, and that doesn't seem to be the case. We appear to always be winning CSP headers race, AFAICT. 

`style-src` causes issues on some sites. Check the Disqus iframe on our [add0n](https://add0n.com/stylus.html) page.

I'm actually kinda concerned about the conflict with TM, given the fact that the loser of the race doesn't even seem to get a participation trophy. TM must modify headers to allow scripts, which we're not doing. 

I've noticed TM's CSP settings before, but they're enabled by default, and I never ran into any issues, so I never bothered with them. Now that I'm concerned about a conflict, I checked them out, and they provide the option to strip them entirely, which means no conflict for anybody.

I get why CSP is a thing, I just don't want it to be a thing that's of no use to me personally, which I have to deal with constantly. It's kinda like antivirus software - if you know what you're doing, it's mostly just a PITA. 

Judging by the fact that you needed convincing on allowing non-data-images, I'm not all that optimistic I can sell you on the idea of providing the option of stripping them entirely, like TM, but I'm gonna at least suggest it anyway. If not, then I'd suggest we move the sandbox code to the rest of the optional CSP pref, so the option would be available to just use TMs instead.

**Comment by tophf** [comment]
No amendments to the option and its note? I just wonder if it's overly technical and thus unclear for the majority of users.

> reloading affects the order

AFAIK no, you would have to uninstall both extensions and install them in the new desired order.

> style-src causes issues on some sites

That's my bad. I shouldn't add it if it wasn't present initially. Fixed now.

> move the sandbox code to the rest of the optional CSP pref, so the option would be available to just use TMs instead.

Yeah, good idea regardless of whether we do it correctly or not. Done.

**Comment by narcolepticinsomniac** [comment]
>No amendments to the option and its note?

My fault. In my defense, you also ignored my main question. =) Should I take that as a hint? IDK, as long as I can kill CSP across the board with TM, that'll work. This pref, as-is, will be pretty convenient for lots of users, but I still think it'd be cool to offer the sledgehammer approach as well.

> I just wonder if it's overly technical and thus unclear for the majority of users

Maybe a little, but it's not terrible or anything. Maybe:

>Enable this if styles contain images or fonts which fail to load on sites with a strict CSP (Content-Security-Policy).

>Enabling this setting will relax CSP restrictions, allowing essential style content to load. This option is only intended for advanced users who understand the potential security implications, and accept responsibility for monitoring the content which they're allowing. Read about CSS-based attacks for more information.

>Also be aware, this particular setting is not guaranteed to take effect if another installed extension modifies the network response first.

Up to you. Tweak as you see fit.

**Comment by tophf** [comment]
I didn't ignore it, I thought now that I fixed the bug there's no need to remove CSP. Is there?

> a little

I'd say it's a whole lot better now.

**Comment by narcolepticinsomniac** [comment]
Well, TM must modify headers to allow scripts, right? This pref doesn't by default. TM is super popular, and the overlap of user bases is likely high. If this setting interferes with TM, or vice-versa, wouldn't that be problematic?

I think it might be useful if they both had optional settings which are compatible, so it wouldn't matter which won the race. If that potential conflict isn't registering as a significant issue to you, then perhaps I'm overthinking it.

**Comment by tophf** [comment]
Well, I don't use TM :-) And I don't like the idea of removing CSP mainly because the selector will break the uniformity of the options UI, haha. A practical solution might be just adding a note about interaction with TM e.g. "You don't need to enable this if you already remove CSP altogether in another extension like Tampermonkey or ModHeaders."

**Comment by narcolepticinsomniac** [comment]
>Well, I don't use TM

I figured, since you worked a bunch on VM.

>mainly because the selector will break the uniformity of the options UI

Literally laughed out loud. =) I can relate to to that kinda warped logic. 

This is probably one of those things we can revisit if it actually does become an issue down the road.

**Comment by tophf** [comment]
I've added columns for style version, size, and age in the manager as a stalled PR is as good as absent.

* The age is shown because its calculation doesn't consume CPU unlike proper rendering of locale-compliant date format.
* The size in kilobytes doesn't seem all that useful so I'm leaning towards removing or hiding it by default.
* The version is shown inside the name element because a) it's present only on usercss styles and b) I'm hiding `1.0.0` as it's essentially "no version" especially for locally created styles.

**Comment by narcolepticinsomniac** [comment]
>I've added columns for style version, size, and age

Pretty cool. I'm not a huge fan of all the empty spaces though. If a style hasn't been updated since being installed, then the install date is the last update IMO.

Kilobytes should be abbreviated to 'kb'. 'k' is much more commonly used as a generic abbreviation for 'thousand'. If I wasn't aware what I was looking at, I might assume it's an install count, or something. Also, it appears to always round down when it should probably round up, and 'bytes' should be indicated in the tooltip. For big styles, like Github Dark, it might be useful to convert 1106kb to 1.1mb.

Could use a little extra space between the second `.style-info` and `.applies-to`. Opacity for small sizes is alright, but not to the point where you can't see them. Maybe `currentColor` for `.style-info` and .6 opacity for tiny sizes. They should both have that opacity if disabled, and if enabled, sizes should be opaque on entry hover, and match actions transition.

**Comment by tophf** [comment]
Thanks, fixed. As for the size column, I've removed it. After all Stylus is not a file manager.

Added scope selector to the style search in manager. I also removed some `calc(100% - 30px)`, which probably was preserving space for the scrollbar in the header panel but everything seems fine without it.

**Comment by narcolepticinsomniac** [comment]
> As for the size column, I've removed it

I usually use a real compact layout, so I'd likely hide it, but I kinda liked it for the default layout. 

> I also removed some `calc(100% - 30px)`

From where though? Kinda rings a bell as something removed from the header a long time ago.

**Comment by tophf** [comment]
On the sort and search elements: https://github.com/openstyles/stylus/pull/1107/files#diff-f0ba897aef7820f3ff5ec9b8f7a3315f2122039b753149a5a7ec3eb10e5cb169L851

Apparently it was needed because there was flex-wrap which I removed as there's no need to wrap the teeny-weeny `(i)`.

**Comment by dnknn** [comment]
@tophf  I saw that you added some features to the manager, and I would like to mention a requirement by the way.
e.g. there are many styles applied to `github.com` , then, How to make them line up tightly, even if the first letter of the style is different ?

Can add `applies-to` to the manager sort?  This sorting allows related/applied to multiple styles under the same `domain` to be arranged closely together rather than separated.

You might say use style name to sort together , but we also use the first letter as the Popup-hotkeys.


So I think that this requirement can only be achieved by sorting by `applies-to`, WDYT？

**Comment by tophf** [comment]
@dnknn open a new issue.

**Pull request merged**
