### PR TITLE
switch to USO-archive for inline search in popup

### LINKED ISSUE #420: Search by text in the inline styles finder
Please add an option for searching themes by the name.
It is very difficult to find my favorite theme for sites like Youtube with 100+ themes available

### LINKED ISSUE #926: Add alternative sources instead of horrible userstyles.org
Since userstyles appear to be completely broken for some time now, can you replace them with, or at least include some alternative sources for (inline) css downloading? 

I don't know much about them but [_Openusercss_](https://openusercss.org/) looks promising..

### PR DESCRIPTION
**Pull request by tophf**
Fixes #926.
Fixes #420 - Search by text and sort the results.

Seems to work but didn't test it a lot yet.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
Nicely done. Performance is like night and day. This should make lots of users happy, once it's good to go, and it looks pretty close already.

USO forum returns "No styles found", which shouldn't be accurate. Couple minor cosmetic details - select needs styling to match all the others, and auto-scroll could add a few pixels, so bottoms of buttons aren't visible.

Not sure whether sorting pref should be remembered. Could make a case either way, but it's probably worth considering. IDK if it's much different from USO, but there seems to be lots of styles with no preview images. If there really are none, maybe we should add some placeholders, like:

image-unavailable

**Comment by decembre** [comment]
Yep that very good.
It's possible to add UserCSS from GreasyFork as alternative too ?

**Comment by tophf** [comment]
>USO forum returns "No styles found"

I didn't find USO forum category in the index. There's `userstyles.org` with ~400 styles so to find which ones apply to the forum I would have to download the actual code of all those styles, parse the moz-document sections and find the ones that apply. That would take ~5 minutes of network transfer time or maybe ten times more.

I've added a second retry (only when no styles are found) so `sub.domain.tld` will fallback to `domain.tld`.

> select needs styling

Done. I guess.

> auto-scroll could add a few pixels, so bottoms of buttons aren't visible.

I'd say let them be so the users would have a clue there's more UI.

> seems to be lots of styles with no preview images

Fixed.

@decembre any usercss can be installed from any site by Stylus, which is exactly the point of usercss right from its inception.

**Comment by tophf** [comment]
@decembre I guess you mean searching greasyfork in the inline search but I don't see it yet worth the effort. Maybe in several years when they have a lot more styles. We can probably add it as a standard link in another PR sometime in the future...

**Comment by decembre** [comment]
> 
> 
> @decembre I guess you mean searching greasyfork in the inline search but I don't see it yet worth the effort. Maybe in several years when they have a lot more styles. We can probably add it as a standard link in another PR sometime in the future...

Yep, that's not me the coder her...
But if we want an working alternative to userstyles.org, not in "Maybe in several years when they have a lot more style", it should be a good idea to promote a good working solution, which already exist.
USO-archives are static, no?
And if you approach Jason , i am sure you can gain quick help/solution to include an inline search in your popup.
If the GreasyFork solution gain more visibility, it gain more users which can post easily their usertyles on it too.

**Comment by tophf** [comment]
USO-archive is not static and it has 97,704 styles whereas greasyfork has 194. I don't see what to promote here.

**Comment by decembre** [comment]
> 
> 
> USO-archive is not static and it has 97,704 styles whereas greasyfork has 194. I don't see what to promote here.

Ok...
But we can't add usertyles to USO-archives directly?.
We only add a new userstyles by using this damn userstyles.org.
And by this way we promoting it.
And what's the future good challenger to it ???

**Comment by tophf** [comment]
Someone can add GreasyFork to our wiki. I won't be adding it to the inline search and I won't be bothering Jason so we'll wait either for more styles on GF or for someone to implement it for us.

**Comment by narcolepticinsomniac** [comment]
>select needs styling

>Done. I guess.

Need to wrap em so arrow stays put when popup's wider:

```
      <div class="select-resizer">
        <select id="search-order" i18n-title="sortStylesHelpTitle">
          <option value="n" i18n-text="genericTitle">
          <option value="u" i18n-text="searchResultUpdated">
          <option value="t" i18n-text="searchResultInstallCount">
          <option value="w" i18n-text="searchResultWeeklyCount">
          <option value="r" i18n-text="searchResultRating">
        </select>
        <svg class="svg-icon select-arrow"><use xlink:href="#svg-icon-select-arrow"/></svg>
      </div>
```

**Comment by tophf** [comment]
I've made the text input grow so it should be fine as the current wrapper already is flex + relative.

**Comment by narcolepticinsomniac** [comment]
Couldn't just copypasta, huh? Probably wanna put a max-width on that input, so it can't get stupid wide. Regardless, you can keep the select in place with various CSS properties - doesn't change the fact that it should be wrapped in `select-resizer` for consistency. =)

**Comment by tophf** [comment]
Fine, consistency it is. But I won't be limiting the width of the text as it looks better when it fills the entire width so I don't need to think how to align it.

**Comment by narcolepticinsomniac** [comment]
Aah, wide popups are likely few and far between. As long as nothing's broken, it's fine.

Fixes LGTM. Stuff you chose to ignore seems justifiable. I'll try to remember to keep testing for a bit, and hopefully others will as well. @Mottie @eight04

**Comment by tophf** [comment]
Uhm the sorting pref... I thought we'll use the search for a while and see if we need such a pref. Or maybe wait for someone to open an issue.

**Comment by tophf** [comment]
@33kk, you might wanna adopt the fix I found for the missing screenshots: those that end with `-after.png` (`-` not `_`) should be loaded from `https://userstyles.org/auto_style_screenshots/`, example: https://33kk.github.io/uso-archive/?style=18041

**Comment by narcolepticinsomniac** [comment]
Feels even snappier now. Rarely seeing the loading spinners, but when they're visible, their sizing seems abnormally large currently.

**Comment by tophf** [comment]
I want to set `minimum_chrome_version` to 55 and use the modern JS features like async/await syntax, the lack of which is really painful to me after having been using it in all my projects for the past few years. Now that I spend more time on Stylus, I'd like to use it here as well. Do you even see Chrome 49 in the statistics, @narcolepticinsomniac?

**Comment by narcolepticinsomniac** [comment]
> I want to set minimum_chrome_version to 55 

Go for it.

>Do you even see Chrome 49 in the statistics

Stats dashboard was redesigned, so IDK if Chromium version used to be a filter, but I'm not finding it now.

filters

**Comment by tophf** [comment]
Is it still possible to open the old dashboard?

**Comment by narcolepticinsomniac** [comment]
It's been temperamental when switching, so I'd rather not screw with it. I don't really care what the numbers are anyway, min-version bump is long overdue.

**Comment by tophf** [comment]
Nice, I async'd a few parts affected by this PR.

**Comment by tophf** [comment]
Time to merge or I'll just keep on adding micro-features here.

**Comment by narcolepticinsomniac** [comment]
Randomly testing inline search, and ran into an edge case error. Last page of Stylus UI themes, when "Dark Stylish/Stylus Interface" by Xane Myers (X-Man) is installed, it throws an error when attempting to click again to uninstall. I'm guessing it's because the style installed sets `img { display: none;}` which hides preview images, and for whatever reason, they're expected to be there.

**Comment by tophf** [comment]
We can't bind the click event to the entire entry as it has text. I'm not sure we should guard against broken styles as there are tons of ways they can break our UI but for this particular case the only workaround I see is a specificity hack to keep the image visible:

```css
#stylus#stylus#stylus#stylus .search-result-screenshot {
  display: inline !important;
  visibility: visible !important;
  opacity: 1 !important;
}
```
Then again, we can't guard against everything so I would never add this myself unless you would insist.

**Comment by narcolepticinsomniac** [comment]
>unless you would insist

Nope. Can't account for all stupidity, just giving you a heads up in case you cared.

**Comment by narcolepticinsomniac** [comment]
Unchecking "inline" and clicking "find styles" seems flaky in some scenarios.` old.reddit.com` searches `https://33kk.github.io/uso-archive/?category=old.reddit.com&search=`, which returns nothing. If you search inline, and then click the external link, it returns a valid search.

Are we doing anything funky with the "find styles" link when the popup loads? It seems to be missing the transition patch frequently, and it's the only element I see doing that.

**Comment by tophf** [comment]
Since there's a "nontrivial" subdomain `old`, the initial category is `old.reddit.com`. It's set in the link and it's used for the initial search which produces nothing so the category is recalculated to `reddit` but only if the inline search is used. People who don't want to to use the inline search wouldn't probably like if we performed a network download of the search index just to check the category for two reasons: a) if we do it automatically then we may burn traffic on a metered connection, b) if we do on click there'll be a pause for several seconds to get the updated index as it's updated frequently and we don't cache it explicitly but even if we did the first download would still produce a weird pause on click.

> anything funky with the "find styles" link

It uses our `API.openURL` which is calling chrome.tabs.create. We use it for all of our pages. I can remove it here so the browser opens the link itself. I guess there's a bug in Chrome.

**Comment by narcolepticinsomniac** [comment]
>It uses our `API.openURL`.

I think I wasn't clear. I'm talking about a transition being applied to the actual "find styles" link when opening the popup. It's the only element I see a transition erroneously applying to when the popup opens. Should be more noticeable with my dark style enabled.

If the search term issue has no good solution, so be it. Figured it was worth mentioning.

**Comment by tophf** [comment]
The link doesn't have `href` initially and we add it during init which must be the reason. Let's set some URL there.

As for the category, I guess in this case we should just go with the more generic less specific one e.g. the one we use in retry mode.

**Comment by tophf** [comment]
Done: aac0f476

**Comment by narcolepticinsomniac** [comment]
LGTM, thanks.

**Pull request merged**
