### PR TITLE
Fix: change disabled state after the content is set

### LINKED ISSUE #693: "Turn all styles off" doesn't work all of the time
* **Browser**: Firefox 66.0.3
* **Operating System**: Arch Linux
* **Stylus Version**: 1.5.3

A couple examples:
- https://pypi.org/project/utilsuneed/ with https://userstyles.org/styles/158687
- https://www.archlinux.org/packages/community/any/perl-extutils-cppguess/ with http://userstyles.org/styles/155701

PyPI project pages are unthemed after a reload, but for Arch packages I have to disable the theme.

Referencing https://github.com/openstyles/stylus/issues/525#issuecomment-482252700

### PR DESCRIPTION
**Pull request by eight04**
Fixes #693.

### CODE REVIEW

**Comment by polyzen** [comment]
Is there a simple way to test this?

**Comment by eight04** [comment]
Here is the guide to load an un-released branch as a temporary extension:
https://github.com/openstyles/stylus/wiki/Install-Stylus-from-GitHub

**Comment by polyzen** [comment]
Seems like your fix worked, but also seems like the process nuked my `stylish.sqlite`. o.O

**Comment by polyzen** [comment]
Ah, silly me, Stylus doesn't use that file. All my styles did disappear nonetheless after I removed the temporary addon and re-enabled Stylus.

**Comment by eight04** [comment]
Ouch, we should probably mention that in the wiki and tell users to back up their data.

**Comment by DanaMW** [comment]
I added a reminder to back up your styles to the instructions you linked to eight04, Right at the top should take care of that problem for you friend.

**Pull request merged**
