### PR TITLE
reuse the style config icon for other configurable stuff

### PR DESCRIPTION
**Pull request by tophf**
For some weird reason I've used an "inverted" gear icon for linter and hotkey config, but it looks weird (more like a light/dark theme switch) so this PR reuses the same icon from the manager:

image

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
We should use the same gear icon everywhere, I'd just prefer it was the solid variety. I'm a little surprised you went with the ones with super thin outlines, since you hate icon pixelation, and those are the most pixelated icons we have. They look especially bad in dark themes.

**Comment by tophf** [comment]
I see no other gear-like icons so I guess you mean the options buttons? That's something more profound, which is outside of this PR. As for the pixelation, I got used to it because this is how svg icons look in 99% of sites/pages.

Here's one from devtools:
image

We can use it (with attribution in the source I guess) or would you like to find a better one?

**Comment by narcolepticinsomniac** [comment]
> I see no other gear-like icons so I guess you mean the options buttons?

I meant the solid ones you swapped out in this PR. Good chance they were [Google material](https://material.io/resources/icons/?icon=settings&style=baseline) "settings" icon, but who knows? We've grabbed various icons from all over the place.

The one from devtools is fine, but I think it's an actual image. The one we were using was fine IMO, but it doesn't really matter, any solid gear icon with a sharp shape would do.

**Comment by narcolepticinsomniac** [comment]
> I think it's an actual image

I guess not, but they're using some sorta svg sprite-sheet, because everything about the devtools UI has to be annoying.

**Comment by tophf** [comment]
The solid one we had was so thin that it didn't look like a gear at all, but rather a simplified sun, which usually represents a day/night theme switch.

The one you linked looks good.

**Comment by tophf** [comment]
I drew it myself because including the license for such a small thing is a PITA.

image

image

**Comment by narcolepticinsomniac** [comment]
> I drew it myself

Nice, LGTM.

**Comment by tophf** [comment]
I wondered though if I should make the petals beveled and slightly inwardly slanted like the original gear icon...

Currently it's built with simple rectangles:

image

**Comment by narcolepticinsomniac** [comment]
Probably not. That kinda detail becomes detrimental at icon sizes IMO. Ends up looking like a sun weather icon.

**Pull request merged**
