### PR TITLE
separate storage for order + important styles

### PR DESCRIPTION
**Pull request by tophf**
Turns out each id is quite long (36 bytes of UUID + 3 bytes of JSON-stringification) so my 130 styles ended up filling our `prefs` value to almost 8kB which is the maximum length in the sync storage. This PR extracts the order into a separate storage item ~and packs the ids to 25 bytes so we can store 320 styles~, no artificial limit now.

Added important styles.

I've removed the `≡` symbol because we can drag the entire row anyway so its presence is just a decoration, which started to compete for attention with the toggle mark on the right that I added. Tried several unicode thingamajigs but ended up with a ~simple circle~ star.

### CODE REVIEW

**Comment by eight04** [comment]
Another way is to store style specific settings in DB. For example, we can create a document with a special ID:
```js
{
  _id: '_prefs', //  a special ID
  injectionOrder: [...],
  otherStyleRelatedSettings: ...
}
```
Then insert it into DB so it can be synced/exported with other styles.

Just make sure to hide documents with special IDs from normal styles API.

**Comment by tophf** [comment]
It sounds better because someone may have more than 320 styles. I'll try it.

**Comment by tophf** [comment]
Seems to work.

**Comment by tophf** [comment]
Found a good solution that resolves my worries: a star icon. It's used to bookmark things in browser's UI as well as in web pages so the users would guess the purpose of the symbol is to mark the style as important.

**Comment by tophf** [comment]
SVG icon:

image

**Comment by tophf** [comment]
BTW this svg icon is completely messed up in `Stylus Insomniac` style, which is why I didn't want to use svg for the split buttons. I guess I'll use a font here too just like we do for the sort symbol.

**Comment by narcolepticinsomniac** [comment]
> BTW this svg icon is completely messed up in `Stylus Insomniac` style

I don't think we can pretend that style's a good test case anymore. There's new changes unaccounted for, and a lot of leftover, potentially detrimental properties specified, which wouldn't work as originally intended 4+ years ago. 

I wouldn't exactly recommend it anymore. Specificity overrides have gotten ridiculous. It needs a rewrite, but I keep putting it off, and haven't bothered with convoluting it any further in the meantime to fix things.

> I'll probably try combining all of our svg icons in one font semi-automatically

It's a PITA, but I did [a base64 version](https://gist.github.com/narcolepticinsomniac/4efb48f2261dffa2b2073b56741a0793#file-custom-native-html5-player-with-shortcuts-user-js-L1819) for like 12+ icons, and was surprised how reasonable the size was.


That sort icon in the screenshot looks pretty good, actually. Maybe even better if they weren't crammed inside a button. Arrows aren't quite as obvious, but I guess their fine too.

**Comment by tophf** [comment]
> Maybe even better if they weren't crammed inside a button

Yeah, tried that, but it gave an impression of something very unimportant like the button above to view the update history.

I've simplified the icon to give it more breathing room:

image

**Comment by tophf** [comment]
So I guess this is good to merge now?

**Comment by narcolepticinsomniac** [comment]
Changes made in the injection order dialog are all substantial improvements.

Only little detail I dislike is the thick border on the bottom square of the new icon. It would look better to reuse the same shape/thickness as the thinner rectangle on top. Considering the functionality, it might be more accurate to flip the arrow, since dragging down will be the more common action, but NBD either way.

**Comment by tophf** [comment]
image

**Pull request merged**
