### PR TITLE
autosave in editor

### LINKED ISSUE #1303: Feature suggestion: Autosaving styles
* **Browser**: Firefox 90
* **Operating System**: macOS 11.0.1
* **Stylus Version**: 1.5.19

Firefox crashes sometimes for me, and it seems like Stylus doesn't recover code from last session if so. An autosave feature would be really useful in situations like this.

### PR DESCRIPTION
**Pull request by tophf**
Fixes #1303.

Unsaved changes in the editor are stored as a draft for this style id.

Saving removes the draft.

Opening the editor for this style will show a prompt:

image

The timer is `10` seconds, customizable in devtools console: `prefs.set('editor.autosaveDelay', 1)`.
Didn't add it in UI because there's a lot of settings already so I thought I'll implement CodeMirror-related stuff first (#1083).

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
So... calling this 'autosave' seems kinda misleading. AFAICT, if you exit the editor, after confirming you don't wanna save, it saves it as a draft anyway, and then offers that unsaved draft as an option next time the style gets opened.

While that's not a terrible idea, it's a borderline edge case that you'd wanna recover a draft you explicitly declined to save already. It also appears to only work on usercss pages currently. 

Good chance I'm missing the bigger picture here, because I'm not really seeing the point, or how this qualifies as 'autosave' in the commonly understood definition of such a feature.

**Comment by tophf** [comment]
It helps when the browser/extension/computer crashes so it's not an autosave per se, but rather auto-recovery. It works with sectioned styles for me.

**Comment by narcolepticinsomniac** [comment]
> It works with sectioned styles for me.

Alright, I see it now too. Must've been a timing issue, or something.

> It helps when the browser/extension/computer crashes

Sure, a crash would be a solid edge case to account for. Not sure if 'yes', or 'no', or neither should be focused/highlighted.

What about a real autosave feature? Too much potential for disaster? People who like it must know what they're getting into.

**Comment by tophf** [comment]
I just realized I should probably delete the draft when the user exits/reloads the editor and agrees to abandon changes when prompted by the browser?

> What about a real autosave feature? 

Can't say. I'm using live-preview so I don't need autosave.

**Comment by narcolepticinsomniac** [comment]
> delete the draft when the user exits/reloads the editor and agrees to abandon changes when prompted by the browser

I'd say so. This is more a fail-safe.

**Pull request merged**
