### PR TITLE
For Firefox and Chrome

### PR DESCRIPTION
**Pull request by yoasif**
Instead of for Chrome and Chrome-like.

### CODE REVIEW

**Comment by tophf** [comment]
Chrome is the original platform for this extension so it should be the first, moreover currently only Chrome supports the API fully and it's relatively more robust.

I also think `things` can be omitted.

```
Stylus: a fork of Stylish for Chrome and Firefox
```

**Comment by tophf** [comment]
For the sake of technical precision: "Stylus is a fork of Stylish for Chrome, also compatible with Firefox as a WebExtension"

**Comment by narcolepticinsomniac** [comment]
>"Stylus is a fork of Stylish for Chrome, also compatible with Firefox as a WebExtension"

LGTM.

**Comment by schomery** [comment]
> Stylus is a fork of Stylish for Chrome, also compatible with Firefox as a WebExtension

+1

**Comment by tophf** [comment]
Okay, implemented in 78d76978450b0c137fbcbf495f4e01c0c0e492c8

**Pull request closed without merging**
