### PR TITLE
menus as dialogs

### PR DESCRIPTION
**Pull request by narcolepticinsomniac**
I think it's better in general, and also eliminates the glitchiness of expandable menus in FF, not to mention possible scroll issues on long style lists with overflow, plus the fact that we could add many menu items in the future without the menu looking ridiculous.

IDEK how the formatting got screwed up and borked the diffs in the other PR. I updated my editor config plugin, so let's see if that helps. I restarted with a fresh master and copy/pasted the changes, so if it's still screwy, I guess my editor needs more help. If not, I'm not playing around with it anymore right now, and the other PR does at least work.

### CODE REVIEW

**Comment by narcolepticinsomniac** [comment]
@eight04 I ran this by @Mottie already and he prefers it as well. Tweaks made to the delete and confirm functions also eliminate the errors on deletion and on exclusions made after cancellation of deletion. Wish I could take credit, but it was really just a dumb luck coincidence. Unless you have any thoughts or suggestions, I think we'll probably merge this one shortly also.

**Comment by eight04** [comment]
If we want to switch to dialogs, we should refactor the dialog service so they can share the same code. Also, we no longer have to create hidden menu elements for each entry inside DOM.

Should we change the icon to something like `...`? Or change it to `>` and make the dialog slide-in from the right side?

**Comment by narcolepticinsomniac** [comment]
>Should we change the icon to something like ...? Or change it to > and make the dialog slide-in from the right side?

The icon is fine IMO, and I like the fact that it's pretty narrow. Reusing the little fade in animation from the confirmation dialog also looks pretty decent to me, but I'd be open to alternatives if you feel like trying something else.

> If we want to switch to dialogs, we should refactor the dialog service so they can share the same code. Also, we no longer have to create hidden menu elements for each entry inside DOM.

Figured you might say that. The exclusion code also currently relies on individual entries and menus, so this is just a lazy implementation for menus to mimic dialogs. Not like it adds any elements which weren't already there, just changes their appearance. 

As far as refactoring the dialog service, exclusions would also need some refactoring, which makes it more of a chore to optimize the code for the sake of achieving the same exact end goal. The lazy implementation here isn't any more or less optimized than the expandable menu version. Sure, it could be, but if it ain't broke, I'm not trying to fix it. Not only does it work, it resolves those minor issues in previous versions.

One way or the other, I think the dialog implementation is the way to go. Up to you if you think optimization is worth the time and effort. I pinged you in case it's something you think is worthwhile, but it's not a necessity IMO.

**Comment by narcolepticinsomniac** [comment]
AMO's gonna be looking for a mandatory update sometime this week for their "recommended extension" program, and I'd prefer exclusions be included this time around. As with simplified toggles, mimicking dialogs is a "good enough" improvement on expandable menus. Refactoring the dialog service would be an improvement which could be done in a separate PR beforehand or later on down the road, depending on how much you wanna prioritize it.

**Pull request merged**
