### PR TITLE
Add: responsive layout for usercss-install.html

### LINKED ISSUE #250: [Suggestion]Adapt to the page based on the width of the device
I wrote some adaptive styles, like [add0n.com 360x640 Reading Mode](https://userstyles.org/styles/150552), but when I tested on different devices I found Stylus itself was not able to adapt to the web page.
In Stylus's CSS source, `@media max-width` has been used to support screens of different widths, but in` edit.html`, `manage.html`,` options.html`, `popup.html` Source code, and did not add the same page as `install-usercss.html` Adaptive code:

```html
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
```

### PR DESCRIPTION
**Pull request by eight04**
Fixes #250.
screen shot 2017-11-22 at 14 13 59

### CODE REVIEW

**Comment by tophf** [comment]
Damn, you didn't respond to the question and I've fixed this yesterday.

**Comment by tophf** [comment]
Join us in dev chat https://discord.gg/tzXVNJz (runs in browser or as a dedicated app)

**Comment by eight04** [comment]
Sorry for that. I was working on other stuff these days. Should I close this PR?

**Comment by tophf** [comment]
Compare it to the one I did 431d9f1ff31ac206a042286d6384c7bd12522ac7, please. I don't know why you did all those changes so maybe mine isn't sufficient (it has a known bug with no scrollbar in the narrow code which I plan to fix of course).

**Comment by eight04** [comment]
Here is a screenshot of https://github.com/openstyles/stylus/commit/431d9f1ff31ac206a042286d6384c7bd12522ac7 on Firefox.
screen shot 2017-11-22 at 16 22 02

They are pretty much the same, we can use one column when the screen is really small. I can see the scrollbar in the code box, but didn't test it on a real device.

**Comment by tophf** [comment]
Yep, had to rearrange quite a bit, otherwise CodeMirror with a long style didn't scroll (same as in your PR).

**Pull request closed without merging**
